#include "ORB_OMS_RCS_CONN.h"


namespace dps
{
	// K-Loads
	constexpr int OMS_ULLAGE_PRESS_LOWER_LMT = 236;// OMS TANK PRESS INIT LIMIT [psi] (V97U9822C)
	constexpr float PRESS_TIME_DELAY = 30.0f;// OMS TANK PRESS TIME [psi] (V97U9823C)


	ORB_OMS_RCS_CONN::ORB_OMS_RCS_CONN( SimpleGPCSystem *_gpc ):SimpleGPCSoftware( _gpc, "ORB_OMS_RCS_CONN" ),
		INTERCONNECT_INITIATION_FLAG(0), PRE_SEQ_CMD_TERM_FLAG(0), REPRESS_ACTIVE_FLAG(0),
		firstpass_step2(true), firstpass_stepa1_2(true),
		timer_step2(0.0), timer_stepa1_1(0.0), timer_stepa1_2(0.0), timerena_step2(true), timerena_stepa1_1(true), timerena_stepa1_2(true)
	{
		return;
	}

	ORB_OMS_RCS_CONN::~ORB_OMS_RCS_CONN( void )
	{
		return;
	}

	void ORB_OMS_RCS_CONN::OnPostStep( double simt, double simdt, double mjd )
	{
		unsigned short FA_1_INPUT_PROM_SEG_1_2_STATUS = 0;// TODO V91X2841X
		unsigned short FA_2_INPUT_PROM_SEG_1_2_STATUS = 0;// TODO V91X2841X

		// handle timers
		if (timerena_step2) timer_step2 += simdt;
		if (timerena_stepa1_1) timer_stepa1_1 += simdt;
		if (timerena_stepa1_2) timer_stepa1_2 += simdt;


	//step1:
		WriteCOMPOOL_IS( SCP_LT_OMS_HEVAPOR_ISO_VLV_MISCOM, 0 );
		WriteCOMPOOL_IS( SCP_RT_OMS_HEVAPOR_ISO_VLV_MISCOM, 0 );

		if (INTERCONNECT_INITIATION_FLAG == 1)
		{
			PRE_SEQ_CMD_TERM_FLAG = 1;
			INTERCONNECT_INITIATION_FLAG = 0;

			SubsequenceB();
		}
		else
		{
			if (PRE_SEQ_CMD_TERM_FLAG == 0)
			{
				goto step2;
			}
		}

		if ((ReadCOMPOOL_IS( SCP_LOMS_TO_AFT_RCS_PRESS_ENA ) == 0) && (ReadCOMPOOL_IS( SCP_ROMS_TO_AFT_RCS_PRESS_ENA ) == 0))
		{
			INTERCONNECT_INITIATION_FLAG = 1;
			REPRESS_ACTIVE_FLAG = 0;
			OMS_L_POD_HE_ISLN_VLV_A_OP = 0;
			OMS_L_POD_HE_ISLN_VLV_B_OP = 0;
			OMS_L_POD_VAPOR_ISLN_VLV_1_OP = 0;
			OMS_L_POD_VAPOR_ISLN_VLV_2_OP = 0;
			OMS_R_POD_HE_ISLN_VLV_A_OP = 0;
			OMS_R_POD_HE_ISLN_VLV_B_OP = 0;
			OMS_R_POD_VAPOR_ISLN_VLV_1_OP = 0;
			OMS_R_POD_VAPOR_ISLN_VLV_2_OP = 0;
		}

		goto terminatesequence;


	step2:
		if ((FA_1_INPUT_PROM_SEG_1_2_STATUS == 0) && (FA_2_INPUT_PROM_SEG_1_2_STATUS == 0))
		{
			SubsequenceA();
		}
		else
		{
			if (REPRESS_ACTIVE_FLAG == 1)
			{
				if (firstpass_step2)
				{
					firstpass_step2 = false;
					timer_step2 = 0.0;
					timerena_step2 = true;
				}

				if (timer_step2 >= PRESS_TIME_DELAY)
				{
					OMS_L_POD_HE_ISLN_VLV_A_OP = 0;
					OMS_L_POD_HE_ISLN_VLV_B_OP = 0;
					OMS_L_POD_VAPOR_ISLN_VLV_1_OP = 0;
					OMS_L_POD_VAPOR_ISLN_VLV_2_OP = 0;
					OMS_R_POD_HE_ISLN_VLV_A_OP = 0;
					OMS_R_POD_HE_ISLN_VLV_B_OP = 0;
					OMS_R_POD_VAPOR_ISLN_VLV_1_OP = 0;
					OMS_R_POD_VAPOR_ISLN_VLV_2_OP = 0;
					REPRESS_ACTIVE_FLAG = 0;

					timerena_step2 = false;
				}
			}
		}

		goto terminatesequence;


	terminatesequence:
		// outputs
		unsigned short FA1_IOM7_CH1 = 0;
		unsigned short FA1_IOM7_CH2 = 0;
		unsigned short FA1_IOM15_CH1 = 0;
		unsigned short FA1_IOM15_CH2 = 0;
		unsigned short FA2_IOM7_CH1 = 0;
		unsigned short FA2_IOM7_CH2 = 0;
		unsigned short FA2_IOM15_CH1 = 0;
		unsigned short FA2_IOM15_CH2 = 0;
		unsigned short FA3_IOM7_CH1 = 0;
		unsigned short FA3_IOM7_CH2 = 0;
		unsigned short FA3_IOM15_CH1 = 0;
		unsigned short FA3_IOM15_CH2 = 0;
		unsigned short FA4_IOM7_CH1 = 0;
		unsigned short FA4_IOM7_CH2 = 0;
		unsigned short FA4_IOM15_CH1 = 0;
		unsigned short FA4_IOM15_CH2 = 0;

		FA2_IOM7_CH1 |= (OMS_L_POD_XFD_VLVS_A_CMD_1_CL & 0b1) << 12;
		FA1_IOM7_CH1 |= (OMS_L_POD_OXDZR_XFD_VLV_A_CMD_2_CL & 0b1) << 12;
		FA1_IOM7_CH1 |= (OMS_L_POD_FUEL_XFD_VLV_A_CMD_2_CL & 0b1) << 8;
		FA1_IOM15_CH1 |= (OMS_L_POD_XFD_VLVS_B_CMD_1_CL & 0b1) << 12;
		FA2_IOM15_CH1 |= (OMS_L_POD_OXDZR_XFD_VLV_B_CMD_2_CL & 0b1) << 12;
		FA2_IOM15_CH1 |= (OMS_L_POD_FUEL_XFD_VLV_B_CMD_2_CL & 0b1) << 8;

		FA1_IOM15_CH1 |= (OMS_R_POD_XFD_VLVS_A_CMD_1_CL & 0b1) << 14;
		FA1_IOM7_CH1 |= (OMS_R_POD_OXDZR_XFD_VLV_A_CMD_2_CL & 0b1) << 14;
		FA1_IOM7_CH1 |= (OMS_R_POD_FUEL_XFD_VLV_A_CMD_2_CL & 0b1) << 10;
		FA1_IOM15_CH1 |= (OMS_R_POD_XFD_VLVS_B_CMD_1_CL & 0b1) << 14;
		FA2_IOM15_CH1 |= (OMS_R_POD_OXDZR_XFD_VLV_B_CMD_2_CL & 0b1) << 14;
		FA2_IOM15_CH1 |= (OMS_R_POD_FUEL_XFD_VLV_B_CMD_2_CL & 0b1) << 10;

		FA4_IOM7_CH2 |= (RCS_L_AFT_XFD_VLV_12_GPC_CL_A & 0b1) << 0;
		FA3_IOM7_CH2 |= (RCS_L_AFT_OX_XFD_VLV_12_GPC_CL_B & 0b1) << 0;
		FA3_IOM15_CH2 |= (RCS_L_AFT_FU_XFD_VLV_12_GPC_CL_B & 0b1) << 9;
		FA1_IOM7_CH2 |= (RCS_L_AFT_XFD_VLV_345_GPC_CL_A & 0b1) << 0;
		FA2_IOM7_CH2 |= (RCS_L_AFT_OX_XFD_V_345_GPC_CL_B & 0b1) << 0;
		FA2_IOM7_CH2 |= (RCS_L_AFT_FU_XFD_V_345_GPC_CL_B & 0b1) << 2;

		FA3_IOM15_CH2 |= (RCS_R_AFT_XFD_VLV_12_GPC_CL_A & 0b1) << 0;
		FA4_IOM15_CH2 |= (RCS_R_AFT_OX_XFD_V_12_GPC_CL_B & 0b1) << 0;
		FA4_IOM15_CH2 |= (RCS_R_AFT_FU_XFD_V_12_GPC_CL_B & 0b1) << 9;
		FA2_IOM15_CH2 |= (RCS_R_AFT_XFD_VLV_345_GPC_CL_A & 0b1) << 0;
		FA1_IOM15_CH2 |= (RCS_R_AFT_OX_XFD_V_345_GPC_CL_B & 0b1) << 0;
		FA1_IOM15_CH2 |= (RCS_R_AFT_FU_XFD_V_345_GPC_CL_B & 0b1) << 2;

		FA2_IOM7_CH2 |= (RCS_L_AFT_TK_ISLN_V_12_GPC_CL_A & 0b1) << 4;
		FA1_IOM7_CH2 |= (RCS_L_AFT_OX_TK_ISLN_V12_GPC_CL_B & 0b1) << 4;
		FA1_IOM7_CH2 |= (RCS_L_AFT_FU_TK_ISLN_V12_GPC_CL_B & 0b1) << 2;
		FA3_IOM7_CH2 |= (RCS_L_AFT_OX_TK_ISLN_V345_A_GPC_CL & 0b1) << 4;
		FA3_IOM7_CH2 |= (RCS_L_AFT_FU_TK_ISLN_V345_A_GPC_CL & 0b1) << 2;
		FA4_IOM7_CH2 |= (RCS_L_AFT_OX_TK_ISLN_V345_B_GPC_CL & 0b1) << 4;
		FA4_IOM7_CH2 |= (RCS_L_AFT_FU_TK_ISLN_V345_B_GPC_CL & 0b1) << 2;

		FA1_IOM15_CH2 |= (RCS_R_AFT_TK_ISLN_V_12_GPC_CL_A & 0b1) << 4;
		FA2_IOM15_CH2 |= (RCS_R_AFT_OX_TK_ISLN_V_12_GPC_CL_B & 0b1) << 4;
		FA2_IOM15_CH2 |= (RCS_R_AFT_FU_TK_ISLN_V_12_GPC_CL_B & 0b1) << 2;
		FA3_IOM15_CH2 |= (RCS_R_AFT_OX_TK_ISLN_V345_A_GPC_CL & 0b1) << 4;
		FA3_IOM15_CH2 |= (RCS_R_AFT_FU_TK_ISLN_V345_A_GPC_CL & 0b1) << 2;
		FA4_IOM15_CH2 |= (RCS_R_AFT_OX_TK_ISLN_V345_B_GPC_CL & 0b1) << 4;
		FA4_IOM15_CH2 |= (RCS_R_AFT_FU_TK_ISLN_V345_B_GPC_CL & 0b1) << 2;

		FA2_IOM7_CH1 |= (OMS_L_POD_XFD_VLVS_A_CMD_1_OP & 0b1) << 11;
		FA1_IOM7_CH1 |= (OMS_L_POD_OXDZR_XFD_VLV_A_CMD_2_OP & 0b1) << 11;
		FA1_IOM7_CH1 |= (OMS_L_POD_FUEL_XFD_VLV_A_CMD_2_OP & 0b1) << 7;
		FA1_IOM15_CH1 |= (OMS_L_POD_XFD_VLVS_B_CMD_1_OP & 0b1) << 11;
		FA2_IOM15_CH1 |= (OMS_L_POD_OXDZR_XFD_VLV_B_CMD_2_OP & 0b1) << 11;
		FA2_IOM15_CH1 |= (OMS_L_POD_FUEL_XFD_VLV_B_CMD_2_OP & 0b1) << 7;

		FA1_IOM15_CH1 |= (OMS_R_POD_XFD_VLVS_A_CMD_1_OP & 0b1) << 13;
		FA1_IOM7_CH1 |= (OMS_R_POD_OXDZR_XFD_VLV_A_CMD_2_OP & 0b1) << 13;
		FA1_IOM7_CH1 |= (OMS_R_POD_FUEL_XFD_VLV_A_CMD_2_OP & 0b1) << 9;
		FA1_IOM15_CH1 |= (OMS_R_POD_XFD_VLVS_B_CMD_1_OP & 0b1) << 13;
		FA2_IOM15_CH1 |= (OMS_R_POD_OXDZR_XFD_VLV_B_CMD_2_OP & 0b1) << 13;
		FA2_IOM15_CH1 |= (OMS_R_POD_FUEL_XFD_VLV_B_CMD_2_OP & 0b1) << 9;

		FA4_IOM7_CH2 |= (RCS_L_AFT_XFD_VLV_12_GPC_OP_A & 0b1) << 1;
		FA3_IOM7_CH2 |= (RCS_L_AFT_OX_XFD_VLV_12_GPC_OP_B & 0b1) << 1;
		FA3_IOM15_CH2 |= (RCS_L_AFT_FU_XFD_VLV_12_GPC_OP_B & 0b1) << 10;
		FA1_IOM7_CH2 |= (RCS_L_AFT_XFD_VLV_345_GPC_OP_A & 0b1) << 1;
		FA2_IOM7_CH2 |= (RCS_L_AFT_OX_XFD_V_345_GPC_OP_B & 0b1) << 1;
		FA2_IOM7_CH2 |= (RCS_L_AFT_FU_XFD_V_345_GPC_OP_B & 0b1) << 3;

		FA3_IOM15_CH2 |= (RCS_R_AFT_XFD_VLV_12_GPC_OP_A & 0b1) << 1;
		FA4_IOM15_CH2 |= (RCS_R_AFT_OX_XFD_V_12_GPC_OP_B & 0b1) << 1;
		FA4_IOM15_CH2 |= (RCS_R_AFT_FU_XFD_V_12_GPC_OP_B & 0b1) << 10;
		FA2_IOM15_CH2 |= (RCS_R_AFT_XFD_VLV_345_GPC_OP_A & 0b1) << 1;
		FA1_IOM15_CH2 |= (RCS_R_AFT_OX_XFD_V_345_GPC_OP_B & 0b1) << 1;
		FA1_IOM15_CH2 |= (RCS_R_AFT_FU_XFD_V_345_GPC_OP_B & 0b1) << 3;

		FA2_IOM7_CH2 |= (RCS_L_AFT_TK_ISLN_V_12_GPC_OP_A & 0b1) << 5;
		FA1_IOM7_CH2 |= (RCS_L_AFT_OX_TK_ISLN_V_12_GPC_OP_B & 0b1) << 5;
		FA1_IOM7_CH2 |= (RCS_L_AFT_FU_TK_ISLN_V_12_GPC_OP_B & 0b1) << 3;
		FA3_IOM7_CH2 |= (RCS_L_AFT_OX_TK_ISLN_V_345_A_GPC_OP & 0b1) << 5;
		FA3_IOM7_CH2 |= (RCS_L_AFT_FU_TK_ISLN_V_345_A_GPC_OP & 0b1) << 3;
		FA4_IOM7_CH2 |= (RCS_L_AFT_OX_TK_ISLN_V_345_B_GPC_OP & 0b1) << 5;
		FA4_IOM7_CH2 |= (RCS_L_AFT_FU_TK_ISLN_V_345_B_GPC_OP & 0b1) << 3;

		FA1_IOM15_CH2 |= (RCS_R_AFT_TK_ISLN_V_12_GPC_OP_A & 0b1) << 5;
		FA2_IOM15_CH2 |= (RCS_R_AFT_OX_TK_ISLN_V_12_GPC_OP_B & 0b1) << 5;
		FA2_IOM15_CH2 |= (RCS_R_AFT_FU_TK_ISLN_V_12_GPC_OP_B & 0b1) << 3;
		FA3_IOM15_CH2 |= (RCS_R_AFT_OX_TK_ISLN_V_345_A_GPC_OP & 0b1) << 5;
		FA3_IOM15_CH2 |= (RCS_R_AFT_FU_TK_ISLN_V_345_A_GPC_OP & 0b1) << 3;
		FA4_IOM15_CH2 |= (RCS_R_AFT_OX_TK_ISLN_V_345_B_GPC_OP & 0b1) << 5;
		FA4_IOM15_CH2 |= (RCS_R_AFT_FU_TK_ISLN_V_345_B_GPC_OP & 0b1) << 3;

		FA2_IOM7_CH1 |= (OMS_L_POD_TK_VLVS_A_CMD_1_OP & 0b1) << 5;
		FA2_IOM7_CH1 |= (OMS_L_POD_TK_VLVS_A_CMD_1_CL & 0b1) << 6;
		FA1_IOM7_CH1 |= (OMS_L_POD_OXDZR_ISLN_V_A_CMD_2_OP & 0b1) << 5;
		FA1_IOM7_CH1 |= (OMS_L_POD_OXDZR_ISLN_V_A_CMD_2_CL & 0b1) << 6;
		FA1_IOM15_CH1 |= (OMS_L_POD_TK_VLVS_B_CMD_1_OP & 0b1) << 5;
		FA1_IOM15_CH1 |= (OMS_L_POD_TK_VLVS_B_CMD_1_CL & 0b1) << 6;
		FA2_IOM15_CH1 |= (OMS_L_POD_OXDZR_ISLN_V_B_CMD_2_OP & 0b1) << 5;
		FA2_IOM15_CH1 |= (OMS_L_POD_OXDZR_ISLN_V_B_CMD_2_CL & 0b1) << 6;
		FA1_IOM7_CH1 |= (OMS_L_POD_FUEL_ISLN_VLV_A_CMD_2_OP & 0b1) << 3;
		FA1_IOM7_CH1 |= (OMS_L_POD_FUEL_ISLN_VLV_A_CMD_2_CL & 0b1) << 4;
		FA2_IOM15_CH1 |= (OMS_L_POD_FUEL_ISLN_VLV_B_CMD_2_OP & 0b1) << 3;
		FA2_IOM15_CH1 |= (OMS_L_POD_FUEL_ISLN_VLV_B_CMD_2_CL & 0b1) << 4;

		FA3_IOM7_CH1 |= (OMS_R_POD_TK_VLVS_A_CMD_1_OP & 0b1) << 5;
		FA3_IOM7_CH1 |= (OMS_R_POD_TK_VLVS_A_CMD_1_CL & 0b1) << 6;
		FA4_IOM7_CH1 |= (OMS_R_POD_OXDZR_ISLN_V_A_CMD_2_OP & 0b1) << 5;
		FA4_IOM7_CH1 |= (OMS_R_POD_OXDZR_ISLN_V_A_CMD_2_CL & 0b1) << 6;
		FA4_IOM15_CH1 |= (OMS_R_POD_TK_VLVS_B_CMD_1_OP & 0b1) << 5;
		FA4_IOM15_CH1 |= (OMS_R_POD_TK_VLVS_B_CMD_1_CL & 0b1) << 6;
		FA3_IOM15_CH1 |= (OMS_R_POD_OXDZR_ISLN_V_B_CMD_2_OP & 0b1) << 5;
		FA3_IOM15_CH1 |= (OMS_R_POD_OXDZR_ISLN_V_B_CMD_2_CL & 0b1) << 6;
		FA4_IOM7_CH1 |= (OMS_R_POD_FUEL_ISLN_VLV_A_CMD_2_OP & 0b1) << 3;
		FA4_IOM7_CH1 |= (OMS_R_POD_FUEL_ISLN_VLV_A_CMD_2_CL & 0b1) << 4;
		FA3_IOM15_CH1 |= (OMS_R_POD_FUEL_ISLN_VLV_B_CMD_2_OP & 0b1) << 3;
		FA3_IOM15_CH1 |= (OMS_R_POD_FUEL_ISLN_VLV_B_CMD_2_CL & 0b1) << 4;

		FA1_IOM15_CH1 |= (OMS_L_POD_HE_ISLN_VLV_A_OP & 0b1) << 2;
		FA2_IOM15_CH1 |= (OMS_L_POD_HE_ISLN_VLV_B_OP & 0b1) << 2;
		FA1_IOM7_CH1 |= (OMS_L_POD_VAPOR_ISLN_VLV_1_OP & 0b1) << 2;
		FA2_IOM7_CH1 |= (OMS_L_POD_VAPOR_ISLN_VLV_2_OP & 0b1) << 2;
		FA3_IOM15_CH1 |= (OMS_R_POD_HE_ISLN_VLV_A_OP & 0b1) << 2;
		FA4_IOM15_CH1 |= (OMS_R_POD_HE_ISLN_VLV_B_OP & 0b1) << 2;
		FA3_IOM7_CH1 |= (OMS_R_POD_VAPOR_ISLN_VLV_1_OP & 0b1) << 2;
		FA4_IOM7_CH1 |= (OMS_R_POD_VAPOR_ISLN_VLV_2_OP & 0b1) << 2;


		unsigned short tmp = ReadCOMPOOL_IS( SCP_FA1_IOM7_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA1_IOM7_CH1_DATA, tmp | FA1_IOM7_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA1_IOM7_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA1_IOM7_CH2_DATA, tmp | FA1_IOM7_CH2 );

		tmp = ReadCOMPOOL_IS( SCP_FA1_IOM15_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA1_IOM15_CH1_DATA, tmp | FA1_IOM15_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA1_IOM15_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA1_IOM15_CH2_DATA, tmp | FA1_IOM15_CH2 );

		tmp = ReadCOMPOOL_IS( SCP_FA2_IOM7_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA2_IOM7_CH1_DATA, tmp | FA2_IOM7_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA2_IOM7_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA2_IOM7_CH2_DATA, tmp | FA2_IOM7_CH2 );

		tmp = ReadCOMPOOL_IS( SCP_FA2_IOM15_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA2_IOM15_CH1_DATA, tmp | FA2_IOM15_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA2_IOM15_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA2_IOM15_CH2_DATA, tmp | FA2_IOM15_CH2 );

		tmp = ReadCOMPOOL_IS( SCP_FA3_IOM7_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA3_IOM7_CH1_DATA, tmp | FA3_IOM7_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA3_IOM7_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA3_IOM7_CH2_DATA, tmp | FA3_IOM7_CH2 );

		tmp = ReadCOMPOOL_IS( SCP_FA3_IOM15_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA3_IOM15_CH1_DATA, tmp | FA3_IOM15_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA3_IOM15_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA3_IOM15_CH2_DATA, tmp | FA3_IOM15_CH2 );

		tmp = ReadCOMPOOL_IS( SCP_FA4_IOM7_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA4_IOM7_CH1_DATA, tmp | FA4_IOM7_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA4_IOM7_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA4_IOM7_CH2_DATA, tmp | FA4_IOM7_CH2 );

		tmp = ReadCOMPOOL_IS( SCP_FA4_IOM15_CH1_DATA );
		WriteCOMPOOL_IS( SCP_FA4_IOM15_CH1_DATA, tmp | FA4_IOM15_CH1 );

		tmp = ReadCOMPOOL_IS( SCP_FA4_IOM15_CH2_DATA );
		WriteCOMPOOL_IS( SCP_FA4_IOM15_CH2_DATA, tmp | FA4_IOM15_CH2 );
		return;
	}

	void ORB_OMS_RCS_CONN::SubsequenceA( void )
	{
		float OMS_L_POD_OXDZR_TANK_ULLAGE_PRESS = 0.0f;// TODO V43P4221C
		float OMS_L_POD_FUEL_TANK_ULLAGE_PRESS = 0.0f;// TODO V43P4321C
		float OMS_R_POD_OXDZR_TANK_ULLAGE_PRESS = 0.0f;// TODO V43P5221C
		float OMS_R_POD_FUEL_TANK_ULLAGE_PRESS = 0.0f;// TODO V43P5321C

		unsigned short FA1_IOM3_CH1 = ReadCOMPOOL_IS( SCP_FA1_IOM3_CH1_DATA );
		unsigned short FA1_IOM11_CH1 = ReadCOMPOOL_IS( SCP_FA1_IOM11_CH1_DATA );
		unsigned short FA2_IOM3_CH1 = ReadCOMPOOL_IS( SCP_FA2_IOM3_CH1_DATA );
		unsigned short FA2_IOM11_CH1 = ReadCOMPOOL_IS( SCP_FA2_IOM11_CH1_DATA );
		unsigned short FA3_IOM3_CH1 = ReadCOMPOOL_IS( SCP_FA3_IOM3_CH1_DATA );
		unsigned short FA3_IOM11_CH1 = ReadCOMPOOL_IS( SCP_FA3_IOM11_CH1_DATA );
		unsigned short FA4_IOM3_CH1 = ReadCOMPOOL_IS( SCP_FA4_IOM3_CH1_DATA );
		unsigned short FA4_IOM11_CH1 = ReadCOMPOOL_IS( SCP_FA4_IOM11_CH1_DATA );

		unsigned short OMS_L_POD_HE_ISLN_VLV_A_POSN_OP = (FA1_IOM11_CH1 >> 4) & 0b1;// V43X4152X
		unsigned short OMS_L_POD_HE_ISLN_VLV_B_POSN_OP = (FA2_IOM11_CH1 >> 4) & 0b1;// V43X4154X
		unsigned short OMS_L_POD_VAPOR_ISLN_VLV_1_POSN_OP = (FA1_IOM3_CH1 >> 4) & 0b1;// V43X4156X
		unsigned short OMS_L_POD_VAPOR_ISLN_VLV_2_POSN_OP = (FA2_IOM3_CH1 >> 4) & 0b1;// V43X4158X
		unsigned short OMS_R_POD_HE_ISLN_VLV_A_POSN_OP = (FA3_IOM11_CH1 >> 4) & 0b1;// V43X5152X
		unsigned short OMS_R_POD_HE_ISLN_VLV_B_POSN_OP = (FA4_IOM11_CH1 >> 4) & 0b1;// V43X5154X
		unsigned short OMS_R_POD_VAPOR_ISLN_VLV_1_POSN_OP = (FA3_IOM3_CH1 >> 4) & 0b1;// V43X5156X
		unsigned short OMS_R_POD_VAPOR_ISLN_VLV_2_POSN_OP = (FA4_IOM3_CH1 >> 4) & 0b1;// V43X5158X

		unsigned short FA_1_INPUT_PROM_SEG_3_10_STATUS = 0;// TODO V91X2845X
		unsigned short FA_2_INPUT_PROM_SEG_3_10_STATUS = 0;// TODO V91X2846X
		unsigned short FA_3_INPUT_PROM_SEG_3_10_STATUS = 0;// TODO V91X2847X
		unsigned short FA_4_INPUT_PROM_SEG_3_10_STATUS = 0;// TODO V91X2848X

	//stepA1:
		if (REPRESS_ACTIVE_FLAG == 0)
		{
			if (ReadCOMPOOL_IS( SCP_OMS_PRESS_ENA_INHIBIT ) == 0)
			{
				if (((OMS_L_POD_OXDZR_TANK_ULLAGE_PRESS < OMS_ULLAGE_PRESS_LOWER_LMT) || (OMS_L_POD_FUEL_TANK_ULLAGE_PRESS < OMS_ULLAGE_PRESS_LOWER_LMT)) && (ReadCOMPOOL_IS( SCP_LOMS_TO_AFT_RCS_PRESS_ENA ) == 1))
				{
					OMS_L_POD_HE_ISLN_VLV_A_OP = 1;
					OMS_L_POD_HE_ISLN_VLV_B_OP = 1;
					OMS_L_POD_VAPOR_ISLN_VLV_1_OP = 1;
					OMS_L_POD_VAPOR_ISLN_VLV_2_OP = 1;
					REPRESS_ACTIVE_FLAG = 1;

					timer_stepa1_1 = 0.0;
					timerena_stepa1_1 = true;
				}
				else
				{
					if (((OMS_R_POD_OXDZR_TANK_ULLAGE_PRESS < OMS_ULLAGE_PRESS_LOWER_LMT) || (OMS_R_POD_FUEL_TANK_ULLAGE_PRESS < OMS_ULLAGE_PRESS_LOWER_LMT)) && (ReadCOMPOOL_IS( SCP_ROMS_TO_AFT_RCS_PRESS_ENA ) == 1))
					{
						OMS_R_POD_HE_ISLN_VLV_A_OP = 1;
						OMS_R_POD_HE_ISLN_VLV_B_OP = 1;
						OMS_R_POD_VAPOR_ISLN_VLV_1_OP = 1;
						OMS_R_POD_VAPOR_ISLN_VLV_2_OP = 1;
						REPRESS_ACTIVE_FLAG = 1;

						timer_stepa1_1 = 0.0;
						timerena_stepa1_1 = true;
					}
				}
			}
		}
		else
		{
			if (timer_stepa1_1 >= PRESS_TIME_DELAY)
			{
				timerena_stepa1_1 = false;

				if (firstpass_stepa1_2)
				{
					OMS_L_POD_HE_ISLN_VLV_A_OP = 0;
					OMS_L_POD_HE_ISLN_VLV_B_OP = 0;
					OMS_L_POD_VAPOR_ISLN_VLV_1_OP = 0;
					OMS_L_POD_VAPOR_ISLN_VLV_2_OP = 0;
					OMS_R_POD_HE_ISLN_VLV_A_OP = 0;
					OMS_R_POD_HE_ISLN_VLV_B_OP = 0;
					OMS_R_POD_VAPOR_ISLN_VLV_1_OP = 0;
					OMS_R_POD_VAPOR_ISLN_VLV_2_OP = 0;

					timer_stepa1_2 = 0.0;
					timerena_stepa1_2 = true;
				}

				if (timer_stepa1_2 >= 1.5)
				{
					timerena_stepa1_2 = false;
					goto stepA2;
				}
			}
		}

		return;


	stepA2:
		if ((FA_1_INPUT_PROM_SEG_3_10_STATUS == 0) && (FA_2_INPUT_PROM_SEG_3_10_STATUS == 0) && (FA_3_INPUT_PROM_SEG_3_10_STATUS == 0) && (FA_4_INPUT_PROM_SEG_3_10_STATUS == 0))
		{
			if ((OMS_L_POD_HE_ISLN_VLV_A_POSN_OP == 1) || (OMS_L_POD_HE_ISLN_VLV_B_POSN_OP == 1) || (OMS_L_POD_VAPOR_ISLN_VLV_1_POSN_OP == 1) || (OMS_L_POD_VAPOR_ISLN_VLV_2_POSN_OP == 1))
			{
				WriteCOMPOOL_IS( SCP_LT_OMS_HEVAPOR_ISO_VLV_MISCOM, 1 );
			}

			if ((OMS_R_POD_HE_ISLN_VLV_A_POSN_OP == 1) || (OMS_R_POD_HE_ISLN_VLV_B_POSN_OP == 1) || (OMS_R_POD_VAPOR_ISLN_VLV_1_POSN_OP == 1) || (OMS_R_POD_VAPOR_ISLN_VLV_2_POSN_OP == 1))
			{
				WriteCOMPOOL_IS( SCP_RT_OMS_HEVAPOR_ISO_VLV_MISCOM, 1 );
			}

			if ((OMS_L_POD_HE_ISLN_VLV_A_POSN_OP == 0) && (OMS_L_POD_HE_ISLN_VLV_B_POSN_OP == 0) && (OMS_L_POD_VAPOR_ISLN_VLV_1_POSN_OP == 0) && (OMS_L_POD_VAPOR_ISLN_VLV_2_POSN_OP == 0) &&
				(OMS_R_POD_HE_ISLN_VLV_A_POSN_OP == 0) && (OMS_R_POD_HE_ISLN_VLV_B_POSN_OP == 0) && (OMS_R_POD_VAPOR_ISLN_VLV_1_POSN_OP == 0) && (OMS_R_POD_VAPOR_ISLN_VLV_2_POSN_OP == 0))
			{
				REPRESS_ACTIVE_FLAG = 0;
			}
		}
		return;
	}

	void ORB_OMS_RCS_CONN::SubsequenceB( void )
	{
		OMS_L_POD_XFD_VLVS_A_CMD_1_CL = 0;
		OMS_L_POD_OXDZR_XFD_VLV_A_CMD_2_CL = 0;
		OMS_L_POD_FUEL_XFD_VLV_A_CMD_2_CL = 0;
		OMS_L_POD_XFD_VLVS_B_CMD_1_CL = 0;
		OMS_L_POD_OXDZR_XFD_VLV_B_CMD_2_CL = 0;
		OMS_L_POD_FUEL_XFD_VLV_B_CMD_2_CL = 0;

		OMS_R_POD_XFD_VLVS_A_CMD_1_CL = 0;
		OMS_R_POD_OXDZR_XFD_VLV_A_CMD_2_CL = 0;
		OMS_R_POD_FUEL_XFD_VLV_A_CMD_2_CL = 0;
		OMS_R_POD_XFD_VLVS_B_CMD_1_CL = 0;
		OMS_R_POD_OXDZR_XFD_VLV_B_CMD_2_CL = 0;
		OMS_R_POD_FUEL_XFD_VLV_B_CMD_2_CL = 0;

		RCS_L_AFT_XFD_VLV_12_GPC_CL_A = 0;
		RCS_L_AFT_OX_XFD_VLV_12_GPC_CL_B = 0;
		RCS_L_AFT_FU_XFD_VLV_12_GPC_CL_B = 0;
		RCS_L_AFT_XFD_VLV_345_GPC_CL_A = 0;
		RCS_L_AFT_OX_XFD_V_345_GPC_CL_B = 0;
		RCS_L_AFT_FU_XFD_V_345_GPC_CL_B = 0;

		RCS_R_AFT_XFD_VLV_12_GPC_CL_A = 0;
		RCS_R_AFT_OX_XFD_V_12_GPC_CL_B = 0;
		RCS_R_AFT_FU_XFD_V_12_GPC_CL_B = 0;
		RCS_R_AFT_XFD_VLV_345_GPC_CL_A = 0;
		RCS_R_AFT_OX_XFD_V_345_GPC_CL_B = 0;
		RCS_R_AFT_FU_XFD_V_345_GPC_CL_B = 0;

		RCS_L_AFT_TK_ISLN_V_12_GPC_CL_A = 0;
		RCS_L_AFT_OX_TK_ISLN_V12_GPC_CL_B = 0;
		RCS_L_AFT_FU_TK_ISLN_V12_GPC_CL_B = 0;
		RCS_L_AFT_OX_TK_ISLN_V345_A_GPC_CL = 0;
		RCS_L_AFT_FU_TK_ISLN_V345_A_GPC_CL = 0;
		RCS_L_AFT_OX_TK_ISLN_V345_B_GPC_CL = 0;
		RCS_L_AFT_FU_TK_ISLN_V345_B_GPC_CL = 0;

		RCS_R_AFT_TK_ISLN_V_12_GPC_CL_A = 0;
		RCS_R_AFT_OX_TK_ISLN_V_12_GPC_CL_B = 0;
		RCS_R_AFT_FU_TK_ISLN_V_12_GPC_CL_B = 0;
		RCS_R_AFT_OX_TK_ISLN_V345_A_GPC_CL = 0;
		RCS_R_AFT_FU_TK_ISLN_V345_A_GPC_CL = 0;
		RCS_R_AFT_OX_TK_ISLN_V345_B_GPC_CL = 0;
		RCS_R_AFT_FU_TK_ISLN_V345_B_GPC_CL = 0;

		OMS_L_POD_XFD_VLVS_A_CMD_1_OP = 0;
		OMS_L_POD_OXDZR_XFD_VLV_A_CMD_2_OP = 0;
		OMS_L_POD_FUEL_XFD_VLV_A_CMD_2_OP = 0;
		OMS_L_POD_XFD_VLVS_B_CMD_1_OP = 0;
		OMS_L_POD_OXDZR_XFD_VLV_B_CMD_2_OP = 0;
		OMS_L_POD_FUEL_XFD_VLV_B_CMD_2_OP = 0;

		OMS_R_POD_XFD_VLVS_A_CMD_1_OP = 0;
		OMS_R_POD_OXDZR_XFD_VLV_A_CMD_2_OP = 0;
		OMS_R_POD_FUEL_XFD_VLV_A_CMD_2_OP = 0;
		OMS_R_POD_XFD_VLVS_B_CMD_1_OP = 0;
		OMS_R_POD_OXDZR_XFD_VLV_B_CMD_2_OP = 0;
		OMS_R_POD_FUEL_XFD_VLV_B_CMD_2_OP = 0;

		RCS_L_AFT_XFD_VLV_12_GPC_OP_A = 0;
		RCS_L_AFT_OX_XFD_VLV_12_GPC_OP_B = 0;
		RCS_L_AFT_FU_XFD_VLV_12_GPC_OP_B = 0;
		RCS_L_AFT_XFD_VLV_345_GPC_OP_A = 0;
		RCS_L_AFT_OX_XFD_V_345_GPC_OP_B = 0;
		RCS_L_AFT_FU_XFD_V_345_GPC_OP_B = 0;

		RCS_R_AFT_XFD_VLV_12_GPC_OP_A = 0;
		RCS_R_AFT_OX_XFD_V_12_GPC_OP_B = 0;
		RCS_R_AFT_FU_XFD_V_12_GPC_OP_B = 0;
		RCS_R_AFT_XFD_VLV_345_GPC_OP_A = 0;
		RCS_R_AFT_OX_XFD_V_345_GPC_OP_B = 0;
		RCS_R_AFT_FU_XFD_V_345_GPC_OP_B = 0;

		RCS_L_AFT_TK_ISLN_V_12_GPC_OP_A = 0;
		RCS_L_AFT_OX_TK_ISLN_V_12_GPC_OP_B = 0;
		RCS_L_AFT_FU_TK_ISLN_V_12_GPC_OP_B = 0;
		RCS_L_AFT_OX_TK_ISLN_V_345_A_GPC_OP = 0;
		RCS_L_AFT_FU_TK_ISLN_V_345_A_GPC_OP = 0;
		RCS_L_AFT_OX_TK_ISLN_V_345_B_GPC_OP = 0;
		RCS_L_AFT_FU_TK_ISLN_V_345_B_GPC_OP = 0;

		RCS_R_AFT_TK_ISLN_V_12_GPC_OP_A = 0;
		RCS_R_AFT_OX_TK_ISLN_V_12_GPC_OP_B = 0;
		RCS_R_AFT_FU_TK_ISLN_V_12_GPC_OP_B = 0;
		RCS_R_AFT_OX_TK_ISLN_V_345_A_GPC_OP = 0;
		RCS_R_AFT_FU_TK_ISLN_V_345_A_GPC_OP = 0;
		RCS_R_AFT_OX_TK_ISLN_V_345_B_GPC_OP = 0;
		RCS_R_AFT_FU_TK_ISLN_V_345_B_GPC_OP = 0;

		OMS_L_POD_TK_VLVS_A_CMD_1_OP = 0;
		OMS_L_POD_TK_VLVS_A_CMD_1_CL = 0;
		OMS_L_POD_OXDZR_ISLN_V_A_CMD_2_OP = 0;
		OMS_L_POD_OXDZR_ISLN_V_A_CMD_2_CL = 0;
		OMS_L_POD_TK_VLVS_B_CMD_1_OP = 0;
		OMS_L_POD_TK_VLVS_B_CMD_1_CL = 0;
		OMS_L_POD_OXDZR_ISLN_V_B_CMD_2_OP = 0;
		OMS_L_POD_OXDZR_ISLN_V_B_CMD_2_CL = 0;
		OMS_L_POD_FUEL_ISLN_VLV_A_CMD_2_OP = 0;
		OMS_L_POD_FUEL_ISLN_VLV_A_CMD_2_CL = 0;
		OMS_L_POD_FUEL_ISLN_VLV_B_CMD_2_OP = 0;
		OMS_L_POD_FUEL_ISLN_VLV_B_CMD_2_CL = 0;

		OMS_R_POD_TK_VLVS_A_CMD_1_OP = 0;
		OMS_R_POD_TK_VLVS_A_CMD_1_CL = 0;
		OMS_R_POD_OXDZR_ISLN_V_A_CMD_2_OP = 0;
		OMS_R_POD_OXDZR_ISLN_V_A_CMD_2_CL = 0;
		OMS_R_POD_TK_VLVS_B_CMD_1_OP = 0;
		OMS_R_POD_TK_VLVS_B_CMD_1_CL = 0;
		OMS_R_POD_OXDZR_ISLN_V_B_CMD_2_OP = 0;
		OMS_R_POD_OXDZR_ISLN_V_B_CMD_2_CL = 0;
		OMS_R_POD_FUEL_ISLN_VLV_A_CMD_2_OP = 0;
		OMS_R_POD_FUEL_ISLN_VLV_A_CMD_2_CL = 0;
		OMS_R_POD_FUEL_ISLN_VLV_B_CMD_2_OP = 0;
		OMS_R_POD_FUEL_ISLN_VLV_B_CMD_2_CL = 0;

		PRE_SEQ_CMD_TERM_FLAG = 0;
		return;
	}

	bool ORB_OMS_RCS_CONN::OnParseLine( const char* keyword, const char* value )
	{
		return false;
	}

	void ORB_OMS_RCS_CONN::OnSaveState( FILEHANDLE scn ) const
	{
		return;
	}

	bool ORB_OMS_RCS_CONN::OnMajorModeChange( unsigned int newMajorMode )
	{
		switch (newMajorMode)
		{
			case 201:
			case 202:
			case 801:
				return true;
		}
		return false;
	}
}
