#include "RM_RCS_Display_Processing.h"


namespace dps
{
	RM_RCS_Display_Processing::RM_RCS_Display_Processing( SimpleGPCSystem* _gpc ):SimpleGPCSoftware( _gpc, "RM/RCS Display Processing" )
	{
		WriteCOMPOOL_IS( SCP_RCS_FWD_RCS_MODULE_DSPL_REQ, 1 );
		WriteCOMPOOL_IS( SCP_RCS_LEFT_RCS_MODULE_DSPL_REQ, 0 );
		WriteCOMPOOL_IS( SCP_RCS_RIGHT_RCS_MODULE_DSPL_REQ, 0 );
		WriteCOMPOOL_IS( SCP_SELECTED_RCS_JET_FAIL_LIMIT_CMD, 0xFFFF );// HACK using 0xFFFF for no input
		return;
	}

	RM_RCS_Display_Processing::~RM_RCS_Display_Processing()
	{
	}

	void RM_RCS_Display_Processing::OnPreStep( double simt, double simdt, double mjd )
	{
		if (0) return;// TODO only run if display up

		constexpr unsigned short JET_PRIORITY[38] = {
			1, 2, 3,
			1, 2,
			1, 2,
			1, 2, 3,
			1, 2,
			1, 2,
			1, 2,
			1, 2,
			1, 2, 3, 4,
			1, 2, 3, 4,
			1, 2, 3,
			1, 2, 3,
			1, 2, 3,
			1, 2, 3
		};// priority

		unsigned short PTY_fwd[16];
		unsigned short PTY_aft[28];

		for (int i = 0; i < 14; i++)
		{
			unsigned short pri = ReadCOMPOOL_AIS( SCP_JET_MAP_ELEMENT, i + 1, 38 );
			PTY_fwd[pri - 1] = JET_PRIORITY[i];
		}

		for (int i = 14; i < 38; i++)
		{
			unsigned short pri = ReadCOMPOOL_AIS( SCP_JET_MAP_ELEMENT, i + 1, 38 );
			PTY_aft[pri - 1] = JET_PRIORITY[i];
		}


		// copy data
		if (ReadCOMPOOL_IS( SCP_RCS_FWD_RCS_MODULE_DSPL_REQ ) == 1)
		{
			WriteCOMPOOL_IS( SCP_SELECTED_PRI_RCS_JET_FAIL_LIM_FLAG, ReadCOMPOOL_IS( SCP_RCS_FWD_JET_FAIL_LT ) );

			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 1, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 2, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 2, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 10, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 3, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 6, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 4, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 13, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 5, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 3, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 6, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 11, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 7, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 7, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 8, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 4, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 9, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 12, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 10, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 8, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 11, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 14, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 12, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 1, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 13, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 9, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 14, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 5, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 15, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 15, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 16, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 16, 44 ), 16 );

			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 1, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 2, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 2, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 14, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 3, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 6, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 4, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 13, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 5, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 3, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 6, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 15, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 7, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 7, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 8, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 4, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 9, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 16, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 10, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 8, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 11, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 10, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 12, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 1, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 13, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 9, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 14, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 5, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 15, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 11, 16 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 16, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_FWD, 12, 16 ), 16 );

			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 1, PTY_fwd[1], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 2, PTY_fwd[13], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 3, PTY_fwd[5], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 4, PTY_fwd[8], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 5, PTY_fwd[2], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 6, PTY_fwd[14], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 7, PTY_fwd[6], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 8, PTY_fwd[3], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 9, PTY_fwd[15], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 10, PTY_fwd[7], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 11, PTY_fwd[9], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 12, PTY_fwd[0], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 13, PTY_fwd[12], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 14, PTY_fwd[4], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 15, 1, 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 16, 1, 16 );

			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 1, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 1, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 2, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 2, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 3, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 3, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 4, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 4, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 5, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 5, 15 ), 5 );
		}
		else if (ReadCOMPOOL_IS( SCP_RCS_LEFT_RCS_MODULE_DSPL_REQ ) == 1)
		{
			WriteCOMPOOL_IS( SCP_SELECTED_PRI_RCS_JET_FAIL_LIM_FLAG, ReadCOMPOOL_IS( SCP_RCS_L_JET_FAIL_LT ) );

			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 1, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 26, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 2, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 20, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 3, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 24, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 4, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 18, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 5, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 27, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 6, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 21, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 7, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 19, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 8, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 9, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 28, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 10, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 22, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 11, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 25, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 12, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 23, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 13, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 17, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 14, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 15, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 30, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 16, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 29, 44 ), 16 );

			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 1, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 23, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 2, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 17, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 3, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 10, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 4, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 2, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 5, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 24, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 6, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 18, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 7, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 3, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 8, 1, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 9, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 25, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 10, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 19, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 11, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 11, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 12, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 9, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 13, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 1, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 14, 1, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 15, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 8, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 16, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 7, 28 ), 16 );

			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 1, PTY_aft[22], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 2, PTY_aft[16], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 3, PTY_aft[9], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 4, PTY_aft[1], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 5, PTY_aft[23], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 6, PTY_aft[17], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 7, PTY_aft[2], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 8, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 9, PTY_aft[24], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 10, PTY_aft[18], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 11, PTY_aft[10], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 12, PTY_aft[8], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 13, PTY_aft[0], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 14, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 15, 1, 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 16, 1, 16 );

			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 1, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 6, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 2, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 7, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 3, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 8, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 4, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 9, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 5, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 10, 15 ), 5 );
		}
		else if (ReadCOMPOOL_IS( SCP_RCS_RIGHT_RCS_MODULE_DSPL_REQ ) == 1)
		{
			WriteCOMPOOL_IS( SCP_SELECTED_PRI_RCS_JET_FAIL_LIM_FLAG, ReadCOMPOOL_IS( SCP_RCS_R_JET_FAIL_LT ) );

			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 1, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 40, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 2, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 34, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 3, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 38, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 4, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 32, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 5, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 41, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 6, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 35, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 7, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 33, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 8, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 9, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 42, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 10, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 36, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 11, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 39, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 12, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 31, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 13, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 37, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 14, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 15, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 44, 44 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_RM_INH_FLAG, 16, ReadCOMPOOL_AIS( SCP_JET_DES_INHIBIT, 43, 44 ), 16 );

			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 1, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 26, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 2, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 20, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 3, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 13, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 4, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 5, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 5, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 27, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 6, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 21, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 7, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 6, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 8, 1, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 9, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 28, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 10, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 22, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 11, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 14, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 12, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 4, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 13, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 12, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 14, 1, 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 15, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 15, 28 ), 16 );
			WriteCOMPOOL_AIS( SCP_SEL_JET_AVAIL_FLAG, 16, ReadCOMPOOL_AIS( SCP_AVAILABLE_JET_AFT, 16, 28 ), 16 );

			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 1, PTY_aft[25], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 2, PTY_aft[19], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 3, PTY_aft[12], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 4, PTY_aft[4], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 5, PTY_aft[26], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 6, PTY_aft[20], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 7, PTY_aft[5], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 8, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 9, PTY_aft[27], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 10, PTY_aft[21], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 11, PTY_aft[13], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 12, PTY_aft[11], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 13, PTY_aft[3], 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 14, 0, 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 15, 1, 16 );
			WriteCOMPOOL_AIS( SCP_SELECTED_JET_PRIORITY, 16, 1, 16 );

			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 1, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 11, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 2, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 12, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 3, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 13, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 4, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 14, 15 ), 5 );
			WriteCOMPOOL_AIS( SCP_SELECTED_RCS_MANF_OP_CL_STATUS, 5, ReadCOMPOOL_AIS( SCP_RCS_MANIFOLD_OP_CL_STATUS, 15, 15 ), 5 );
		}


		// TODO copy control
		unsigned short SELECTED_RCS_JET_FAIL_LIMIT_CMD = ReadCOMPOOL_IS( SCP_SELECTED_RCS_JET_FAIL_LIMIT_CMD );
		if (SELECTED_RCS_JET_FAIL_LIMIT_CMD != 0xFFFF)
		{
			if (ReadCOMPOOL_IS( SCP_RCS_FWD_RCS_MODULE_DSPL_REQ ) == 1)
			{
				WriteCOMPOOL_IS( SCP_RCS_FWD_JET_FAIL_LT, SELECTED_RCS_JET_FAIL_LIMIT_CMD );
			}
			else if (ReadCOMPOOL_IS( SCP_RCS_LEFT_RCS_MODULE_DSPL_REQ ) == 1)
			{
				WriteCOMPOOL_IS( SCP_RCS_L_JET_FAIL_LT, SELECTED_RCS_JET_FAIL_LIMIT_CMD );
			}
			else if (ReadCOMPOOL_IS( SCP_RCS_RIGHT_RCS_MODULE_DSPL_REQ ) == 1)
			{
				WriteCOMPOOL_IS( SCP_RCS_R_JET_FAIL_LT, SELECTED_RCS_JET_FAIL_LIMIT_CMD );
			}

			WriteCOMPOOL_IS( SCP_SELECTED_RCS_JET_FAIL_LIMIT_CMD, 0xFFFF );// HACK using 0xFFFF for no input
		}

		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 1, 15, SCP_JET_DES_INHIBIT, 2, 26, 40 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 2, 15, SCP_JET_DES_INHIBIT, 10, 20, 34 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 3, 15, SCP_JET_DES_INHIBIT, 6, 24, 38 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 4, 15, SCP_JET_DES_INHIBIT, 13, 18, 32 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 5, 15, SCP_JET_DES_INHIBIT, 3, 27, 41 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 6, 15, SCP_JET_DES_INHIBIT, 11, 21, 35 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 7, 15, SCP_JET_DES_INHIBIT, 7, 19, 33 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 8, 15, SCP_JET_DES_INHIBIT, 4, 0, 0 );// HACK using idx 0, will produce no effect
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 9, 15, SCP_JET_DES_INHIBIT, 12, 28, 42 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 10, 15, SCP_JET_DES_INHIBIT, 8, 22, 36 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 11, 15, SCP_JET_DES_INHIBIT, 14, 25, 39 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 12, 15, SCP_JET_DES_INHIBIT, 1, 23, 31 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 13, 15, SCP_JET_DES_INHIBIT, 9, 17, 37 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 14, 15, SCP_JET_DES_INHIBIT, 5, 0, 0 );// HACK using idx 0, will produce no effect
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 15, 15, SCP_JET_DES_INHIBIT, 15, 30, 44 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_RM_AUTO_INH_FLAG, 16, 15, SCP_JET_DES_INHIBIT, 16, 29, 43 );

		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 1, 44, SCP_JET_DESELECT, 2, 26, 40 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 2, 44, SCP_JET_DESELECT, 10, 20, 34 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 3, 44, SCP_JET_DESELECT, 6, 24, 38 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 4, 44, SCP_JET_DESELECT, 13, 18, 32 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 5, 44, SCP_JET_DESELECT, 3, 27, 41 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 6, 44, SCP_JET_DESELECT, 11, 21, 35 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 7, 44, SCP_JET_DESELECT, 7, 19, 33 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 8, 44, SCP_JET_DESELECT, 4, 0, 0 );// HACK using idx 0, will produce no effect
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 9, 44, SCP_JET_DESELECT, 12, 28, 42 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 10, 44, SCP_JET_DESELECT, 8, 22, 36 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 11, 44, SCP_JET_DESELECT, 14, 25, 39 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 12, 44, SCP_JET_DESELECT, 1, 23, 31 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 13, 44, SCP_JET_DESELECT, 9, 17, 37 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 14, 44, SCP_JET_DESELECT, 5, 0, 0 );// HACK using idx 0, will produce no effect
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 15, 44, SCP_JET_DESELECT, 15, 30, 44 );
		CopyControlFlags( 16, SCP_RCS_SEL_JET_SEL_DES_FLAG, 16, 44, SCP_JET_DESELECT, 16, 29, 43 );

		CopyControlFlags( 5, SCP_SELECTED_RCS_MANF_OP_CL_STAT_OVRD, 1, 15, SCP_RCS_MANF_OP_CL_STAT_OVRD, 1, 6, 11 );
		CopyControlFlags( 5, SCP_SELECTED_RCS_MANF_OP_CL_STAT_OVRD, 2, 15, SCP_RCS_MANF_OP_CL_STAT_OVRD, 2, 7, 12 );
		CopyControlFlags( 5, SCP_SELECTED_RCS_MANF_OP_CL_STAT_OVRD, 3, 15, SCP_RCS_MANF_OP_CL_STAT_OVRD, 3, 8, 13 );
		CopyControlFlags( 5, SCP_SELECTED_RCS_MANF_OP_CL_STAT_OVRD, 4, 15, SCP_RCS_MANF_OP_CL_STAT_OVRD, 4, 9, 14 );
		CopyControlFlags( 5, SCP_SELECTED_RCS_MANF_OP_CL_STAT_OVRD, 5, 15, SCP_RCS_MANF_OP_CL_STAT_OVRD, 5, 10, 15 );


		// RCS Jet Manifold Status
		if (ReadCOMPOOL_IS( SCP_RCS_FWD_RCS_MODULE_DSPL_REQ ) == 1)
		{
			JetManfStatus( 2, 1 );// F1L
			JetManfStatus( 10, 2 );// F3L
			JetManfStatus( 6, 3 );// F2R
			JetManfStatus( 13, 4 );// F4R
			JetManfStatus( 3, 5 );// F1U
			JetManfStatus( 11, 6 );// F3U
			JetManfStatus( 7, 7 );// F2U
			JetManfStatus( 4, 8 );// F1D
			JetManfStatus( 12, 9 );// F3D
			JetManfStatus( 8, 10 );// F2D
			JetManfStatus( 14, 11 );// F4D
			JetManfStatus( 1, 12 );// F1F
			JetManfStatus( 9, 13 );// F3F
			JetManfStatus( 5, 14 );// F2F
			JetManfStatus( 15, 15 );// F5L
			JetManfStatus( 16, 16 );// F5R
		}
		else if (ReadCOMPOOL_IS( SCP_RCS_LEFT_RCS_MODULE_DSPL_REQ ) == 1)
		{
			JetManfStatus( 26, 1 );// L4L
			JetManfStatus( 20, 2 );// L2L
			JetManfStatus( 24, 3 );// L3L
			JetManfStatus( 18, 4 );// L1L
			JetManfStatus( 27, 5 );// L4U
			JetManfStatus( 21, 6 );// L2U
			JetManfStatus( 19, 7 );// L1U
			WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, 8, "   ", 16, 3 );
			JetManfStatus( 28, 9 );// L4D
			JetManfStatus( 22, 10 );// L2D
			JetManfStatus( 25, 11 );// L3D
			JetManfStatus( 23, 12 );// L3A
			JetManfStatus( 17, 13 );// L1A
			WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, 14, "   ", 16, 3 );
			JetManfStatus( 30, 15 );// L5L
			JetManfStatus( 29, 16 );// L5D
		}
		else if (ReadCOMPOOL_IS( SCP_RCS_RIGHT_RCS_MODULE_DSPL_REQ ) == 1)
		{
			JetManfStatus( 40, 1 );// R4R
			JetManfStatus( 34, 2 );// R2R
			JetManfStatus( 38, 3 );// R3R
			JetManfStatus( 32, 4 );// R1R
			JetManfStatus( 41, 5 );// R4U
			JetManfStatus( 35, 6 );// R2U
			JetManfStatus( 33, 7 );// R1U
			WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, 8, "   ", 16, 3 );
			JetManfStatus( 42, 9 );// R4D
			JetManfStatus( 36, 10 );// R2D
			JetManfStatus( 39, 11 );// R3D
			JetManfStatus( 31, 12 );// R1A
			JetManfStatus( 37, 13 );// R3A
			WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, 14, "   ", 16, 3 );
			JetManfStatus( 44, 15 );// R5R
			JetManfStatus( 43, 16 );// R5D
		}

		// TODO RCS Temperature Conversion and Status

		// TODO RCS Helium Tank Pressure Conversion and Status

		// TODO RCS Propellant Conversion and Status

		// TODO RCS Manifold Pressure Conversion & Status
		
		// RCS Manifold OP/CL I/O Status
		if (ReadCOMPOOL_IS( SCP_RCS_FWD_RCS_MODULE_DSPL_REQ ) == 1)
		{
			for (int i = 1; i <= 5; i++) RCSManifOPCLIOStatus( SCP_RCS_MANF_RM_DILEMMA_FLAG, i, SCP_SELECTED_RCS_MANF_OP_CL_IO_STAT, i, 5 );
		}
		else if (ReadCOMPOOL_IS( SCP_RCS_LEFT_RCS_MODULE_DSPL_REQ ) == 1)
		{
			for (int i = 1; i <= 5; i++) RCSManifOPCLIOStatus( SCP_RCS_MANF_RM_DILEMMA_FLAG, i + 5, SCP_SELECTED_RCS_MANF_OP_CL_IO_STAT, i, 5 );
		}
		else if (ReadCOMPOOL_IS( SCP_RCS_RIGHT_RCS_MODULE_DSPL_REQ ) == 1)
		{
			for (int i = 1; i <= 5; i++) RCSManifOPCLIOStatus( SCP_RCS_MANF_RM_DILEMMA_FLAG, i + 10, SCP_SELECTED_RCS_MANF_OP_CL_IO_STAT, i, 5 );
		}

		// TODO OMS AFT Crossfeed (XFD) Pressure Conversion & Status
		return;
	}

	void RM_RCS_Display_Processing::JetManfStatus( const unsigned int jetid, const unsigned int outid )
	{
		if (ReadCOMPOOL_AIS( SCP_JET_FAILED_ON, jetid, 44 ) == 1) WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, outid, "ON ", 16, 3 );
		else if (ReadCOMPOOL_AIS( SCP_JET_LEAKING, jetid, 44 ) == 1) WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, outid, "LK ", 16, 3 );
		else if (ReadCOMPOOL_AIS( SCP_JET_FAILED_OFF, jetid, 44 ) == 1) WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, outid, "OFF", 16, 3 );
		else WriteCOMPOOL_AC( SCP_SELECTED_JET_ON_LK_OFF_FLAG, outid, "   ", 16, 3 );
		return;
	}

	void RM_RCS_Display_Processing::RCSManifOPCLIOStatus( const unsigned int dilemmaaddr, const unsigned int dilemmaidx, const unsigned int outaddr, const unsigned int outidx, const unsigned int outsz )
	{
		// TODO commfaults
		if (0 || 0) WriteCOMPOOL_AC( outaddr, outidx, "M", outsz, 1 );
		else if (ReadCOMPOOL_AIS( dilemmaaddr, dilemmaidx, 15 ) == 1) WriteCOMPOOL_AC( outaddr, outidx, "?", outsz, 1 );
		else WriteCOMPOOL_AC( outaddr, outidx, " ", outsz, 1 );
		return;
	}

	void RM_RCS_Display_Processing::CopyControlFlags( const unsigned int maxinidx, const unsigned int inaddr, const unsigned int inidx, const unsigned int maxoutidx, const unsigned int outaddr, const unsigned int outidxfwd, const unsigned int outidxleft, const unsigned int outidxright )
	{
		if (ReadCOMPOOL_AIS( inaddr, inidx, maxinidx ) == 1)
		{
			if (ReadCOMPOOL_IS( SCP_RCS_FWD_RCS_MODULE_DSPL_REQ ) == 1)
			{
				WriteCOMPOOL_AIS( outaddr, outidxfwd, ReadCOMPOOL_AIS( outaddr, outidxfwd, maxoutidx ) ? 0 : 1, maxoutidx );
			}
			else if (ReadCOMPOOL_IS( SCP_RCS_LEFT_RCS_MODULE_DSPL_REQ ) == 1)
			{
				WriteCOMPOOL_AIS( outaddr, outidxleft, ReadCOMPOOL_AIS( outaddr, outidxleft, maxoutidx ) ? 0 : 1, maxoutidx );
			}
			else if (ReadCOMPOOL_IS( SCP_RCS_RIGHT_RCS_MODULE_DSPL_REQ ) == 1)
			{
				WriteCOMPOOL_AIS( outaddr, outidxright, ReadCOMPOOL_AIS( outaddr, outidxright, maxoutidx ) ? 0 : 1, maxoutidx );
			}

			WriteCOMPOOL_AIS( inaddr, inidx, 0, maxinidx );
		}
		return;
	}

	bool RM_RCS_Display_Processing::OnMajorModeChange( unsigned int newMajorMode )
	{
		return true;
	}
};
