#ifndef _COMPOOL_H_
#define _COMPOOL_H_

// ----------------------------------------------------------------
// SSV COMPOOL definition
// ----------------------------------------------------------------
// SINGLE => 16b
// DOUBLE => 32b

// INFO: SCALAR should always be DOUBLE, and implemented in C with a 32b float

// current major mode
inline constexpr unsigned int SCP_MM = 0x00000;// INTEGER SINGLE
// new major mode
inline constexpr unsigned int SCP_NEW_MM = 0x00001;// INTEGER SINGLE

// MDM return word output
inline constexpr unsigned int SCP_MDM_RETURN = 0x00002;// INTEGER SINGLE

// bypass/commfault words
// word 0:
// 0-FF1	FF Input Prom Seq 1,2 (MFE)
// 1-FF2	FF Input Prom Seq 1,2 (MFE)
// 2-FF3	FF Input Prom Seq 1,2 (MFE)
// 3-FF4	FF Input Prom Seq 1,2 (MFE)
// 4-FF1	TACAN/RA (MFE)
// 5-FF2	TACAN/RA (MFE)
// 6-FF3	TACAN/RA (MFE)
// 7-
// 8-FF1	MSBLS (MFE)
// 9-FF2	MSBLS (MFE)
// 10-FF3	MSBLS (MFE)
// 11-
// 12-FF1	IMU (MFE)
// 13-FF2	IMU (MFE)
// 14-FF3	IMU (MFE)
// 15-
// 16-
// 17-
// 18-FF1	STU (MFE)
// 19-FF3	STU (MFE)
// 20-FF3	Rendezvous Radar (MFE)
// 21-
// 22-
// 23-
// 24-EIU1	EIU1/P1 (MFE)
// 25-EIU2	EIU2/P1 (MFE)
// 26-EIU3	EIU3/P1 (MFE)
// 27-
// 28-FA1	FA Input Prom Seq 1,2 (MFE)
// 29-FA2	FA Input Prom Seq 1,2 (MFE)
// 30-FA3	FA Input Prom Seq 1,2 (MFE)
// 31-FA4	FA Input Prom Seq 1,2 (MFE)
inline constexpr unsigned int SCP_COMMFAULT_WORD_0 = 0x00003;// INTEGER DOUBLE
// 0-FF1	MDM Return Word (HFE/HDA)
// 1-FF2	MDM Return Word (HFE/HDA)
// 2-FF3	MDM Return Word (HFE/HDA)
// 3-FF4	MDM Return Word (HFE/HDA)
// 4-FF1	FF Input Prom Seq 2,6 (HFE/HDA)
// 5-FF2	FF Input Prom Seq 2,6 (HFE/HDA)
// 6-FF3	FF Input Prom Seq 2,6 (HFE/HDA)
// 7-FF4	FF Input Prom Seq 2,6 (HFE/HDA)
// 8-FF1	ADTA (HFE/HDA)
// 9-FF2	ADTA (HFE/HDA)
// 10-FF3	ADTA (HFE/HDA)
// 11-FF4	ADTA (HFE/HDA)
// 12-FA1	MDM Return Word (HFE/HDA)
// 13-FA2	MDM Return Word (HFE/HDA)
// 14-FA3	MDM Return Word (HFE/HDA)
// 15-FA4	MDM Return Word (HFE/HDA)
// 16-FA1	FA Input Prom Seq 3,10 (HFE/HDA)
// 17-FA2	FA Input Prom Seq 3,10 (HFE/HDA)
// 18-FA3	FA Input Prom Seq 3,10 (HFE/HDA)
// 19-FA4	FA Input Prom Seq 3,10 (HFE/HDA)
// 20-EIU1	EIU1/P1 (HFE)
// 21-EIU1	EIU1/P4 (HFE)
// 22-EIU2	EIU2/P1 (HFE)
// 23-EIU2	EIU2/P4 (HFE)
// 24-EIU3	EIU3/P1 (HFE)
// 25-EIU3	EIU3/P4 (HFE)
// 26-
// 27-
// 28-
// 29-FA2	Hyd. Sys 3 Press. C (HFE/HDA)
// 30-FA3	OMS Lt. Eng. Press. (HFE/HDA)
// 31-FA4	OMS Rt. Eng. Press. (HFE/HDA)
inline constexpr unsigned int SCP_COMMFAULT_WORD_1 = 0x00005;// INTEGER DOUBLE
// 0-FF1	MTU1 (MTU)
// 1-FF2	MTU2 (MTU)
// 2-FF3	MTU3 (MTU)
// 3-
// 4-FF1	NSP1 Discretes (NSP)
// 5-FF3	NSP2 Discretes (NSP)
// 6-FF1	NSP1 Data (NSP)
// 7-FF3	NSP2 Data (NSP)
// 8-FA1	FA1 MDM (GNC OPS INIT)
// 9-FA2	FA2 MDM (GNC OPS INIT)
// 10-FA3	FA3 MDM (GNC OPS INIT)
// 11-FA4	FA4 MDM (GNC OPS INIT)
// 12-FF1	FF1 MDM (GNC OPS INIT)
// 13-FF2	FF2 MDM (GNC OPS INIT)
// 14-FF3	FF3 MDM (GNC OPS INIT)
// 15-FF4	FF4 MDM (GNC OPS INIT)
// 16-LL1	SRB Prom (SRB)
// 17-LL2	SRB Prom (SRB)
// 18-LR1	SRB Prom (SRB)
// 19-LR2	SRB Prom (SRB)
// 20-FF1	Return Word (IMU)
// 21-FF2	Return Word (IMU)
// 22-FF3	Return Word (IMU)
// 23-
// 24-FF1	IMU Discretes (IMU)
// 25-FF2	IMU Discretes (IMU)
// 26-FF3	IMU Discretes (IMU)
// 27-
// 28-FF1	IMU Data (IMU)
// 29-FF2	IMU Data (IMU)
// 30-FF3	IMU Data (IMU)
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_2 = 0x00007;// INTEGER DOUBLE
// 0-
// 1-
// 2-
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-
// 17-
// 18-
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-PF1	PDI (PDI PF1)
// 29-MCIU	MCIU (MCIU)
// 30-PF1	PSP1 (PSP PF1)
// 31-PF2	PSP2 (PSP PF2)
inline constexpr unsigned int SCP_COMMFAULT_WORD_3 = 0x00009;// INTEGER DOUBLE
// 0-PF1	MDM Return Word (PF Low Rate)
// 1-PF1	KU-Band Radar (PF Low Rate)
// 2-
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-PF2	MDM Return Word (PF Low Rate)
// 17-PF2	Fuel Cell Purge (PF Low Rate)
// 18-
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-
// 29-
// 30-
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_4 = 0x0000b;// INTEGER DOUBLE
// 0-
// 1-
// 2-
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-
// 17-
// 18-
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-
// 29-
// 30-
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_5 = 0x0000d;// INTEGER DOUBLE
// 0-
// 1-
// 2-
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-
// 17-
// 18-
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-
// 29-
// 30-
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_6 = 0x0000f;// INTEGER DOUBLE
// 0-
// 1-
// 2-
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-
// 17-
// 18-
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-
// 29-
// 30-
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_7 = 0x00011;// INTEGER DOUBLE
// 0-
// 1-
// 2-
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-
// 17-
// 18-
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-
// 29-
// 30-
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_8 = 0x00013;// INTEGER DOUBLE
// 0-
// 1-
// 2-
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-
// 17-
// 18-
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-
// 29-
// 30-
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_9 = 0x00015;// INTEGER DOUBLE
// 0-PF1	PBD (PF High Rate)
// 1-PF1	PBD (PF High Rate)
// 2-PF1	PBD (PF High Rate)
// 3-
// 4-
// 5-
// 6-
// 7-
// 8-
// 9-
// 10-
// 11-
// 12-
// 13-
// 14-
// 15-
// 16-PF2	PBD (PF High Rate)
// 17-PF2	PBD (PF High Rate)
// 18-PF2	PBD (PF High Rate)
// 19-
// 20-
// 21-
// 22-
// 23-
// 24-
// 25-
// 26-
// 27-
// 28-
// 29-
// 30-
// 31-
inline constexpr unsigned int SCP_COMMFAULT_WORD_10 = 0x00017;// INTEGER DOUBLE
// Commfault counters
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_0 = 0x00019;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_1 = 0x0001b;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_2 = 0x0001d;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_3 = 0x0001f;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_4 = 0x00021;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_5 = 0x00023;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_6 = 0x00025;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_7 = 0x00027;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_8 = 0x00029;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_9 = 0x0002b;// INTEGER DOUBLE
inline constexpr unsigned int SCP_COMMFAULT_WORD_COUNTER_10 = 0x0002d;// INTEGER DOUBLE

// Fault input buffer
inline constexpr unsigned int SCP_FAULT_IN_IDX = 0x0002f;// INTEGER SINGLE
inline constexpr unsigned int SCP_FAULT_IN_CWCLASS = 0x00030;// ARRAY(5) INTEGER SINGLE
inline constexpr unsigned int SCP_FAULT_IN_MSG = 0x00035;// ARRAY(5) CHARACTER(19)
// Fault display buffer
inline constexpr unsigned int SCP_FAULT_DISPBUF = 0x00094;// ARRAY(15) CHARACTER(43)
inline constexpr unsigned int SCP_FAULT_DISPBUF_CNT = 0x00319;// INTEGER SINGLE
inline constexpr unsigned int SCP_FAULT_DISPBUF_CLEAR = 0x0031a;// INTEGER SINGLE
// Fault message buffer indicator
inline constexpr unsigned int SCP_FAULT_MSG_BUF_IND = 0x0031b;// INTEGER SINGLE
// Fault message line buffer
inline constexpr unsigned int SCP_FAULT_MSG_LINE = 0x0031c;// CHARACTER(43)
// Fault message line state (0 = empty, 1 = flashing, 2 = static)
inline constexpr unsigned int SCP_FAULT_MSG_LINE_STATE = 0x00347;// INTEGER SINGLE
// Illegal Entry indication for each CRT
inline constexpr unsigned int SCP_ILLEGAL_ENTRY_FAULT = 0x00348;// INTEGER SINGLE

inline constexpr unsigned int SCP_ACK_KEY = 0x00349;// INTEGER SINGLE
inline constexpr unsigned int SCP_MSGRESET_KEY = 0x0034a;// INTEGER SINGLE

// duration of SM tone [s]
inline constexpr unsigned int SCP_SM_TONE_DURATION = 0x0034b;// INTEGER SINGLE

// outputs to EIUs
inline constexpr unsigned int SCP_EIU_1_CMD = 0x0034c;// INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_2_CMD = 0x0034d;// INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_3_CMD = 0x0034e;// INTEGER SINGLE

// inputs from EIUs
inline constexpr unsigned int SCP_EIU_1_PRIDATA = 0x0034f;// ARRAY(32) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_2_PRIDATA = 0x0036f;// ARRAY(32) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_3_PRIDATA = 0x0038f;// ARRAY(32) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_1_SECDATA = 0x003af;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_2_SECDATA = 0x003b5;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_3_SECDATA = 0x003bb;// ARRAY(6) INTEGER SINGLE

// output to DDU-1
inline constexpr unsigned int SCP_DDU1_ADI = 0x003c1;// ARRAY(14) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU1_HSI = 0x003cf;// ARRAY(10) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU1_AVVI = 0x003d9;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU1_AMI = 0x003df;// ARRAY(6) INTEGER SINGLE

// output to DDU-2
inline constexpr unsigned int SCP_DDU2_ADI = 0x003e5;// ARRAY(14) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU2_HSI = 0x003f3;// ARRAY(10) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU2_AVVI = 0x003fd;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU2_AMI = 0x00403;// ARRAY(6) INTEGER SINGLE

// output to HUD-1
inline constexpr unsigned int SCP_HUD1_MSG1 = 0x00409;// ARRAY(31) INTEGER SINGLE
inline constexpr unsigned int SCP_HUD1_MSG2 = 0x00428;// ARRAY(12) INTEGER SINGLE

// output to HUD-2
inline constexpr unsigned int SCP_HUD2_MSG1 = 0x00434;// ARRAY(31) INTEGER SINGLE
inline constexpr unsigned int SCP_HUD2_MSG2 = 0x00453;// ARRAY(12) INTEGER SINGLE

// MDM FF1 input
// Radar Altimeter 1 data
inline constexpr unsigned int SCP_FF1_IOM0_CH4_DATA = 0x0045f;// INTEGER SINGLE
// 3-LH BODY FLAP UP A
// 4-LH BODY FLAP DOWN A
// 5-MPS ME-1 SHUTDOWN CMD A
// 7-F_FU_MANF_ISOV_1_OP
// 8-F_FU_MANF_ISOV_1_CL
// 9-F_FU_TK_ISOV_345_OP
// 10-F_FU_TK_ISOV_345_CL
// 11-F_HE_FU_PRESS_V_A_OP
// 12-F_HE_FU_PRESS_V_A_CL
inline constexpr unsigned int SCP_FF1_IOM4_CH0_DATA = 0x00460;// INTEGER SINGLE
// 10-FCS LH PITCH AUTO MODE A
// 11-FCS LH PITCH CSS MODE A
// 13-FCS LH R-Y AUTO MODE A
// 14-FCS LH R-Y CSS MODE A
// 15-LH BODY FLAP AUTO/MANUAL A
inline constexpr unsigned int SCP_FF1_IOM4_CH1_DATA = 0x00461;// INTEGER SINGLE
// 0-LH SPD BK/THROT AUTO/MAN A
// 3-ENTRY ROLL MODE NO Y JET A
// 4-R PB/W VENTS 4 & 7 CLOSED 2
// 5-R PB/W VENTS 4 & 7 OPEN 2
// 6-R FWD VENTS 1 & 2 CLOSED 1
// 7-R FWD VENTS 1 & 2 OPEN 1
// 8-R FWD VENTS 1 & 2 PURGE IND 1
// 9-L PB VENT 6 CLOSED 1
// 10-L PB VENT 6 OPEN 1
// 11-L PB VENT 6 PURGE 1 IND 1
// 12-R PB VENT 3 CLOSED 1
// 13-R PB VENT 3 OPEN 1
// 14-R PB VENT 5 CLOSED 1
// 15-R PB VENT 5 OPEN 1
inline constexpr unsigned int SCP_FF1_IOM4_CH2_DATA = 0x00462;// INTEGER SINGLE
// 0-RJDF 1 JET F1F CHAMBER PRESS IND
// 1-RJDF 1 JET F1L CHAMBER PRESS IND
// 2-RJDF 1 JET F1U CHAMBER PRESS IND
// 3-RJDF 1 JET F1D CHAMBER PRESS IND
// 7-FWD THC POS X OUTPUT - A
// 8-FWD THC NEG X OUTPUT - A
// 9-FWD THC POS Y OUTPUT - A
// 10-FWD THC NEG Y OUTPUT - A
// 11-FWD THC POS Z OUTPUT - A
// 12-FWD THC NEG Z OUTPUT - A
// 13-LH SBTC TAKEOVER - A
inline constexpr unsigned int SCP_FF1_IOM6_CH0_DATA = 0x00463;// INTEGER SINGLE
// 1-LH RHC PLUS PITCH TRIM A
// 2-LH RHC MINUS PITCH TRIM A
// 3-LH RHC PLUS ROLL TRIM A
// 4-LH RHC MINUS ROLL TRIM A
// 5-SRB SEPARATION AUTO A CMD
// 6-SRB SEPN MANUAL/AUTO ENABLE A CMD
// 7-SRB SEPARATION INITIATE A CMD
inline constexpr unsigned int SCP_FF1_IOM6_CH1_DATA = 0x00464;// INTEGER SINGLE
// 0-RJDF 1 JET F1F DRIVER
// 1-RJDF 1 JET F1L DRIVER
// 2-RJDF 1 JET F1U DRIVER
// 3-RJDF 1 JET F1D DRIVER
// 4-FWD DAP SELECT A - A
// 5-FWD DAP SELECT B - A
// 6-AFT DAP SELECT A - C
// 7-AFT DAP SELECT B - C
// 8-FWD DAP AUTO A
// 9-FWD DAP MAN A
// 10-AFT DAP AUTO C
// 11-AFT DAP MAN C
inline constexpr unsigned int SCP_FF1_IOM9_CH0_DATA = 0x00465;// INTEGER SINGLE
// 1-SENSE SW -Z CON A
// 2-SENSE SW -X CON A
// 3-ENTRY ROLL MODE L GAIN - A
// 4-FWD ROTATION ROLL DISC RATE A
// 5-FWD ROTATION ROLL ACCEL A
// 6-FWD ROTATION ROLL PULSE A
// 7-FWD ROTATION PITCH DISC RATE A
// 8-FWD ROTATION PITCH ACCEL A
// 9-FWD ROTATION PITCH PULSE A
// 10-FWD ROTATION YAW DISC RATE A
// 11-FWD ROTATION YAW ACCEL A
// 12-FWD ROTATION YAW PULSE A
// 13-FWD RCS JETS NORM A
// 14-FWD RCS JETS VERNIER A
// 15-FWD TRANSLATION X NORM A
inline constexpr unsigned int SCP_FF1_IOM9_CH1_DATA = 0x00466;// INTEGER SINGLE
// 0-FWD TRANSLATION X PULSE A
// 1-FWD TRANSLATION X LVLH A
// 2-FWD TRANSLATION Y NORM A
// 3-FWD TRANSLATION Y PULSE A
// 4-FWD TRANSLATION Y LOW Z A
// 5-FWD TRANSLATION Z NORM A
// 6-FWD TRANSLATION Z PULSE A
// 7-FWD TRANSLATION Z HIGH A
// 8-MPS PRPLT DUMP SEQUENCE START A
// 9-MPS PRPLT DUMP SEQUENCE STOP A
inline constexpr unsigned int SCP_FF1_IOM9_CH2_DATA = 0x00467;// INTEGER SINGLE
// 1-LH PLUS PITCH TRIM A
// 2-LH MINUS PITCH TRIM A
// 3-LH PLUS ROLL TRIM A
// 4-LH MINUS ROLL TRIM A
// 5-LH PLUS YAW TRIM A
// 6-LH MINUS YAW TRIM A
// 7-F_OX_MANF_ISOV_1_OP
// 8-F_OX_MANF_ISOV_1_CL
// 9-F_HE_OX_PRESS_V_A_OP
// 10-F_HE_OX_PRESS_V_A_CL
// 11-F_OX_TK_ISOV_345_OP
// 12-F_OX_TK_ISOV_345_CL
// 13-CDR RDR ALTM SEL 1
inline constexpr unsigned int SCP_FF1_IOM12_CH0_DATA = 0x00468;// INTEGER SINGLE
// 8-LH RHC TRIM INHIBIT A
inline constexpr unsigned int SCP_FF1_IOM12_CH1_DATA = 0x00469;// INTEGER SINGLE
// 8-L PB VENT 6 PURGE 2 IND 1
// 14-AFT RCS OPTIONS NORM C
// 15-AFT RCS OPTIONS VERNIER C
inline constexpr unsigned int SCP_FF1_IOM12_CH2_DATA = 0x0046a;// INTEGER SINGLE
// 7-AFT THC POS X OUTPUT - A
// 8-AFT THC NEG X OUTPUT - A
// 9-AFT THC POS Y OUTPUT - A
// 10-AFT THC NEG Y OUTPUT - A
// 11-AFT THC POS Z OUTPUT - A
// 12-AFT THC NEG Z OUTPUT - A
inline constexpr unsigned int SCP_FF1_IOM15_CH0_DATA = 0x0046b;// INTEGER SINGLE
// 5-ET SEPARATION MANUAL ENABLE A CMD
// 6-ET SEPARATION INITIATE A CMD
// 7-ET SEPARATION AUTO A CMD
inline constexpr unsigned int SCP_FF1_IOM15_CH1_DATA = 0x0046c;// INTEGER SINGLE

// MDM FF2 input
// Radar Altimeter 2 data
inline constexpr unsigned int SCP_FF2_IOM0_CH4_DATA = 0x0046d;// INTEGER SINGLE
// 2-ENTRY ROLL MODE NO Y JET B
// 3-LH BODY FLAP UP B
// 4-LH BODY FLAP DOWN B
// 5-MPS ME-1 SHUTDOWN CMD B
// 7-F_FU_MANF_ISOV_2_OP
// 8-F_FU_MANF_ISOV_2_CL
// 9-F_HE_FU_PRESS_V_B_OP
// 10-F_HE_FU_PRESS_V_B_CL
inline constexpr unsigned int SCP_FF2_IOM4_CH0_DATA = 0x0046e;// INTEGER SINGLE
// 10-FCS LH PITCH AUTO MODE B
// 11-FCS LH PITCH CSS MODE B
// 13-FCS LH R-Y AUTO MODE B
// 14-FCS LH R-Y CSS MODE B
// 15-LH BODY FLAP AUTO/MANUAL B
inline constexpr unsigned int SCP_FF2_IOM4_CH1_DATA = 0x0046f;// INTEGER SINGLE
// 0-LH SPD BK/THROT AUTO/MAN B
// 1-MPS ENG LIMIT CONTROL NO. 1 ENABLE
// 2-MPS ENG LIMIT CONTROL NO. 1 INHIBIT
// 3-MPS ENG LIMIT CONTROL NO. 1 AUTO
// 4-L PB VENT 3 CLOSED 2
// 5-L PB VENT 3 OPEN 2
// 6-L FWD VENTS 1 & 2 CLOSED 2
// 7-L FWD VENTS 1 & 2 OPEN 2
// 8-L FWD VENTS 1 & 2 PURGE IND 2
// 9-R PB VENT 6 CLOSED 2
// 10-R PB VENT 6 OPEN 2
// 11-R PB VENT 6 PURGE 1 IND 2
// 12-L PB/W VENTS 4 & 7 CLOSED 2
// 13-L PB/W VENTS 4 & 7 OPEN 2
// 14-R PB VENT 5 CLOSED 2
// 15-R PB VENT 5 OPEN 2
inline constexpr unsigned int SCP_FF2_IOM4_CH2_DATA = 0x00470;// INTEGER SINGLE
// 0-RJDF 1 JET F2F CHAMBER PRESS IND
// 1-RJDF 1 JET F2R CHAMBER PRESS IND
// 2-RJDF 1 JET F2U CHAMBER PRESS IND
// 3-RJDF 1 JET F2D CHAMBER PRESS IND
// 7-FWD THC POS X OUTPUT - B
// 8-FWD THC NEG X OUTPUT - B
// 9-FWD THC POS Y OUTPUT - B
// 10-FWD THC NEG Y OUTPUT - B
// 11-FWD THC POS Z OUTPUT - B
// 12-FWD THC NEG Z OUTPUT - B
// 13-LH SBTC TAKEOVER - B
inline constexpr unsigned int SCP_FF2_IOM6_CH0_DATA = 0x00471;// INTEGER SINGLE
// 1-LH RHC PLUS PITCH TRIM B
// 2-LH RHC MINUS PITCH TRIM B
// 3-LH RHC PLUS ROLL TRIM B
// 4-LH RHC MINUS ROLL TRIM B
inline constexpr unsigned int SCP_FF2_IOM6_CH1_DATA = 0x00472;// INTEGER SINGLE
// 0-RJDF 1 JET F2F DRIVER
// 1-RJDF 1 JET F2R DRIVER
// 2-RJDF 1 JET F2U DRIVER
// 3-RJDF 1 JET F2D DRIVER
// 4-FWD DAP SELECT A - B
// 5-FWD DAP SELECT B - B
// 8-FWD DAP AUTO B
// 9-FWD DAP MAN B
inline constexpr unsigned int SCP_FF2_IOM9_CH0_DATA = 0x00473;// INTEGER SINGLE
// 0-MPS ME-2 SHUTDOWN CMD A
// 1-SENSE SW -Z CON B
// 2-SENSE SW -X CON B
// 3-ENTRY ROLL MODE L GAIN - B
// 4-FWD ROTATION ROLL DISC RATE B
// 5-FWD ROTATION ROLL ACCEL B
// 6-FWD ROTATION ROLL PULSE B
// 7-FWD ROTATION PITCH DISC RATE B
// 8-FWD ROTATION PITCH ACCEL B
// 9-FWD ROTATION PITCH PULSE B
// 10-FWD ROTATION YAW DISC RATE B
// 11-FWD ROTATION YAW ACCEL B
// 12-FWD ROTATION YAW PULSE B
// 13-FWD RCS JETS NORM B
// 14-FWD RCS JETS VERNIER B
// 15-FWD TRANSLATION X NORM B
inline constexpr unsigned int SCP_FF2_IOM9_CH1_DATA = 0x00474;// INTEGER SINGLE
// 0-FWD TRANSLATION X PULSE B
// 1-FWD TRANSLATION X LVLH B
// 2-FWD TRANSLATION Y NORM B
// 3-FWD TRANSLATION Y PULSE B
// 4-FWD TRANSLATION Y LOW Z B
// 5-FWD TRANSLATION Z NORM B
// 6-FWD TRANSLATION Z PULSE B
// 7-FWD TRANSLATION Z HIGH B
// 8-MPS PRPLT DUMP SEQUENCE START B
// 9-MPS PRPLT DUMP SEQUENCE STOP B
inline constexpr unsigned int SCP_FF2_IOM9_CH2_DATA = 0x00475;// INTEGER SINGLE
// 1-LH PLUS PITCH TRIM B
// 2-LH MINUS PITCH TRIM B
// 3-LH PLUS ROLL TRIM B
// 4-LH MINUS ROLL TRIM B
// 5-LH PLUS YAW TRIM B
// 6-LH MINUS YAW TRIM B
// 7-F_OX_MANF_ISOV_2_OP
// 8-F_OX_MANF_ISOV_2_CL
// 9-F_HE_OX_PRESS_V_B_OP
// 10-F_HE_OX_PRESS_V_B_CL
// 13-PLT RDR ALTM SEL 1
inline constexpr unsigned int SCP_FF2_IOM12_CH0_DATA = 0x00476;// INTEGER SINGLE
// 8-LH RHC TRIM INHIBIT B
// 10-FCS RH PITCH AUTO MODE A
// 11-FCS RH PITCH CSS MODE A
// 13-FCS RH R-Y AUTO MODE A
// 14-FCS RH R-Y CSS MODE A
// 15-RH BODY FLAP AUTO/MANUAL A
inline constexpr unsigned int SCP_FF2_IOM12_CH1_DATA = 0x00477;// INTEGER SINGLE
// 0-RH SPD BK/THROT AUTO/MAN A
// 8-R PB VENT 6 PURGE 2 IND 2
inline constexpr unsigned int SCP_FF2_IOM12_CH2_DATA = 0x00478;// INTEGER SINGLE
// 7-AFT THC POS X OUTPUT - B
// 8-AFT THC NEG X OUTPUT - B
// 9-AFT THC POS Y OUTPUT - B
// 10-AFT THC NEG Y OUTPUT - B
// 11-AFT THC POS Z OUTPUT - B
// 12-AFT THC NEG Z OUTPUT - B
// 13-RH SBTC TAKEOVER - A
inline constexpr unsigned int SCP_FF2_IOM15_CH0_DATA = 0x00479;// INTEGER SINGLE

// MDM FF3 input
// 3-RH BODY FLAP UP A
// 4-RH BODY FLAP DOWN A
// 5-MPS ME-3 SHUTDOWN CMD A
// 7-F_FU_MANF_ISOV_4_OP
// 8-F_FU_MANF_ISOV_4_CL
// 9-F_FU_TK_ISOV_12_OP
// 10-F_FU_TK_ISOV_12_CL
// 11-F_FU_MANF_ISOV_5_OP
// 12-F_FU_MANF_ISOV_5_CL
inline constexpr unsigned int SCP_FF3_IOM4_CH0_DATA = 0x0047a;// INTEGER SINGLE
// 10-FCS LH PITCH AUTO MODE C
// 11-FCS LH PITCH CSS MODE C
// 13-FCS LH R-Y AUTO MODE C
// 14-FCS LH R-Y CSS MODE C
// 15-LH BODY FLAP AUTO/MANUAL C
inline constexpr unsigned int SCP_FF3_IOM4_CH1_DATA = 0x0047b;// INTEGER SINGLE
// 0-LH SPD BK/THROT AUTO/MAN C
// 1-MPS ENG LIMIT CONTROL NO. 2 ENABLE
// 2-MPS ENG LIMIT CONTROL NO. 2 INHIBIT
// 3-MPS ENG LIMIT CONTROL NO. 2 AUTO
// 4-L PB VENT 3 CLOSED 1
// 5-L PB VENT 3 OPEN 1
// 6-L FWD VENTS 1 & 2 CLOSED 1
// 7-L FWD VENTS 1 & 2 OPEN 1
// 8-L FWD VENTS 1 & 2 PURGE IND 1
// 9-R PB VENT 6 CLOSED 1
// 10-R PB VENT 6 OPEN 1
// 11-R PB VENT 6 PURGE 1 IND 1
// 12-L PB/W VENTS 4 & 7 CLOSED 1
// 13-L PB/W VENTS 4 & 7 OPEN 1
// 14-L PB VENT 5 CLOSED 1
// 15-L PB VENT 5 OPEN 1
inline constexpr unsigned int SCP_FF3_IOM4_CH2_DATA = 0x0047c;// INTEGER SINGLE
// 0-RJDF 2 JET F4R CHAMBER PRESS IND
// 1-RJDF 2 JET F4D CHAMBER PRESS IND
// 2-RJDF 2 JET F5L CHAMBER PRESS IND
// 3-RJDF 2 JET F5R CHAMBER PRESS IND
// 7-FWD THC POS X OUTPUT - C
// 8-FWD THC NEG X OUTPUT - C
// 9-FWD THC POS Y OUTPUT - C
// 10-FWD THC NEG Y OUTPUT - C
// 11-FWD THC POS Z OUTPUT - C
// 12-FWD THC NEG Z OUTPUT - C
// 13-LH SBTC TAKEOVER - C
inline constexpr unsigned int SCP_FF3_IOM6_CH0_DATA = 0x0047d;// INTEGER SINGLE
// 5-SRB SEPARATION AUTO C CMD
// 6-SRB SEPN MANUAL/AUTO ENABLE C CMD
// 7-SRB SEPARATION INITIATE C CMD
inline constexpr unsigned int SCP_FF3_IOM6_CH1_DATA = 0x0047e;// INTEGER SINGLE
// 0-RJDF 2 JET F4R DRIVER
// 1-RJDF 2 JET F4D DRIVER
// 2-RJDF 2 JET F5L DRIVER
// 3-RJDF 2 JET F5R DRIVER
// 4-AFT DAP SELECT A - A
// 5-AFT DAP SELECT B - A
// 6-FWD DAP SELECT A - C
// 7-FWD DAP SELECT B - C
// 8-AFT DAP AUTO A
// 9-AFT DAP MAN A
// 10-FWD DAP AUTO C
// 11-FWD DAP MAN C
inline constexpr unsigned int SCP_FF3_IOM9_CH0_DATA = 0x0047f;// INTEGER SINGLE
// 0-MPS ME-2 SHUTDOWN CMD B
// 1-SENSE SW -Z CON C
// 2-SENSE SW -X CON C
// 3-ENTRY ROLL MODE L GAIN - C
// 4-AFT ROTATION ROLL DISC RATE A
// 5-AFT ROTATION ROLL ACCEL A
// 6-AFT ROTATION ROLL PULSE A
// 7-AFT ROTATION PITCH DISC RATE A
// 8-AFT ROTATION PITCH ACCEL A
// 9-AFT ROTATION PITCH PULSE A
// 10-AFT ROTATION YAW DISC RATE A
// 11-AFT ROTATION YAW ACCEL A
// 12-AFT ROTATION YAW PULSE A
// 13-AFT RCS JETS NORM A
// 14-AFT RCS JETS VERNIER A
// 15-AFT TRANSLATION X NORM A
inline constexpr unsigned int SCP_FF3_IOM9_CH1_DATA = 0x00480;// INTEGER SINGLE
// 0-AFT TRANSLATION X PULSE A
// 1-AFT TRANSLATION X LVLH A
// 2-AFT TRANSLATION Y NORM A
// 3-AFT TRANSLATION Y PULSE A
// 4-AFT TRANSLATION Y LOW Z A
// 5-AFT TRANSLATION Z NORM A
// 6-AFT TRANSLATION Z PULSE A
// 7-AFT TRANSLATION Z HIGH A
// 8-MPS BACKUP LH2 PRPLT DUMP START A
// 9-MPS BACKUP LH2 PRPLT DUMP STOP A
inline constexpr unsigned int SCP_FF3_IOM9_CH2_DATA = 0x00481;// INTEGER SINGLE
// 1-RH PLUS PITCH TRIM A
// 2-RH MINUS PITCH TRIM A
// 3-RH PLUS ROLL TRIM A
// 4-RH MINUS ROLL TRIM A
// 5-RH PLUS YAW TRIM A
// 6-RH MINUS YAW TRIM A
// 7-F_OX_MANF_ISOV_4_OP
// 8-F_OX_MANF_ISOV_4_CL
// 9-F_OX_TK_ISOV_12_OP
// 10-F_OX_TK_ISOV_12_CL
// 11-F_OX_MANF_ISOV_5_OP
// 12-F_OX_MANF_ISOV_5_CL
inline constexpr unsigned int SCP_FF3_IOM12_CH0_DATA = 0x00482;// INTEGER SINGLE
// 2-ENTRY ROLL MODE NO Y JET C
// 8-RH RHC TRIM INHIBIT A
// 10-FCS RH PITCH AUTO MODE B
// 11-FCS RH PITCH CSS MODE B
// 13-FCS RH R-Y AUTO MODE B
// 14-FCS RH R-Y CSS MODE B
// 15-RH BODY FLAP AUTO/MANUAL B
inline constexpr unsigned int SCP_FF3_IOM12_CH1_DATA = 0x00483;// INTEGER SINGLE
// 0-RH SPD BK/THROT AUTO/MAN B
// 8-R PB VENT 6 PURGE 2 IND 1
// 14-FWD RCS OPTIONS NORM C
// 15-FWD RCS OPTIONS VERNIER C
inline constexpr unsigned int SCP_FF3_IOM12_CH2_DATA = 0x00484;// INTEGER SINGLE
// 7-AFT THC POS X OUTPUT - C
// 8-AFT THC NEG X OUTPUT - C
// 9-AFT THC POS Y OUTPUT - C
// 10-AFT THC NEG Y OUTPUT - C
// 11-AFT THC POS Z OUTPUT - C
// 12-AFT THC NEG Z OUTPUT - C
// 13-RH SBTC TAKEOVER - B
inline constexpr unsigned int SCP_FF3_IOM15_CH0_DATA = 0x00485;// INTEGER SINGLE
// 1-RH RHC PLUS PITCH TRIM A
// 2-RH RHC MINUS PITCH TRIM A
// 3-RH RHC PLUS ROLL TRIM A
// 4-RH RHC MINUS ROLL TRIM A
// 5-ET SEPARATION MANUAL ENABLE C CMD
// 6-ET SEPARATION INITIATE C CMD
// 7-ET SEPARATION AUTO C CMD
inline constexpr unsigned int SCP_FF3_IOM15_CH1_DATA = 0x00486;// INTEGER SINGLE

// MDM FF4 input
// 3-RH BODY FLAP UP B
// 4-RH BODY FLAP DOWN B
// 5-MPS ME-3 SHUTDOWN CMD B
// 7-F_FU_MANF_ISOV_3_OP
// 8-F_FU_MANF_ISOV_3_CL
inline constexpr unsigned int SCP_FF4_IOM4_CH0_DATA = 0x00487;// INTEGER SINGLE
// 1-MPS ENG LIMIT CONTROL NO. 3 ENABLE
// 2-MPS ENG LIMIT CONTROL NO. 3 INHIBIT
// 3-MPS ENG LIMIT CONTROL NO. 3 AUTO
// 4-R PB VENT 3 CLOSED 2
// 5-R PB VENT 3 OPEN 2
// 6-R FWD VENTS 1 & 2 CLOSED 2
// 7-R FWD VENTS 1 & 2 OPEN 2
// 8-R FWD VENTS 1 & 2 PURGE IND 2
// 9-L PB VENT 6 CLOSED 2
// 10-L PB VENT 6 OPEN 2
// 11-L PB VENT 6 PURGE 1 IND 2
// 12-R PB/W VENTS 4 & 7 CLOSED 1
// 13-R PB/W VENTS 4 & 7 OPEN 1
// 14-L PB VENT 5 CLOSED 2
// 15-L PB VENT 5 OPEN 2
inline constexpr unsigned int SCP_FF4_IOM4_CH2_DATA = 0x00488;// INTEGER SINGLE
// 0-RJDF 2 JET F3F CHAMBER PRESS IND
// 1-RJDF 2 JET F3L CHAMBER PRESS IND
// 2-RJDF 2 JET F3U CHAMBER PRESS IND
// 3-RJDF 2 JET F3D CHAMBER PRESS IND
inline constexpr unsigned int SCP_FF4_IOM6_CH0_DATA = 0x00489;// INTEGER SINGLE
// 5-SRB SEPARATION AUTO B CMD
// 6-SRB SEPN MANUAL/AUTO ENABLE B CMD
// 7-SRB SEPARATION INITIATE B CMD
inline constexpr unsigned int SCP_FF4_IOM6_CH1_DATA = 0x0048a;// INTEGER SINGLE
// 0-RJDF 2 JET F3F DRIVER
// 1-RJDF 2 JET F3L DRIVER
// 2-RJDF 2 JET F3U DRIVER
// 3-RJDF 2 JET F3D DRIVER
// 4-AFT DAP SELECT A - B
// 5-AFT DAP SELECT B - B
// 8-AFT DAP AUTO B
// 9-AFT DAP MAN B
inline constexpr unsigned int SCP_FF4_IOM9_CH0_DATA = 0x0048b;// INTEGER SINGLE
// 3-ENTRY ROLL MODE L GAIN - D
// 4-AFT ROTATION ROLL DISC RATE B
// 5-AFT ROTATION ROLL ACCEL B
// 6-AFT ROTATION ROLL PULSE B
// 7-AFT ROTATION PITCH DISC RATE B
// 8-AFT ROTATION PITCH ACCEL B
// 9-AFT ROTATION PITCH PULSE B
// 10-AFT ROTATION YAW DISC RATE B
// 11-AFT ROTATION YAW ACCEL B
// 12-AFT ROTATION YAW PULSE B
// 13-AFT RCS JETS NORM B
// 14-AFT RCS JETS VERNIER B
// 15-AFT TRANSLATION X NORM B
inline constexpr unsigned int SCP_FF4_IOM9_CH1_DATA = 0x0048c;// INTEGER SINGLE
// 0-AFT TRANSLATION X PULSE B
// 1-AFT TRANSLATION X LVLH B
// 2-AFT TRANSLATION Y NORM B
// 3-AFT TRANSLATION Y PULSE B
// 4-AFT TRANSLATION Y LOW Z B
// 5-AFT TRANSLATION Z NORM B
// 6-AFT TRANSLATION Z PULSE B
// 7-AFT TRANSLATION Z HIGH B
// 8-MPS BACKUP LH2 PRPLT DUMP START B
// 9-MPS BACKUP LH2 PRPLT DUMP STOP B
inline constexpr unsigned int SCP_FF4_IOM9_CH2_DATA = 0x0048d;// INTEGER SINGLE
// 1-RH PLUS PITCH TRIM B
// 2-RH MINUS PITCH TRIM B
// 3-RH PLUS ROLL TRIM B
// 4-RH MINUS ROLL TRIM B
// 5-RH PLUS YAW TRIM B
// 6-RH MINUS YAW TRIM B
// 7-F_OX_MANF_ISOV_3_OP
// 8-F_OX_MANF_ISOV_3_CL
inline constexpr unsigned int SCP_FF4_IOM12_CH0_DATA = 0x0048e;// INTEGER SINGLE
// 8-RH RHC TRIM INHIBIT B
// 10-FCS RH PITCH AUTO MODE C
// 11-FCS RH PITCH CSS MODE C
// 13-FCS RH R-Y AUTO MODE C
// 14-FCS RH R-Y CSS MODE C
// 15-RH BODY FLAP AUTO/MANUAL C
inline constexpr unsigned int SCP_FF4_IOM12_CH1_DATA = 0x0048f;// INTEGER SINGLE
// 0-RH SPD BK/THROT AUTO/MAN C
// 8-L PB VENT 6 PURGE 2 IND 2
// 15-ENTRY ROLL MODE NO Y JET D
inline constexpr unsigned int SCP_FF4_IOM12_CH2_DATA = 0x00490;// INTEGER SINGLE
// 13-RH SBTC TAKEOVER - C
inline constexpr unsigned int SCP_FF4_IOM15_CH0_DATA = 0x00491;// INTEGER SINGLE
// 1-RH RHC PLUS PITCH TRIM B
// 2-RH RHC MINUS PITCH TRIM B
// 3-RH RHC PLUS ROLL TRIM B
// 4-RH RHC MINUS ROLL TRIM B
// 5-ET SEPARATION MANUAL ENABLE B CMD
// 6-ET SEPARATION INITIATE B CMD
// 7-ET SEPARATION AUTO B CMD
inline constexpr unsigned int SCP_FF4_IOM15_CH1_DATA = 0x00492;// INTEGER SINGLE

// MDM FA1 input
// 2-L_OMS_FU_TK_ISOV_A_OP
// 3-L_OMS_FU_TK_ISOV_A_CL
// 4-L OMS VAP ISOV 1 OP
// 5-L OMS ENG PGE V1 POSN OP
// 8-R_OMS_OX_XFD_V_A_OP
// 9-R_OMS_OX_XFD_V_A_CL
// 10-R_OMS_FU_XFD_V_A_OP
// 11-R_OMS_FU_XFD_V_A_CL
inline constexpr unsigned int SCP_FA1_IOM3_CH1_DATA = 0x00493;// INTEGER SINGLE
// 0-R_FU_MANF_ISOV_1_OP
// 1-R_FU_MANF_ISOV_1_CL
// 2-R_OX_MANF_ISOV_1_OP
// 3-R_OX_MANF_ISOV_1_CL
// 4-R_RCS_OX_XFD_345_OP
// 5-R_RCS_OX_XFD_345_CL
// 6-R_RCS_FU_XFD_345_OP
// 7-R_RCS_FU_XFD_345_CL
// 8-R_HE_OX_PRESS_V_A_OP
// 9-R_HE_OX_PRESS_V_A_CL
// 10-R_HE_FU_PRESS_V_A_OP
// 11-R_HE_FU_PRESS_V_A_CL
inline constexpr unsigned int SCP_FA1_IOM3_CH2_DATA = 0x00494;// INTEGER SINGLE
// 0-RJDA 1 JET L1A CHMBR PRESS IND
// 1-RJDA 1 JET L1L CHMBR PRESS IND
// 2-RJDA 1 JET L1U CHMBR PRESS IND
// 3-RJDA 1 JET R1A CHMBR PRESS IND
// 4-RJDA 1 JET R1R CHMBR PRESS IND
// 5-RJDA 1 JET R1U CHMBR PRESS IND
// 6-RJDA 1 JET L5D CHMBR PRESS IND
// 7-RJDA 1 JET L5L CHMBR PRESS IND
inline constexpr unsigned int SCP_FA1_IOM5_CH0_DATA = 0x00495;// INTEGER SINGLE
// 0-RJDA 1 JET L1A DRIVER
// 1-RJDA 1 JET L1L DRIVER
// 2-RJDA 1 JET L1U DRIVER
// 3-RJDA 1 JET R1A DRIVER
// 4-RJDA 1 JET R1R DRIVER
// 5-RJDA 1 JET R1U DRIVER
// 6-RJDA 1 JET L5D DRIVER
// 7-RJDA 1 JET L5L DRIVER
inline constexpr unsigned int SCP_FA1_IOM8_CH0_DATA = 0x00496;// INTEGER SINGLE
// 13-L AFT VENTS 8 & 9 CLOSED 1
// 14-L AFT VENTS 8 & 9 OPEN 1
// 15-L AFT VENTS 8 & 9 PURGE IND 1
inline constexpr unsigned int SCP_FA1_IOM11_CH0_DATA = 0x00497;// INTEGER SINGLE
// 2-L_OMS_OX_TK_ISOV_A_OP
// 3-L_OMS_OX_TK_ISOV_A_CL
// 4-L OMS HE ISOV A POSN OP
// 6-L_OMS_OX_XFD_V_A_OP
// 7-L_OMS_OX_XFD_V_A_CL
// 8-L_OMS_FU_XFD_V_A_OP
// 9-L_OMS_FU_XFD_V_A_CL
inline constexpr unsigned int SCP_FA1_IOM11_CH1_DATA = 0x00498;// INTEGER SINGLE
// 0-L_FU_MANF_ISOV_1_OP
// 1-L_FU_MANF_ISOV_1_CL
// 2-L_OX_MANF_ISOV_1_OP
// 3-L_OX_MANF_ISOV_1_CL
// 4-L_OX_TK_ISO_V_12_OP
// 5-L_OX_TK_ISO_V_12_CL
// 6-L_FU_TK_ISO_V_12_OP
// 7-L_FU_TK_ISO_V_12_CL
// 8-L_HE_OX_PRESS_V_A_OP
// 9-L_HE_OX_PRESS_V_A_CL
// 10-L_HE_FU_PRESS_V_A_OP
// 11-L_HE_FU_PRESS_V_A_CL
// 12-L_OX_MANF_ISOV_5_OP
// 13-L_FU_MANF_ISOV_5_OP
// 14-L_OX_MANF_ISOV_5_CL
// 15-L_FU_MANF_ISOV_5_CL
inline constexpr unsigned int SCP_FA1_IOM11_CH2_DATA = 0x00499;// INTEGER SINGLE

// MDM FA2 input
// 2-L_OMS_FU_TK_ISOV_B_OP
// 3-L_OMS_FU_TK_ISOV_B_CL
// 4-L OMS VAP ISOV 2 OP
// 5-L OMS ENG PGE V2 POSN OP
// 8-R_OMS_OX_XFD_V_B_OP
// 9-R_OMS_OX_XFD_V_B_CL
// 10-R_OMS_FU_XFD_V_B_OP
// 11-R_OMS_FU_XFD_V_B_CL
inline constexpr unsigned int SCP_FA2_IOM3_CH1_DATA = 0x0049a;// INTEGER SINGLE
// 0-R_FU_MANF_ISOV_3_OP
// 1-R_FU_MANF_ISOV_3_CL
// 2-R_OX_MANF_ISOV_3_OP
// 3-R_OX_MANF_ISOV_3_CL
// 4-R_OX_TK_ISO_V_12_OP
// 5-R_OX_TK_ISO_V_12_CL
// 6-R_FU_TK_ISO_V_12_OP
// 7-R_FU_TK_ISO_V_12_CL
// 8-R_HE_OX_PRESS_V_B_OP
// 9-R_HE_OX_PRESS_V_B_CL
// 10-R_HE_FU_PRESS_V_B_OP
// 11-R_HE_FU_PRESS_V_B_CL
// 12-R_OX_MANF_ISOV_5_OP
// 13-R_FU_MANF_ISOV_5_OP
// 14-R_OX_MANF_ISOV_5_CL
// 15-R_FU_MANF_ISOV_5_CL
inline constexpr unsigned int SCP_FA2_IOM3_CH2_DATA = 0x0049b;// INTEGER SINGLE
// 0-RJDA 2 JET L3A CHMBR PRESS IND
// 1-RJDA 2 JET L3L CHMBR PRESS IND
// 2-RJDA 2 JET L3D CHMBR PRESS IND
// 3-RJDA 2 JET R3A CHMBR PRESS IND
// 4-RJDA 2 JET R3R CHMBR PRESS IND
// 5-RJDA 2 JET R3D CHMBR PRESS IND
// 6-RJDA 2 JET R5R CHMBR PRESS IND
// 7-RJDA 2 JET R5D CHMBR PRESS IND
inline constexpr unsigned int SCP_FA2_IOM5_CH0_DATA = 0x0049c;// INTEGER SINGLE
// 0-RJDA 2 JET L3A DRIVER
// 1-RJDA 2 JET L3L DRIVER
// 2-RJDA 2 JET L3D DRIVER
// 3-RJDA 2 JET R3A DRIVER
// 4-RJDA 2 JET R3R DRIVER
// 5-RJDA 2 JET R3D DRIVER
// 6-RJDA 2 JET R5R DRIVER
// 7-RJDA 2 JET R5D DRIVER
inline constexpr unsigned int SCP_FA2_IOM8_CH0_DATA = 0x0049d;// INTEGER SINGLE
// 13-R AFT VENTS 8 & 9 CLOSED 2
// 14-R AFT VENTS 8 & 9 OPEN 2
// 15-R AFT VENTS 8 & 9 PURGE IND 2
inline constexpr unsigned int SCP_FA2_IOM11_CH0_DATA = 0x0049e;// INTEGER SINGLE
// 2-L_OMS_OX_TK_ISOV_B_OP
// 3-L_OMS_OX_TK_ISOV_B_CL
// 4-L OMS HE ISOV B POSN OP
// 6-L_OMS_OX_XFD_V_B_OP
// 7-L_OMS_OX_XFD_V_B_CL
// 8-L_OMS_FU_XFD_V_B_OP
// 9-L_OMS_FU_XFD_V_B_CL
inline constexpr unsigned int SCP_FA2_IOM11_CH1_DATA = 0x0049f;// INTEGER SINGLE
// 0-L_FU_MANF_ISOV_3_OP
// 1-L_FU_MANF_ISOV_3_CL
// 2-L_OX_MANF_ISOV_3_OP
// 3-L_OX_MANF_ISOV_3_CL
// 4-L_RCS_OX_XFD_345_OP
// 5-L_RCS_OX_XFD_345_CL
// 6-L_RCS_FU_XFD_345_OP
// 7-L_RCS_FU_XFD_345_CL
inline constexpr unsigned int SCP_FA2_IOM11_CH2_DATA = 0x004a0;// INTEGER SINGLE

// MDM FA3 input
// 2-R_OMS_FU_TK_ISOV_B_OP
// 3-R_OMS_FU_TK_ISOV_B_CL
// 4-R OMS VAP ISOV 1 OP
// 5-R OMS ENG PGE V1 POSN OP
inline constexpr unsigned int SCP_FA3_IOM3_CH1_DATA = 0x004a1;// INTEGER SINGLE
// 0-R_FU_MANF_ISOV_2_OP
// 1-R_FU_MANF_ISOV_2_CL
// 2-R_OX_MANF_ISOV_2_OP
// 3-R_OX_MANF_ISOV_2_CL
// 4-R_OX_TK_ISO_V_345_A_OP
// 5-R_OX_TK_ISO_V_345_A_CL
// 6-R_FU_TK_ISO_V_345_A_OP
// 7-R_FU_TK_ISO_V_345_A_CL
// 8-L_RCS_OX_XFD_12_OP
// 9-L_RCS_OX_XFD_12_CL
// 10-L_RCS_FU_XFD_12_OP
// 11-L_RCS_FU_XFD_12_CL
inline constexpr unsigned int SCP_FA3_IOM3_CH2_DATA = 0x004a2;// INTEGER SINGLE
// 0-RJDA 1 JET L2L CHMBR PRESS IND
// 1-RJDA 1 JET L2U CHMBR PRESS IND
// 2-RJDA 1 JET L2D CHMBR PRESS IND
// 3-RJDA 1 JET R2R CHMBR PRESS IND
// 4-RJDA 1 JET R2U CHMBR PRESS IND
// 5-RJDA 1 JET R2D CHMBR PRESS IND
inline constexpr unsigned int SCP_FA3_IOM5_CH0_DATA = 0x004a3;// INTEGER SINGLE
// 0-RJDA 1 JET L2L DRIVER
// 1-RJDA 1 JET L2U DRIVER
// 2-RJDA 1 JET L2D DRIVER
// 3-RJDA 1 JET R2R DRIVER
// 4-RJDA 1 JET R2U DRIVER
// 5-RJDA 1 JET R2D DRIVER
inline constexpr unsigned int SCP_FA3_IOM8_CH0_DATA = 0x004a4;// INTEGER SINGLE
// 13-R AFT VENTS 8 & 9 CLOSED 1
// 14-R AFT VENTS 8 & 9 OPEN 1
// 15-R AFT VENTS 8 & 9 PURGE IND 1
inline constexpr unsigned int SCP_FA3_IOM11_CH0_DATA = 0x004a5;// INTEGER SINGLE
// 2-R_OMS_OX_TK_ISOV_B_OP
// 3-R_OMS_OX_TK_ISOV_B_CL
// 4-R OMS HE ISOV A POSN OP
// 5-L OMS ENG PRESS V OP
inline constexpr unsigned int SCP_FA3_IOM11_CH1_DATA = 0x004a6;// INTEGER SINGLE
// 0-L_FU_MANF_ISOV_2_OP
// 1-L_FU_MANF_ISOV_2_CL
// 2-L_OX_MANF_ISOV_2_OP
// 3-L_OX_MANF_ISOV_2_CL
// 4-L_OX_TK_ISO_V_345_A_OP
// 5-L_OX_TK_ISO_V_345_A_CL
// 6-L_FU_TK_ISO_V_345_A_OP
// 7-L_FU_TK_ISO_V_345_A_CL
// 8-L_HE_OX_PRESS_V_B_OP
// 9-L_HE_OX_PRESS_V_B_CL
// 10-L_HE_FU_PRESS_V_B_OP
// 11-L_HE_FU_PRESS_V_B_CL
inline constexpr unsigned int SCP_FA3_IOM11_CH2_DATA = 0x004a7;// INTEGER SINGLE

// MDM FA4 input
// 2-R_OMS_FU_TK_ISOV_A_OP
// 3-R_OMS_FU_TK_ISOV_A_CL
// 4-R OMS VAP ISOV 2 OP
// 5-R OMS ENG PGE V2 POSN OP
inline constexpr unsigned int SCP_FA4_IOM3_CH1_DATA = 0x004a8;// INTEGER SINGLE
// 0-R_FU_MANF_ISOV_4_OP
// 1-R_FU_MANF_ISOV_4_CL
// 2-R_OX_MANF_ISOV_4_OP
// 3-R_OX_MANF_ISOV_4_CL
// 4-R_OX_TK_ISO_V_345_B_OP
// 5-R_OX_TK_ISO_V_345_B_CL
// 6-R_FU_TK_ISO_V_345_B_OP
// 7-R_FU_TK_ISO_V_345_B_CL
inline constexpr unsigned int SCP_FA4_IOM3_CH2_DATA = 0x004a9;// INTEGER SINGLE
// 0-RJDA 2 JET L4L CHMBR PRESS IND
// 1-RJDA 2 JET L4U CHMBR PRESS IND
// 2-RJDA 2 JET L4D CHMBR PRESS IND
// 3-RJDA 2 JET R4R CHMBR PRESS IND
// 4-RJDA 2 JET R4U CHMBR PRESS IND
// 5-RJDA 2 JET R4D CHMBR PRESS IND
inline constexpr unsigned int SCP_FA4_IOM5_CH0_DATA = 0x004aa;// INTEGER SINGLE
// 0-RJDA 2 JET L4L DRIVER
// 1-RJDA 2 JET L4U DRIVER
// 2-RJDA 2 JET L4D DRIVER
// 3-RJDA 2 JET R4R DRIVER
// 4-RJDA 2 JET R4U DRIVER
// 5-RJDA 2 JET R4D DRIVER
inline constexpr unsigned int SCP_FA4_IOM8_CH0_DATA = 0x004ab;// INTEGER SINGLE
// 13-L AFT VENTS 8 & 9 CLOSED 2
// 14-L AFT VENTS 8 & 9 OPEN 2
// 15-L AFT VENTS 8 & 9 PURGE IND 2
inline constexpr unsigned int SCP_FA4_IOM11_CH0_DATA = 0x004ac;// INTEGER SINGLE
// 2-R_OMS_OX_TK_ISOV_A_OP
// 3-R_OMS_OX_TK_ISOV_A_CL
// 4-R OMS HE ISOV B POSN OP
// 5-R OMS ENG PRESS V OP
inline constexpr unsigned int SCP_FA4_IOM11_CH1_DATA = 0x004ad;// INTEGER SINGLE
// 0-L_FU_MANF_ISOV_4_OP
// 1-L_FU_MANF_ISOV_4_CL
// 2-L_OX_MANF_ISOV_4_OP
// 3-L_OX_MANF_ISOV_4_CL
// 4-L_OX_TK_ISO_V_345_B_OP
// 5-L_OX_TK_ISO_V_345_B_CL
// 6-L_FU_TK_ISO_V_345_B_OP
// 7-L_FU_TK_ISO_V_345_B_CL
// 8-R_RCS_OX_XFD_12_OP
// 9-R_RCS_OX_XFD_12_CL
// 10-R_RCS_FU_XFD_12_OP
// 11-R_RCS_FU_XFD_12_CL
inline constexpr unsigned int SCP_FA4_IOM11_CH2_DATA = 0x004ae;// INTEGER SINGLE

// MDM FF1 output
// 0-RH VENTS 1/2 MOTOR 1/CLOSE B (CL/1B)
// 1-RH VENTS 1/2 MOTOR 1/OPEN B (OP/1B)
// 2-RH VENTS 1/2 MOTOR 1/PURGE B (PG/1B)
// 3-MANF_ISOV_NO_1_OP
// 4-MANF_ISOV_NO_4_CL_A
// 5-F_OX_TK_ISOV_345_OP_A
// 6-F_OX_TK_ISOV_345_CL_B
// 7-F_TK_ISOV_345_CL_A
// 11-RH VENTS 4/7 MOTOR 2/CLOSE B (CL/2B)
// 12-F_MANF_ISOL_5_OP_B (actual position unknown)
inline constexpr unsigned int SCP_FF1_IOM2_CH0_DATA = 0x004af;// INTEGER SINGLE
// 0-F7 LIGHT: C MPS AMBER STATUS
// 7-F6 LIGHT A: RCS CMD "ROLL LEFT"
// 8-F6 LIGHT A: RCS CMD "ROLL RIGHT"
// 9-F6 LIGHT A: RCS CMD "YAW LEFT"
// 10-F6 LIGHT A: RCS CMD "YAW RIGHT"
// 11-F6 LIGHT A: RCS CMD "PITCH UP"
// 12-F6 LIGHT A: RCS CMD "PITCH DOWN"
// 13-C3 LIGHT: FWD DAP CONTROL "AUTO"
// 14-C3 LIGHT: FWD DAP SELECT "A"
// 15-C3 LIGHT: FWD DAP RCS JETS "NORM"
inline constexpr unsigned int SCP_FF1_IOM2_CH1_DATA = 0x004b0;// INTEGER SINGLE
// 3-C3 LIGHT: FWD DAP CONTROL "MAN"
// 4-C3 LIGHT: FWD DAP SELECT "B"
// 5-C3 LIGHT: FWD DAP RCS JETS "VERN"
// 7-RH VENTS 4/7 MOTOR 2/OPEN B (OP/2B)
// 8-RH VENT 3 MOTOR 1/CLOSE B (CL/1B)
// 9-RH VENT 3 MOTOR 1/OPEN B (OP/1B)
// 10-LH VENT 6 MOTOR 1/CLOSE B (CL/1B)
// 11-LH VENT 6 MOTOR 1/OPEN B (OP/1B)
// 12-LH VENT 6 MOTOR 1/PRG-1 B (P1/1B)
// 13-LH VENT 6 MOTOR 1/PRG-2 B (P2/1B)
// 14-RH VENT 5 MOTOR 1/CLOSE B (CL/1B)
// 15-RH VENT 5 MOTOR 1/OPEN B (OP/1B)
inline constexpr unsigned int SCP_FF1_IOM2_CH2_DATA = 0x004b1;// INTEGER SINGLE
// 0-RJDF 1B F RCS JET F1F CMD A
// 1-RJDF 1B F RCS JET F1L CMD A
// 2-RJDF 1B F RCS JET F1U CMD A
// 3-RJDF 1B F RCS JET F1D CMD A
inline constexpr unsigned int SCP_FF1_IOM5_CH0_DATA = 0x004b2;// INTEGER SINGLE
// 0-FWD EVENT TIMER: ABORT TIMER RESET
// 11-C&W MATRIX "LEFT RCS" (LEAK DETECT)
inline constexpr unsigned int SCP_FF1_IOM5_CH1_DATA = 0x004b3;// INTEGER SINGLE
// F7 TAPE MTR: MPS PRESS "C MPS Pc"
inline constexpr unsigned int SCP_FF1_IOM8_CH0_DATA = 0x004b4;// INTEGER SINGLE
// SPI: SPEED BRK "COMMAND"
inline constexpr unsigned int SCP_FF1_IOM8_CH7_DATA = 0x004b5;// INTEGER SINGLE
// SPI: "RUDDER" POSITION
inline constexpr unsigned int SCP_FF1_IOM8_CH8_DATA = 0x004b6;// INTEGER SINGLE
// SPI: "SPEEDBRAKE" POSITION
inline constexpr unsigned int SCP_FF1_IOM8_CH9_DATA = 0x004b7;// INTEGER SINGLE
// SPI: "ELEVONS" L INBD POSITION
inline constexpr unsigned int SCP_FF1_IOM8_CH10_DATA = 0x004b8;// INTEGER SINGLE
// SPI: "ELEVONS" L OTBD POSITION
inline constexpr unsigned int SCP_FF1_IOM8_CH11_DATA = 0x004b9;// INTEGER SINGLE
// SPI: "ELEVONS" R INBD POSITION
inline constexpr unsigned int SCP_FF1_IOM8_CH12_DATA = 0x004ba;// INTEGER SINGLE
// SPI: "ELEVONS" R OTBD POSITION
inline constexpr unsigned int SCP_FF1_IOM8_CH13_DATA = 0x004bb;// INTEGER SINGLE
// 0-RH VENTS 1/2 MOTOR 1/CLOSE A (CL/1A)
// 1-RH VENTS 1/2 MOTOR 1/OPEN A (OP/1A)
// 2-RH VENTS 1/2 MOTOR 1/PURGE A (PG/1A)
// 4-F2 LIGHT: LH FCS BODY FLAP "AUTO"
// 5-F2 LIGHT: LH FCS SPEED BK "AUTO"
// 6-F2 LIGHT: LH FCS PITCH "AUTO"
// 7-F2 LIGHT: LH FCS ROLL/YAW "AUTO"
// 10-F_FU_TK_ISOV_345_OP_A
// 11-F_FU_TK_ISOV_345_CL_B
// 12-F_MANF_ISOL_5_CL_A (actual position unknown)
// 13-F_HE_PR_VLV_A_OP_A
// 14-F_HE_PR_VLV_A_CL_A
// 15-MANF_ISOV_NO_4_CL_B
inline constexpr unsigned int SCP_FF1_IOM10_CH0_DATA = 0x004bc;// INTEGER SINGLE
// 0-F7 LIGHT: C MPS RED STATUS
// 1-C3 LIGHT: FWD MAN ROT ROLL "DISC RT"
// 2-C3 LIGHT: FWD MAN ROT ROLL "ACCEL"
// 3-C3 LIGHT: FWD MAN ROT ROLL "PULSE"
// 4-C3 LIGHT: FWD MAN ROT PITCH "DISC RT"
// 5-C3 LIGHT: FWD MAN ROT PITCH "ACCEL"
// 6-C3 LIGHT: FWD MAN ROT PITCH "PULSE"
// 7-C3 LIGHT: FWD MAN ROT YAW "DISC RT"
// 8-C3 LIGHT: FWD MAN ROT YAW "ACCEL"
// 9-C3 LIGHT: FWD MAN ROT YAW "PULSE"
// 10-C3 LIGHT: FWD MAN TRANS X "NORM"
// 11-C3 LIGHT: FWD MAN TRANS X "PULSE"
// 12-C3 LIGHT: FWD MAN TRANS X "LVLH"
// 13-C3 LIGHT: FWD MAN TRANS Y "NORM"
// 14-C3 LIGHT: FWD MAN TRANS Y "PULSE"
// 15-C3 LIGHT: FWD MAN TRANS Y "LOW Z"
inline constexpr unsigned int SCP_FF1_IOM10_CH1_DATA = 0x004bd;// INTEGER SINGLE
// 0-C3 LIGHT: FWD MAN TRANS Z "NORM"
// 1-C3 LIGHT: FWD MAN TRANS Z "PULSE"
// 2-C3 LIGHT: FWD MAN TRANS Z "HIGH"
// 3-C&W MATRIX "BACKUP C/W ALARM"
// 4-SM ALERT: TONE A CMD 1
// 5-SM ALERT: LIGHT A CMD 1
// 6-RH VENTS 4/7 MOTOR 2/CLOSE A (CL/2A)
// 7-RH VENTS 4/7 MOTOR 2/OPEN A (OP/2A)
// 8-RH VENT 3 MOTOR 1/CLOSE A (CL/1A)
// 9-RH VENT 3 MOTOR 1/OPEN A (OP/1A)
// 10-LH VENT 6 MOTOR 1/CLOSE A (CL/1A)
// 11-LH VENT 6 MOTOR 1/OPEN A (OP/1A)
// 12-LH VENT 6 MOTOR 1/PRG-1 A (P1/1A)
// 13-LH VENT 6 MOTOR 1/PRG-2 A (P2/1A)
// 14-RH VENT 5 MOTOR 1/CLOSE A (CL/1A)
// 15-RH VENT 5 MOTOR 1/OPEN A (OP/1A)
inline constexpr unsigned int SCP_FF1_IOM10_CH2_DATA = 0x004be;// INTEGER SINGLE
// 0-RJDF 1B F RCS JET F1F CMD B
// 1-RJDF 1B F RCS JET F1L CMD B
// 2-RJDF 1B F RCS JET F1U CMD B
// 3-RJDF 1B F RCS JET F1D CMD B
// 10-SPI: DATA VALID CMD ("OFF" FLAG)
inline constexpr unsigned int SCP_FF1_IOM13_CH0_DATA = 0x004bf;// INTEGER SINGLE

// MDM FF2 output
// 0-LH VENTS 1/2 MOTOR 2/CLOSE B (CL/2B)
// 1-LH VENTS 1/2 MOTOR 2/OPEN B (OP/2B)
// 2-LH VENTS 1/2 MOTOR 2/PURGE B (PG/2B)
// 3-MANF_ISOV_NO_2_OP
// 4-MANF_ISOV_NO_3_CL_A
// 12-F_MANF_ISOL_5_CL_C (actual position unknown)
inline constexpr unsigned int SCP_FF2_IOM2_CH0_DATA = 0x004c0;// INTEGER SINGLE
// 0-F7 LIGHT: L MPS AMBER STATUS
// 6-RH VENT 5 MOTOR 2/CLOSE B (CL/2B)
inline constexpr unsigned int SCP_FF2_IOM2_CH1_DATA = 0x004c1;// INTEGER SINGLE
// 6-LH VENT 3 MOTOR 2/CLOSE B (CL/2B)
// 7-LH VENT 3 MOTOR 2/OPEN B (OP/2B)
// 8-LH VENTS 4/7 MOTOR 2/CLOSE B (CL/2B)
// 9-LH VENTS 4/7 MOTOR 2/OPEN B (OP/2B)
// 10-RH VENT 6 MOTOR 2/CLOSE B (CL/2B)
// 11-RH VENT 6 MOTOR 2/OPEN B (OP/2B)
// 12-RH VENT 6 MOTOR 2/PRG-1 B (P1/2B)
// 13-RH VENT 6 MOTOR 2/PRG-2 B (P2/2B)
// 15-RH VENT 5 MOTOR 2/OPEN B (OP/2B)
inline constexpr unsigned int SCP_FF2_IOM2_CH2_DATA = 0x004c2;// INTEGER SINGLE
// 0-RJDF 1A F RCS JET F2F CMD A
// 1-RJDF 1A F RCS JET F2R CMD A
// 2-RJDF 1A F RCS JET F2U CMD A
// 3-RJDF 1A F RCS JET F2D CMD A
inline constexpr unsigned int SCP_FF2_IOM5_CH0_DATA = 0x004c3;// INTEGER SINGLE
// F7 TAPE MTR: MPS PRESS "L MPS Pc"
inline constexpr unsigned int SCP_FF2_IOM8_CH0_DATA = 0x004c4;// INTEGER SINGLE
// SPI: "BODY FLAP" POSITION
inline constexpr unsigned int SCP_FF2_IOM8_CH8_DATA = 0x004c5;// INTEGER SINGLE
// SPI: "AILERON" POSITION
inline constexpr unsigned int SCP_FF2_IOM8_CH9_DATA = 0x004c6;// INTEGER SINGLE
// 0-LH VENTS 1/2 MOTOR 2/CLOSE A (CL/2A)
// 1-LH VENTS 1/2 MOTOR 2/OPEN A (OP/2A)
// 2-LH VENTS 1/2 MOTOR 2/PURGE A (PG/2A)
// 4-F2 LIGHT: LH FCS BODY FLAP "MAN"
// 5-F2 LIGHT: LH FCS SPEED BK "MAN"
// 6-F2 LIGHT: LH FCS PITCH "CSS"
// 7-F2 LIGHT: LH FCS ROLL/YAW "CSS"
// 12-F_MANF_ISOL_5_OP_C (actual position unknown)
// 15-MANF_ISOV_NO_3_CL_B
inline constexpr unsigned int SCP_FF2_IOM10_CH0_DATA = 0x004c7;// INTEGER SINGLE
// 0-F7 LIGHT: L MPS RED STATUS
inline constexpr unsigned int SCP_FF2_IOM10_CH1_DATA = 0x004c8;// INTEGER SINGLE
// 3-C&W MATRIX "BACKUP C/W ALARM"
// 4-SM ALERT: TONE A CMD 2
// 5-SM ALERT: LIGHT A CMD 2
// 6-LH VENT 3 MOTOR 2/CLOSE A (CL/2A)
// 7-LH VENT 3 MOTOR 2/OPEN A (OP/2A)
// 8-LH VENTS 4/7 MOTOR 2/CLOSE A (CL/2A)
// 9-LH VENTS 4/7 MOTOR 2/OPEN A (OP/2A)
// 10-RH VENT 6 MOTOR 2/CLOSE A (CL/2A)
// 11-RH VENT 6 MOTOR 2/OPEN A (OP/2A)
// 12-RH VENT 6 MOTOR 2/PRG-1 A (P1/2A)
// 13-RH VENT 6 MOTOR 2/PRG-2 A (P2/2A)
// 14-RH VENT 5 MOTOR 2/CLOSE A (CL/2A)
// 15-RH VENT 5 MOTOR 2/OPEN A (OP/2A)
inline constexpr unsigned int SCP_FF2_IOM10_CH2_DATA = 0x004c9;// INTEGER SINGLE
// 0-RJDF 1A F RCS JET F2F CMD B
// 1-RJDF 1A F RCS JET F2R CMD B
// 2-RJDF 1A F RCS JET F2U CMD B
// 3-RJDF 1A F RCS JET F2D CMD B
inline constexpr unsigned int SCP_FF2_IOM13_CH0_DATA = 0x004ca;// INTEGER SINGLE

// MDM FF3 output
// 0-LH VENT 3 MOTOR 1/OPEN B (OP/1B)
// 1-LH VENTS 1/2 MOTOR 1/OPEN B (OP/1B)
// 2-LH VENTS 1/2 MOTOR 1/PURGE B (PG/1B)
// 3-MANF_ISOV_NO_4_OP
// 4-MANF_ISOV_NO_1_CL_A
// 5-F_OX_TK_ISOV_12_OP_A
// 6-F_OX_TK_ISOV_12_CL_B
// 7-F_TK_ISOV_12_CL_A
// 12-F_MANF_ISOL_5_CL_B (actual position unknown)
inline constexpr unsigned int SCP_FF3_IOM2_CH0_DATA = 0x004cb;// INTEGER SINGLE
// 0-F7 LIGHT: R MPS AMBER STATUS
// 6-LH VENTS 4/7 MOTOR 1/CLOSE B (CL/1B)
// 7-F6 LIGHT B: RCS CMD "ROLL LEFT"
// 8-F6 LIGHT B: RCS CMD "ROLL RIGHT"
// 9-F6 LIGHT B: RCS CMD "YAW LEFT"
// 10-F6 LIGHT B: RCS CMD "YAW RIGHT"
// 11-F6 LIGHT B: RCS CMD "PITCH UP"
// 12-F6 LIGHT B: RCS CMD "PITCH DOWN"
// 13-A6 LIGHT: AFT DAP CONTROL "AUTO"
// 14-A6 LIGHT: AFT DAP SELECT "A"
// 15-A6 LIGHT: AFT DAP RCS JETS "NORM"
inline constexpr unsigned int SCP_FF3_IOM2_CH1_DATA = 0x004cc;// INTEGER SINGLE
// 3-A6 LIGHT: AFT DAP CONTROL "MAN"
// 4-A6 LIGHT: AFT DAP SELECT "B"
// 5-A6 LIGHT: AFT DAP RCS JETS "VERN"
// 6-LH VENT 3 MOTOR 1/CLOSE B (CL/1B)
// 7-LH VENTS 1/2 MOTOR 1/CLOSE B (CL/1B)
// 9-LH VENTS 4/7 MOTOR 1/OPEN B (OP/1B)
// 10-RH VENT 6 MOTOR 1/CLOSE B (CL/1B)
// 11-RH VENT 6 MOTOR 1/OPEN B (OP/1B)
// 12-RH VENT 6 MOTOR 1/PRG-1 B (P1/1B)
// 13-RH VENT 6 MOTOR 1/PRG-2 B (P2/1B)
// 14-LH VENT 5 MOTOR 1/CLOSE B (CL/1B)
// 15-LH VENT 5 MOTOR 1/OPEN B (OP/1B)
inline constexpr unsigned int SCP_FF3_IOM2_CH2_DATA = 0x004cd;// INTEGER SINGLE
// 0-RJDF 2B F RCS JET F4R CMD A
// 1-RJDF 2B F RCS JET F4D CMD A
// 2-RJDF 2B F RCS JET F5L CMD A
// 3-RJDF 2B F RCS JET F5R CMD A
inline constexpr unsigned int SCP_FF3_IOM5_CH0_DATA = 0x004ce;// INTEGER SINGLE
// 0-C&W MATRIX "RCS JET"
// 1-C&W MATRIX "OMS TVC"
// 2-C&W MATRIX "LEFT OMS"
// 3-C&W MATRIX "RIGHT OMS"
// 4-C&W MATRIX "FCS CHANNEL"
// 5-C&W MATRIX "FCS SATURATION"
// 6-C&W MATRIX "IMU"
// 7-C&W MATRIX "RIGHT/AFT RHC"
// 8-C&W MATRIX "LEFT RHC"
// 9-C&W MATRIX "AIR DATA"
// 10-C&W MATRIX "RGA/ACCEL"
// 11-C&W MATRIX "RIGHT RCS" (LEAK DETECT)
// 12-C&W MATRIX "FWD RCS" (LEAK DETECT)
inline constexpr unsigned int SCP_FF3_IOM5_CH1_DATA = 0x004cf;// INTEGER SINGLE
// F7 TAPE MTR: MPS PRESS "R MPS Pc"
inline constexpr unsigned int SCP_FF3_IOM8_CH0_DATA = 0x004d0;// INTEGER SINGLE
// 0-LH VENTS 1/2 MOTOR 1/CLOSE A (CL/1A)
// 1-LH VENTS 1/2 MOTOR 1/OPEN A (OP/1A)
// 2-LH VENT 3 MOTOR 1/OPEN A (OP/1A)
// 4-F4 LIGHT: RH FCS BODY FLAP "AUTO"
// 5-F4 LIGHT: RH FCS SPEED BK "AUTO"
// 6-F4 LIGHT: RH FCS PITCH "AUTO"
// 7-F4 LIGHT: RH FCS ROLL/YAW "AUTO"
// 10-F_FU_TK_ISOV_12_OP_A
// 11-F_FU_TK_ISOV_12_CL_B
// 12-F_MANF_ISOL_5_OP_A (actual position unknown)
// 13-F_HE_PR_VLV_B_OP_A
// 14-F_HE_PR_VLV_B_CL_A
// 15-MANF_ISOV_NO_1_CL_B
inline constexpr unsigned int SCP_FF3_IOM10_CH0_DATA = 0x004d1;// INTEGER SINGLE
// 0-F7 LIGHT: R MPS RED STATUS
// 1-A6 LIGHT: AFT MAN ROT ROLL "DISC RT"
// 2-A6 LIGHT: AFT MAN ROT ROLL "ACCEL"
// 3-A6 LIGHT: AFT MAN ROT ROLL "PULSE"
// 4-A6 LIGHT: AFT MAN ROT PITCH "DISC RT"
// 5-A6 LIGHT: AFT MAN ROT PITCH "ACCEL"
// 6-A6 LIGHT: AFT MAN ROT PITCH "PULSE"
// 7-A6 LIGHT: AFT MAN ROT YAW "DISC RT"
// 8-A6 LIGHT: AFT MAN ROT YAW "ACCEL"
// 9-A6 LIGHT: AFT MAN ROT YAW "PULSE"
// 10-A6 LIGHT: AFT MAN TRANS X "NORM"
// 11-A6 LIGHT: AFT MAN TRANS X "PULSE"
// 12-A6 LIGHT: AFT MAN TRANS X "LVLH"
// 13-A6 LIGHT: AFT MAN TRANS Y "NORM"
// 14-A6 LIGHT: AFT MAN TRANS Y "PULSE"
// 15-A6 LIGHT: AFT MAN TRANS Y "LOW Z"
inline constexpr unsigned int SCP_FF3_IOM10_CH1_DATA = 0x004d2;// INTEGER SINGLE
// 0-A6 LIGHT: AFT MAN TRANS Z "NORM"
// 1-A6 LIGHT: AFT MAN TRANS Z "PULSE"
// 2-A6 LIGHT: AFT MAN TRANS Z "HIGH"
// 3-C&W MATRIX "BACKUP C/W ALARM"
// 4-SM ALERT: TONE A CMD 3
// 5-SM ALERT: LIGHT A CMD 3
// 6-LH VENT 3 MOTOR 1/CLOSE A (CL/1A)
// 7-LH VENTS 1/2 MOTOR 1/PURGE A (PG/1A)
// 8-LH VENTS 4/7 MOTOR 1/CLOSE A (CL/1A)
// 9-LH VENTS 4/7 MOTOR 1/OPEN A (OP/1A)
// 10-RH VENT 6 MOTOR 1/CLOSE A (CL/1A)
// 11-RH VENT 6 MOTOR 1/OPEN A (OP/1A)
// 12-RH VENT 6 MOTOR 1/PRG-1 A (P1/1A)
// 13-RH VENT 6 MOTOR 1/PRG-2 A (P2/1A)
// 14-LH VENT 5 MOTOR 1/CLOSE A (CL/1A)
// 15-LH VENT 5 MOTOR 1/OPEN A (OP/1A)
inline constexpr unsigned int SCP_FF3_IOM10_CH2_DATA = 0x004d3;// INTEGER SINGLE
// 0-RJDF 2B F RCS JET F4R CMD B
// 1-RJDF 2B F RCS JET F4D CMD B
// 2-RJDF 2B F RCS JET F5L CMD B
// 3-RJDF 2B F RCS JET F5R CMD B
inline constexpr unsigned int SCP_FF3_IOM13_CH0_DATA = 0x004d4;// INTEGER SINGLE

// MDM FF4 output
// 0-RH VENT 3 MOTOR 2/OPEN B (OP/2B)
// 1-RH VENTS 1/2 MOTOR 2/OPEN B (OP/2B)
// 2-RH VENTS 1/2 MOTOR 2/PURGE B (PG/2B)
// 3-MANF_ISOV_NO_3_OP
// 4-MANF_ISOV_NO_2_CL_A
inline constexpr unsigned int SCP_FF4_IOM2_CH0_DATA = 0x004d5;// INTEGER SINGLE
// 6-LH VENT 5 MOTOR 2/CLOSE B (CL/2B)
inline constexpr unsigned int SCP_FF4_IOM2_CH1_DATA = 0x004d6;// INTEGER SINGLE
// 6-RH VENT 3 MOTOR 2/CLOSE B (CL/2B)
// 7-RH VENTS 1/2 MOTOR 2/CLOSE B (CL/2B)
// 8-RH VENTS 4/7 MOTOR 1/CLOSE B (CL/1B)
// 9-RH VENTS 4/7 MOTOR 1/OPEN B (OP/1B)
// 10-LH VENT 6 MOTOR 2/CLOSE B (CL/2B)
// 11-LH VENT 6 MOTOR 2/OPEN B (OP/2B)
// 12-LH VENT 6 MOTOR 2/PRG-1 B (P1/2B)
// 13-LH VENT 6 MOTOR 2/PRG-2 B (P2/2B)
// 15-LH VENT 5 MOTOR 2/OPEN B (OP/2B)
inline constexpr unsigned int SCP_FF4_IOM2_CH2_DATA = 0x004d7;// INTEGER SINGLE
// 0-RJDF 2A F RCS JET F3F CMD A
// 1-RJDF 2A F RCS JET F3L CMD A
// 2-RJDF 2A F RCS JET F3U CMD A
// 3-RJDF 2A F RCS JET F3D CMD A
inline constexpr unsigned int SCP_FF4_IOM5_CH0_DATA = 0x004d8;// INTEGER SINGLE
// 0-FWD EVENT TIMER: LIFT OFF TIMER RESET
inline constexpr unsigned int SCP_FF4_IOM5_CH1_DATA = 0x004d9;// INTEGER SINGLE
// 0-RH VENTS 1/2 MOTOR 2/CLOSE A (CL/2A)
// 1-RH VENTS 1/2 MOTOR 2/OPEN A (OP/2A)
// 2-RH VENT 3 MOTOR 2/OPEN A (OP/2A)
// 4-F4 LIGHT: RH FCS BODY FLAP "MAN"
// 5-F4 LIGHT: RH FCS SPEED BK "MAN"
// 6-F4 LIGHT: RH FCS PITCH "CSS"
// 7-F4 LIGHT: RH FCS ROLL/YAW "CSS"
// 15-MANF_ISOV_NO_2_CL_B
inline constexpr unsigned int SCP_FF4_IOM10_CH0_DATA = 0x004da;// INTEGER SINGLE
// 3-C&W MATRIX "BACKUP C/W ALARM"
// 4-SM ALERT: TONE A CMD 4
// 5-SM ALERT: LIGHT A CMD 4
// 6-RH VENT 3 MOTOR 2/CLOSE A (CL/2A)
// 7-RH VENTS 1/2 MOTOR 2/PURGE A (PG/2A)
// 8-RH VENTS 4/7 MOTOR 1/CLOSE A (CL/1A)
// 9-RH VENTS 4/7 MOTOR 1/OPEN A (OP/1A)
// 10-LH VENT 6 MOTOR 2/CLOSE A (CL/2A)
// 11-LH VENT 6 MOTOR 2/OPEN A (OP/2A)
// 12-LH VENT 6 MOTOR 2/PRG-1 A (P1/2A)
// 13-LH VENT 6 MOTOR 2/PRG-2 A (P2/2A)
// 14-LH VENT 5 MOTOR 2/CLOSE A (CL/2A)
// 15-LH VENT 5 MOTOR 2/OPEN A (OP/2A)
inline constexpr unsigned int SCP_FF4_IOM10_CH2_DATA = 0x004db;// INTEGER SINGLE
// 0-RJDF 2A F RCS JET F3F CMD B
// 1-RJDF 2A F RCS JET F3L CMD B
// 2-RJDF 2A F RCS JET F3U CMD B
// 3-RJDF 2A F RCS JET F3D CMD B
inline constexpr unsigned int SCP_FF4_IOM13_CH0_DATA = 0x004dc;// INTEGER SINGLE

// MDM FA1 output
// 0-RJDA 1B L RCS JET L1A CMD A
// 1-RJDA 1B L RCS JET L1L CMD A
// 2-RJDA 1B L RCS JET L1U CMD A
// 3-RJDA 1B R RCS JET R1A CMD A
// 4-RJDA 1B R RCS JET R1R CMD A
// 5-RJDA 1B R RCS JET R1U CMD A
// 6-RJDA 1B VERN JET L5D CMD A
// 7-RJDA 1B VERN JET L5L CMD A
inline constexpr unsigned int SCP_FA1_IOM2_CH0_DATA = 0x004dd;// INTEGER SINGLE
// 0-L_MANF_ISOV_NO_3_CL_A
// 4-LH VENTS 8/9 MOTOR 1/CLOSE A (CL/1A)
// 5-LH VENTS 8/9 MOTOR 1/OPEN A (OP/1A)
// 6-LH VENTS 8/9 MOTOR 1/PURGE A (PG/1A)
inline constexpr unsigned int SCP_FA1_IOM7_CH0_DATA = 0x004de;// INTEGER SINGLE
// 1-R_OMS_VLV_1_COIL_2_CMD
// 2-L_OMS_VAP_ISOV_1_OP
// 3-L_OMS_FU_TK_ISOV_A_OP
// 4-L_OMS_FU_TK_ISOV_A_CL
// 5-L_OMS_OX_TK_ISOV_A_OP
// 6-L_OMS_OX_TK_ISOV_A_CL
// 7-L_OMS_FU_XFD_V_A_OP
// 8-L_OMS_FU_XFD_V_A_CL
// 9-R_OMS_FU_XFD_V_A_OP
// 10-R_OMS_FU_XFD_V_A_CL
// 11-L_OMS_OX_XFD_V_A_OP
// 12-L_OMS_OX_XFD_V_A_CL
// 13-R_OMS_OX_XFD_V_A_OP
// 14-R_OMS_OX_XFD_V_A_CL
inline constexpr unsigned int SCP_FA1_IOM7_CH1_DATA = 0x004df;// INTEGER SINGLE
// 0-L_RCS_XFD_345_CL
// 1-L_RCS_XFD_345_OP
// 2-L_FU_TK_ISOV_12_CL_B
// 3-L_FU_TK_ISOV_12_OP_B
// 4-L_OX_TK_ISOV_12_CL_B
// 5-L_OX_TK_ISOV_12_OP_B
// 6-L_MANF_ISOV_NO_1_OP
// 8-R_MANF_ISOV_NO_3_CL_B
// 9-L_HE_PRESS_V_A_OP_A
// 10-L_HE_PRESS_V_A_CL_A
// 11-L_MANF_ISO_5_OPEN_A
inline constexpr unsigned int SCP_FA1_IOM7_CH2_DATA = 0x004e0;// INTEGER SINGLE
// 0-RJDA 1B L RCS JET L1A CMD B
// 1-RJDA 1B L RCS JET L1L CMD B
// 2-RJDA 1B L RCS JET L1U CMD B
// 3-RJDA 1B R RCS JET R1A CMD B
// 4-RJDA 1B R RCS JET R1R CMD B
// 5-RJDA 1B R RCS JET R1U CMD B
// 6-RJDA 1B VERN JET L5D CMD B
// 7-RJDA 1B VERN JET L5L CMD B
inline constexpr unsigned int SCP_FA1_IOM10_CH0_DATA = 0x004e1;// INTEGER SINGLE
// 4-L OMS ENG PGE V1 OP
inline constexpr unsigned int SCP_FA1_IOM12_CH1_DATA = 0x004e2;// INTEGER SINGLE
// 1-R_MANF_ISOV_NO_3_CL_A
// 3-LH VENTS 8/9 MOTOR 1/CLOSE B (CL/1B)
// 4-LH VENTS 8/9 MOTOR 1/OPEN B (OP/1B)
// 5-LH VENTS 8/9 MOTOR 1/PURGE B (PG/1B)
inline constexpr unsigned int SCP_FA1_IOM15_CH0_DATA = 0x004e3;// INTEGER SINGLE
// 1-L_OMS_VLV_1_COIL_2_CMD
// 2-L_OMS_HE_ISOV_A_OP
// 5-L_OMS_TK_V_B_OP
// 6-L_OMS_TK_V_B_CL
// 11-L_OMS_XFD_B_OP
// 12-L_OMS_XFD_B_CL
// 13-R_OMS_XFD_B_OP
// 14-R_OMS_XFD_B_CL
inline constexpr unsigned int SCP_FA1_IOM15_CH1_DATA = 0x004e4;// INTEGER SINGLE
// 0-R_RCS_OX_XFD_345_CL
// 1-R_RCS_OX_XFD_345_OP
// 2-R_RCS_FU_XFD_345_CL
// 3-R_RCS_FU_XFD_345_OP
// 4-R_TK_ISOV_12_CL_A
// 5-R_TK_ISOV_12_OP_A
// 6-R_MANF_ISOV_NO_1_OP
// 8-L_MANF_ISOV_NO_3_CL_B
// 9-R_HE_PRESS_V_A_OP_A
// 10-R_HE_PRESS_V_A_CL_A
// 11-R_MANF_ISO_5_CLOSE_A
inline constexpr unsigned int SCP_FA1_IOM15_CH2_DATA = 0x004e5;// INTEGER SINGLE

// MDM FA2 output
// 0-RJDA 2B L RCS JET L3A CMD A
// 1-RJDA 2B L RCS JET L3L CMD A
// 2-RJDA 2B L RCS JET L3D CMD A
// 3-RJDA 2B R RCS JET R3A CMD A
// 4-RJDA 2B R RCS JET R3R CMD A
// 5-RJDA 2B R RCS JET R3D CMD A
// 6-RJDA 2B VERN JET R5R CMD A
// 7-RJDA 2B VERN JET R5D CMD A
inline constexpr unsigned int SCP_FA2_IOM2_CH0_DATA = 0x004e6;// INTEGER SINGLE
// 0-L_MANF_ISOV_NO_1_CL_A
// 4-RH VENTS 8/9 MOTOR 2/CLOSE A (CL/2A)
// 5-RH VENTS 8/9 MOTOR 2/OPEN A (OP/2A)
// 6-RH VENTS 8/9 MOTOR 2/PURGE A (PG/2A)
inline constexpr unsigned int SCP_FA2_IOM7_CH0_DATA = 0x004e7;// INTEGER SINGLE
// 1-R_OMS_VLV_2_COIL_2_CMD
// 2-L_OMS_VAP_ISOV_2_OP
// 5-L_OMS_TK_V_A_OP
// 6-L_OMS_TK_V_A_CL
// 11-L_OMS_XFD_A_OP
// 12-L_OMS_XFD_A_CL
// 13-R_OMS_XFD_A_OP
// 14-R_OMS_XFD_A_CL
inline constexpr unsigned int SCP_FA2_IOM7_CH1_DATA = 0x004e8;// INTEGER SINGLE
// 0-L_RCS_OX_XFD_345_CL
// 1-L_RCS_OX_XFD_345_OP
// 2-L_RCS_FU_XFD_345_CL
// 3-L_RCS_FU_XFD_345_OP
// 4-L_TK_ISOV_12_CL_A
// 5-L_TK_ISOV_12_OP_A
// 6-L_MANF_ISOV_NO_3_OP
// 8-R_MANF_ISOV_NO_1_CL_B
// 9-L_HE_PRESS_V_B_OP_A
// 10-L_HE_PRESS_V_B_CL_A
// 11-L_MANF_ISO_5_CLOSE_A
inline constexpr unsigned int SCP_FA2_IOM7_CH2_DATA = 0x004e9;// INTEGER SINGLE
// 0-RJDA 2B L RCS JET L3A CMD B
// 1-RJDA 2B L RCS JET L3L CMD B
// 2-RJDA 2B L RCS JET L3D CMD B
// 3-RJDA 2B R RCS JET R3A CMD B
// 4-RJDA 2B R RCS JET R3R CMD B
// 5-RJDA 2B R RCS JET R3D CMD B
// 6-RJDA 2B VERN JET R5R CMD B
// 7-RJDA 2B VERN JET R5D CMD B
inline constexpr unsigned int SCP_FA2_IOM10_CH0_DATA = 0x004ea;// INTEGER SINGLE
// 4-L OMS ENG PGE V2 OP
inline constexpr unsigned int SCP_FA2_IOM12_CH1_DATA = 0x004eb;// INTEGER SINGLE
// 1-R_MANF_ISOV_NO_1_CL_A
// 3-RH VENTS 8/9 MOTOR 2/CLOSE B (CL/2B)
// 4-RH VENTS 8/9 MOTOR 2/OPEN B (OP/2B)
// 5-RH VENTS 8/9 MOTOR 2/PURGE B (PG/2B)
inline constexpr unsigned int SCP_FA2_IOM15_CH0_DATA = 0x004ec;// INTEGER SINGLE
// 1-L_OMS_VLV_2_COIL_2_CMD
// 2-L_OMS_HE_ISOV_B_OP
// 3-L_OMS_FU_TK_ISOV_B_OP
// 4-L_OMS_FU_TK_ISOV_B_CL
// 5-L_OMS_OX_TK_ISOV_B_OP
// 6-L_OMS_OX_TK_ISOV_B_CL
// 7-L_OMS_FU_XFD_V_B_OP
// 8-L_OMS_FU_XFD_V_B_CL
// 9-R_OMS_FU_XFD_V_B_OP
// 10-R_OMS_FU_XFD_V_B_CL
// 11-L_OMS_OX_XFD_V_B_OP
// 12-L_OMS_OX_XFD_V_B_CL
// 13-R_OMS_OX_XFD_V_B_OP
// 14-R_OMS_OX_XFD_V_B_CL
inline constexpr unsigned int SCP_FA2_IOM15_CH1_DATA = 0x004ed;// INTEGER SINGLE
// 0-R_RCS_XFD_345_CL
// 1-R_RCS_XFD_345_OP
// 2-R_FU_TK_ISOV_12_CL_B
// 3-R_FU_TK_ISOV_12_OP_B
// 4-R_OX_TK_ISOV_12_CL_B
// 5-R_OX_TK_ISOV_12_OP_B
// 6-R_MANF_ISOV_NO_3_OP
// 8-L_MANF_ISOV_NO_1_CL_B
// 9-R_HE_PRESS_V_B_OP_A
// 10-R_HE_PRESS_V_B_CL_A
// 11-R_MANF_ISO_5_OPEN_A
inline constexpr unsigned int SCP_FA2_IOM15_CH2_DATA = 0x004ee;// INTEGER SINGLE

// MDM FA3 output
// 0-RJDA 1A L RCS JET L2L CMD A
// 1-RJDA 1A L RCS JET L2U CMD A
// 2-RJDA 1A L RCS JET L2D CMD A
// 3-RJDA 1A R RCS JET R2R CMD A
// 4-RJDA 1A R RCS JET R2U CMD A
// 5-RJDA 1A R RCS JET R2D CMD A
inline constexpr unsigned int SCP_FA3_IOM2_CH0_DATA = 0x004ef;// INTEGER SINGLE
// 0-L_MANF_ISOV_NO_4_CL_A
// 4-RH VENTS 8/9 MOTOR 1/CLOSE A (CL/1A)
// 5-RH VENTS 8/9 MOTOR 1/OPEN A (OP/1A)
// 6-RH VENTS 8/9 MOTOR 1/PURGE A (PG/1A)
inline constexpr unsigned int SCP_FA3_IOM7_CH0_DATA = 0x004f0;// INTEGER SINGLE
// 1-R_OMS_VLV_1_COIL_1_CMD
// 2-R_OMS_VAP_ISOV_1_OP
// 5-R_OMS_TK_V_A_OP
// 6-R_OMS_TK_V_A_CL
inline constexpr unsigned int SCP_FA3_IOM7_CH1_DATA = 0x004f1;// INTEGER SINGLE
// 0-L_RCS_OX_XFD_12_CL
// 1-L_RCS_OX_XFD_12_OP
// 2-L_FU_TK_ISOV_345_A_CL
// 3-L_FU_TK_ISOV_345_A_OP
// 4-L_OX_TK_ISOV_345_A_CL
// 5-L_OX_TK_ISOV_345_A_OP
// 6-L_MANF_ISOV_NO_2_OP
// 8-R_MANF_ISOV_NO_4_CL_B
// 9-R_MANF_ISO_5_OPEN_B (actual position unknown)
// 10-R_MANF_ISO_5_CLOSE_B (actual position unknown)
// 11-L_MANF_ISO_5_OPEN_B (actual position unknown)
inline constexpr unsigned int SCP_FA3_IOM7_CH2_DATA = 0x004f2;// INTEGER SINGLE
// 0-RJDA 1A L RCS JET L2L CMD B
// 1-RJDA 1A L RCS JET L2U CMD B
// 2-RJDA 1A L RCS JET L2D CMD B
// 3-RJDA 1A R RCS JET R2R CMD B
// 4-RJDA 1A R RCS JET R2U CMD B
// 5-RJDA 1A R RCS JET R2D CMD B
inline constexpr unsigned int SCP_FA3_IOM10_CH0_DATA = 0x004f3;// INTEGER SINGLE
// 4-R OMS ENG PGE V1 OP
inline constexpr unsigned int SCP_FA3_IOM12_CH1_DATA = 0x004f4;// INTEGER SINGLE
// 1-R_MANF_ISOV_NO_4_CL_A
// 3-RH VENTS 8/9 MOTOR 1/CLOSE B (CL/1B)
// 4-RH VENTS 8/9 MOTOR 1/OPEN B (OP/1B)
// 5-RH VENTS 8/9 MOTOR 1/PURGE B (PG/1B)
inline constexpr unsigned int SCP_FA3_IOM15_CH0_DATA = 0x004f5;// INTEGER SINGLE
// 1-L_OMS_VLV_2_COIL_1_CMD
// 2-R_OMS_HE_ISOV_A_OP
// 3-R_OMS_FU_TK_ISOV_B_OP
// 4-R_OMS_FU_TK_ISOV_B_CL
// 5-R_OMS_OX_TK_ISOV_B_OP
// 6-R_OMS_OX_TK_ISOV_B_CL
inline constexpr unsigned int SCP_FA3_IOM15_CH1_DATA = 0x004f6;// INTEGER SINGLE
// 0-R_RCS_XFD_12_CL
// 1-R_RCS_XFD_12_OP
// 2-R_FU_TK_ISOV_345_A_CL
// 3-R_FU_TK_ISOV_345_A_OP
// 4-R_OX_TK_ISOV_345_A_CL
// 5-R_OX_TK_ISOV_345_A_OP
// 6-R_MANF_ISOV_NO_2_OP
// 8-L_MANF_ISOV_NO_4_CL_B
// 9-L_RCS_FU_XFD_12_CL
// 10-L_RCS_FU_XFD_12_OP
// 11-L_MANF_ISO_5_CLOSE_B (actual position unknown)
inline constexpr unsigned int SCP_FA3_IOM15_CH2_DATA = 0x004f7;// INTEGER SINGLE

// MDM FA4 output
// 0-RJDA 2A L RCS JET L4L CMD A
// 1-RJDA 2A L RCS JET L4U CMD A
// 2-RJDA 2A L RCS JET L4D CMD A
// 3-RJDA 2A R RCS JET R4R CMD A
// 4-RJDA 2A R RCS JET R4U CMD A
// 5-RJDA 2A R RCS JET R4D CMD A
inline constexpr unsigned int SCP_FA4_IOM2_CH0_DATA = 0x004f8;// INTEGER SINGLE
// 0-L_MANF_ISOV_NO_2_CL_A
// 4-LH VENTS 8/9 MOTOR 2/CLOSE A (CL/2A)
// 5-LH VENTS 8/9 MOTOR 2/OPEN A (OP/2A)
// 6-LH VENTS 8/9 MOTOR 2/PURGE A (PG/2A)
inline constexpr unsigned int SCP_FA4_IOM7_CH0_DATA = 0x004f9;// INTEGER SINGLE
// 1-R_OMS_VLV_2_COIL_1_CMD
// 2-R_OMS_VAP_ISOV_2_OP
// 3-R_OMS_FU_TK_ISOV_A_OP
// 4-R_OMS_FU_TK_ISOV_A_CL
// 5-R_OMS_OX_TK_ISOV_A_OP
// 6-R_OMS_OX_TK_ISOV_A_CL
inline constexpr unsigned int SCP_FA4_IOM7_CH1_DATA = 0x004fa;// INTEGER SINGLE
// 0-L_RCS_XFD_12_CL
// 1-L_RCS_XFD_12_OP
// 2-L_FU_TK_ISOV_345_B_CL
// 3-L_FU_TK_ISOV_345_B_OP
// 4-L_OX_TK_ISOV_345_B_CL
// 5-L_OX_TK_ISOV_345_B_OP
// 6-L_MANF_ISOV_NO_4_OP
// 8-R_MANF_ISOV_NO_2_CL_B
// 9-L_MANF_ISO_5_OPEN_C (actual position unknown)
// 10-L_MANF_ISO_5_CLOSE_C (actual position unknown)
// 11-R_MANF_ISO_5_OPEN_C (actual position unknown)
inline constexpr unsigned int SCP_FA4_IOM7_CH2_DATA = 0x004fb;// INTEGER SINGLE
// 0-RJDA 2A L RCS JET L4L CMD B
// 1-RJDA 2A L RCS JET L4U CMD B
// 2-RJDA 2A L RCS JET L4D CMD B
// 3-RJDA 2A R RCS JET R4R CMD B
// 4-RJDA 2A R RCS JET R4U CMD B
// 5-RJDA 2A R RCS JET R4D CMD B
inline constexpr unsigned int SCP_FA4_IOM10_CH0_DATA = 0x004fc;// INTEGER SINGLE
// 4-R OMS ENG PGE V2 OP
inline constexpr unsigned int SCP_FA4_IOM12_CH1_DATA = 0x004fd;// INTEGER SINGLE
// 1-R_MANF_ISOV_NO_2_CL_A
// 3-LH VENTS 8/9 MOTOR 2/CLOSE B (CL/2B)
// 4-LH VENTS 8/9 MOTOR 2/OPEN B (OP/2B)
// 5-LH VENTS 8/9 MOTOR 2/PURGE B (PG/2B)
inline constexpr unsigned int SCP_FA4_IOM15_CH0_DATA = 0x004fe;// INTEGER SINGLE
// 1-L_OMS_VLV_1_COIL_1_CMD
// 2-R_OMS_HE_ISOV_B_OP
// 5-R_OMS_TK_V_B_OP
// 6-R_OMS_TK_V_B_CL
inline constexpr unsigned int SCP_FA4_IOM15_CH1_DATA = 0x004ff;// INTEGER SINGLE
// 0-R_RCS_OX_XFD_12_CL
// 1-R_RCS_OX_XFD_12_OP
// 2-R_FU_TK_ISOV_345_B_CL
// 3-R_FU_TK_ISOV_345_B_OP
// 4-R_OX_TK_ISOV_345_B_CL
// 5-R_OX_TK_ISOV_345_B_OP
// 6-R_MANF_ISOV_NO_4_OP
// 8-L_MANF_ISOV_NO_2_CL_B
// 9-R_RCS_FU_XFD_12_CL
// 10-R_RCS_FU_XFD_12_OP
// 11-R_MANF_ISO_5_CLOSE_C (actual position unknown)
inline constexpr unsigned int SCP_FA4_IOM15_CH2_DATA = 0x00500;// INTEGER SINGLE

// MDM PF1 output
// 12-C&W MATRIX "BACKUP C/W ALARM"
// 13-SM ALERT: TONE B CMD 1
// 14-SM ALERT: LIGHT B CMD 1
inline constexpr unsigned int SCP_PF1_IOM2_CH0_DATA = 0x00501;// INTEGER SINGLE

// MDM PF2 output
// 12-C&W MATRIX "BACKUP C/W ALARM"
// 13-SM ALERT: TONE B CMD 2
// 14-SM ALERT: LIGHT B CMD 2
inline constexpr unsigned int SCP_PF2_IOM2_CH0_DATA = 0x00502;// INTEGER SINGLE
// 2-C&W MATRIX "PAYLOAD WARNING"
inline constexpr unsigned int SCP_PF2_IOM10_CH2_DATA = 0x00503;// INTEGER SINGLE

// Radar Altimeter
inline constexpr unsigned int SCP_RA_DATA_CDR_SEL = 0x00504;// INTEGER SINGLE
inline constexpr unsigned int SCP_RA_VALIDITY_CDR_SEL = 0x00505;// INTEGER SINGLE
inline constexpr unsigned int SCP_RA_DATA_PLT_SEL = 0x00506;// INTEGER SINGLE
inline constexpr unsigned int SCP_RA_VALIDITY_PLT_SEL = 0x00507;// INTEGER SINGLE

// DAP PBIs light command
// forward
inline constexpr unsigned int SCP_FWD_DAP_SELECT_A_LT = 0x00508;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_SELECT_B_LT = 0x00509;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_AUTO_LT = 0x0050a;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN_INRTL_LT = 0x0050b;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN_LVLH_LT = 0x0050c;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN_FREE_DFT_LT = 0x0050d;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_BLANK_LT = 0x0050e;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_X_NORM_LT = 0x0050f;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_X_PULSE_LT = 0x00510;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_LOW_Z_LT = 0x00511;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Y_NORM_LT = 0x00512;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Y_PULSE_LT = 0x00513;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Z_HIGH_LT = 0x00514;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Z_NORM_LT = 0x00515;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Z_PULSE_LT = 0x00516;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_JETS_NORM_LT = 0x00517;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_ROLL_DISC_LT = 0x00518;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_ROLL_PULSE_LT = 0x00519;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ALT_PRCS_MODE_LT = 0x0051a;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_PITCH_DISC_LT = 0x0051b;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_PITCH_PULSE_LT = 0x0051c;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_JETS_VERN_LT = 0x0051d;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_YAW_DISC_LT = 0x0051e;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_YAW_PULSE_LT = 0x0051f;// INTEGER SINGLE
// aft
inline constexpr unsigned int SCP_AFT_DAP_SELECT_A_LT = 0x00520;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_SELECT_B_LT = 0x00521;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_AUTO_LT = 0x00522;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN_INRTL_LT = 0x00523;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN_LVLH_LT = 0x00524;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN_FREE_DFT_LT = 0x00525;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_BLANK_LT = 0x00526;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_X_NORM_LT = 0x00527;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_X_PULSE_LT = 0x00528;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_LOW_Z_LT = 0x00529;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Y_NORM_LT = 0x0052a;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Y_PULSE_LT = 0x0052b;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Z_HIGH_LT = 0x0052c;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Z_NORM_LT = 0x0052d;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Z_PULSE_LT = 0x0052e;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_JETS_NORM_LT = 0x0052f;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_ROLL_DISC_LT = 0x00530;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_ROLL_PULSE_LT = 0x00531;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ALT_PRCS_MODE_LT = 0x00532;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_PITCH_DISC_LT = 0x00533;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_PITCH_PULSE_LT = 0x00534;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_JETS_VERN_LT = 0x00535;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_YAW_DISC_LT = 0x00536;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_YAW_PULSE_LT = 0x00537;// INTEGER SINGLE

// TAEM parameters
// maximum shuttle orbiter weight [slugs]
inline constexpr unsigned int SCP_WT_GS1 = 0x00538;// SCALAR DOUBLE
// minimum RPRED to issue OHALRT [ft]
inline constexpr unsigned int SCP_RMOH = 0x0053a;// SCALAR DOUBLE
// HAC turn angle [deg]
inline constexpr unsigned int SCP_PSHA = 0x0053c;// SCALAR DOUBLE
// HAC radius [ft]
inline constexpr unsigned int SCP_RTURN = 0x0053e;// SCALAR DOUBLE
// R/L cone indicator [1]
inline constexpr unsigned int SCP_YSGN = 0x00540;// SCALAR DOUBLE
// PSHA reset value [deg]
inline constexpr unsigned int SCP_PSHARS = 0x00542;// SCALAR DOUBLE
// initial HAC spiral turn radius on final [ft]
inline constexpr unsigned int SCP_RF0 = 0x00544;// SCALAR DOUBLE
// linear term in spiral radius eqn. [ft/deg]
inline constexpr unsigned int SCP_R1 = 0x00546;// SCALAR DOUBLE
// quadratic term in spiral radius eqn. [ft/deg]
inline constexpr unsigned int SCP_R2 = 0x00548;// SCALAR DOUBLE

// Autoland parameters
// pullup circle radius (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_AL_R = 0x0054a;// MATRIX(2,2) DOUBLE
// pullup circle center (x) (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_X_K = 0x00552;// MATRIX(2,2) DOUBLE
// pullup circle center (h) (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_H_K = 0x0055a;// MATRIX(2,2) DOUBLE
// exponential/circle tangency range (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_X_EXP = 0x00562;// MATRIX(2,2) DOUBLE
// exponential decay (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_H_DECAY = 0x0056a;// MATRIX(2,2) DOUBLE
// exponential decay factor [1]
inline constexpr unsigned int SCP_SIGMA = 0x00572;// SCALAR DOUBLE
// steep glideslop angle (indexed by IGS) [deg]
inline constexpr unsigned int SCP_GAMMA_REF_1 = 0x00574;// VECTOR(2) DOUBLE
// shallow glideslop angle [deg]
inline constexpr unsigned int SCP_GAMMA_REF_2 = 0x00578;// SCALAR DOUBLE
// steep glide slope aim point (indexed by IGI) [ft]
inline constexpr unsigned int SCP_X_ZERO = 0x0057a;// VECTOR(2) DOUBLE
// shallow glide slope aim point [ft]
inline constexpr unsigned int SCP_X_AIM = 0x0057e;// SCALAR DOUBLE
// open-loop pull-up altitude [ft]
inline constexpr unsigned int SCP_H_FLARE = 0x00580;// SCALAR DOUBLE
// closed-loop pull-up altitude [ft]
inline constexpr unsigned int SCP_H_CLOOP = 0x00582;// SCALAR DOUBLE

// runway approach mode (1-overhead; 2-strait-in)
inline constexpr unsigned int SCP_OVHD = 0x00584;// INTEGER SINGLE
// glide slope (1-light; 2-heavy)
inline constexpr unsigned int SCP_IGS = 0x00585;// INTEGER SINGLE
// aimpoint (1-nom; 2-close-in)
inline constexpr unsigned int SCP_IGI = 0x00586;// INTEGER SINGLE
// runway ID (1-pri; 2-sec)
inline constexpr unsigned int SCP_RWID = 0x00587;// INTEGER SINGLE
// previous runway ID (1-pri; 2-sec)
inline constexpr unsigned int SCP_RWID0 = 0x00588;// INTEGER SINGLE
// landing site ID [1,45]
inline constexpr unsigned int SCP_LSID = 0x00589;// INTEGER SINGLE

// speedbrake logic select (1-nom; 2-short; 3-ELS)
inline constexpr unsigned int SCP_SB_SEL = 0x0058a;// INTEGER SINGLE

// pri runway name
inline constexpr unsigned int SCP_PRI_ID = 0x0058b;// CHARACTER(5)
// pri runway heading [deg]
inline constexpr unsigned int SCP_PRI_HDG = 0x00590;// SCALAR DOUBLE
// pri runway pos (greenwich=ECEF) [ft]
inline constexpr unsigned int SCP_PRI_POS = 0x00592;// VECTOR(3) DOUBLE
// pri greenwich(=ECEF)-to-runway matrix [ft]
inline constexpr unsigned int SCP_PRI_G2R = 0x00598;// MATRIX(3,3) DOUBLE
// pri runway length [ft]
inline constexpr unsigned int SCP_PRI_LEN = 0x005aa;// INTEGER SINGLE
// sec runway name
inline constexpr unsigned int SCP_SEC_ID = 0x005ab;// CHARACTER(5)
// sec runway heading [deg]
inline constexpr unsigned int SCP_SEC_HDG = 0x005b0;// SCALAR DOUBLE
// sec runway pos (greenwich=ECEF) [ft]
inline constexpr unsigned int SCP_SEC_POS = 0x005b2;// VECTOR(3) DOUBLE
// sec greenwich(=ECEF)-to-runway matrix [ft]
inline constexpr unsigned int SCP_SEC_G2R = 0x005b8;// MATRIX(3,3) DOUBLE
// sec runway length [ft]
inline constexpr unsigned int SCP_SEC_LEN = 0x005ca;// INTEGER SINGLE

// Landing SOP
inline constexpr unsigned int SCP_WOWLON = 0x005cb;// INTEGER SINGLE
inline constexpr unsigned int SCP_FLATTURN = 0x005cc;// INTEGER SINGLE
inline constexpr unsigned int SCP_ROLLOUT = 0x005cd;// INTEGER SINGLE
inline constexpr unsigned int SCP_GSENBL = 0x005ce;// INTEGER SINGLE
inline constexpr unsigned int SCP_HUD_WOWLON = 0x005cf;// INTEGER SINGLE
inline constexpr unsigned int SCP_HUD_ROLLOUT = 0x005d0;// INTEGER SINGLE

// Aerojet DAP FCS
// AerojetDAP FCS pitch control (1-AUTO; 2-CSS)
inline constexpr unsigned int SCP_AEROJET_FCS_PITCH = 0x005d1;// INTEGER SINGLE
// AerojetDAP FCS roll control (1-AUTO; 2-CSS)
inline constexpr unsigned int SCP_AEROJET_FCS_ROLL = 0x005d2;// INTEGER SINGLE
// AerojetDAP FCS speedbrake control (1-AUTO; 2-CDR; 3-PLT)
inline constexpr unsigned int SCP_AEROJET_FCS_SB = 0x005d3;// INTEGER SINGLE
// AerojetDAP body flap control (1-AUTO; 2-CSS)
inline constexpr unsigned int SCP_AEROJET_FCS_BF = 0x005d4;// INTEGER SINGLE
// number of RCS roll jets to fire (+right, -left) [1]
inline constexpr unsigned int SCP_UXCMD = 0x005d5;// INTEGER SINGLE
// number of RCS pitch jets to fire (+up, -down) [1]
inline constexpr unsigned int SCP_UYCMD = 0x005d6;// INTEGER SINGLE
// number of RCS yaw jets to fire (+right, -left) [1]
inline constexpr unsigned int SCP_UZCMD = 0x005d7;// INTEGER SINGLE
// aileron trim [deg]
inline constexpr unsigned int SCP_DATRIM = 0x005d8;// SCALAR DOUBLE
// rudder trim [deg]
inline constexpr unsigned int SCP_DRTRIM = 0x005da;// SCALAR DOUBLE
// NY trim [g]
inline constexpr unsigned int SCP_DRTI = 0x005dc;// SCALAR DOUBLE
// NZ error [g]
inline constexpr unsigned int SCP_NZERR = 0x005de;// SCALAR DOUBLE
// bank error [deg]
inline constexpr unsigned int SCP_BANKERR = 0x005e0;// SCALAR DOUBLE
// wraparound DAP mode (0=INH, 1=ENA, 2=ACT)
inline constexpr unsigned int SCP_WRAP = 0x005e2;// INTEGER SINGLE
// elevator command [deg]
inline constexpr unsigned int SCP_DECC = 0x005e3;// SCALAR DOUBLE
// aileron command [deg]
inline constexpr unsigned int SCP_DAC = 0x005e5;// SCALAR DOUBLE
// rudder command [deg]
inline constexpr unsigned int SCP_DRC = 0x005e7;// SCALAR DOUBLE
// speedbrake command [deg]
inline constexpr unsigned int SCP_DSBC = 0x005e9;// SCALAR DOUBLE
// NWS command [deg]
inline constexpr unsigned int SCP_DNWC = 0x005eb;// SCALAR DOUBLE
// Entry Mode switch "Low Gain" selected
inline constexpr unsigned int SCP_SEL_L_GAIN = 0x005ed;// INTEGER SINGLE
// Entry Mode switch "No Yaw Jet" selected
inline constexpr unsigned int SCP_SEL_NO_Y_JET = 0x005ee;// INTEGER SINGLE
// Entry Mode switch override
inline constexpr unsigned int SCP_ENTRY_SW_OVERRIDE = 0x005ef;// INTEGER SINGLE

// A/L UPP
// geodetic altitude of vehicle center of mass above rw [ft]
inline constexpr unsigned int SCP_H = 0x005f0;// SCALAR DOUBLE
// negative z component of velocity in topodetic coordinates [fps]
inline constexpr unsigned int SCP_HDOT = 0x005f2;// SCALAR DOUBLE
// true airspeed [fps]
inline constexpr unsigned int SCP_V_T = 0x005f4;// SCALAR DOUBLE
// equivalent? airspeed [fps]
inline constexpr unsigned int SCP_V_I = 0x005f6;// SCALAR DOUBLE
// equivalent airspeed [knots]
inline constexpr unsigned int SCP_KEAS = 0x005f8;// SCALAR DOUBLE
// topodetic horizontal component of earth relative velocity [fps]
inline constexpr unsigned int SCP_VG = 0x005fa;// SCALAR DOUBLE
// vehicle position in runway coordinates [ft]
inline constexpr unsigned int SCP_X = 0x005fc;// SCALAR DOUBLE
inline constexpr unsigned int SCP_Y = 0x005fe;// SCALAR DOUBLE
inline constexpr unsigned int SCP_Z = 0x00600;// SCALAR DOUBLE
// vehicle velocity in runway coordinates [fps]
inline constexpr unsigned int SCP_XDOT = 0x00602;// SCALAR DOUBLE
inline constexpr unsigned int SCP_YDOT = 0x00604;// SCALAR DOUBLE
// heading [deg]
inline constexpr unsigned int SCP_HDG = 0x00606;// SCALAR DOUBLE
// topodetic earth relative flight-path angle [deg]
inline constexpr unsigned int SCP_GAMMA = 0x00608;// SCALAR DOUBLE
// roll [deg]
inline constexpr unsigned int SCP_PHI = 0x0060a;// SCALAR DOUBLE
// cosine of body roll euler angle [1]
inline constexpr unsigned int SCP_COSPHI = 0x0060c;// SCALAR DOUBLE
// sine of body roll euler angle [1]
inline constexpr unsigned int SCP_SINPHI = 0x0060e;// SCALAR DOUBLE
// tangent of body roll euler angle [1]
inline constexpr unsigned int SCP_TANPHI = 0x00610;// SCALAR DOUBLE
// cosine of angle of attack [1]
inline constexpr unsigned int SCP_COSALF = 0x00612;// SCALAR DOUBLE
// sine of angle of attack [1]
inline constexpr unsigned int SCP_SINALF = 0x00614;// SCALAR DOUBLE
// pitch [deg]
inline constexpr unsigned int SCP_THETA = 0x00616;// SCALAR DOUBLE
// cosine of theta [1]
inline constexpr unsigned int SCP_COSTH = 0x00618;// SCALAR DOUBLE
// sine of theta [1]
inline constexpr unsigned int SCP_SINTH = 0x0061a;// SCALAR DOUBLE
// angle-of-attack [deg]
inline constexpr unsigned int SCP_ALPHA = 0x0061c;// SCALAR DOUBLE
// sideslip [deg]
inline constexpr unsigned int SCP_BETA = 0x0061e;// SCALAR DOUBLE
// dynamic pressure [psf]
inline constexpr unsigned int SCP_QBAR = 0x00620;// SCALAR DOUBLE
// lateral acceleration [g]
inline constexpr unsigned int SCP_NY = 0x00622;// SCALAR DOUBLE
// normal acceleration [g]
inline constexpr unsigned int SCP_NZ = 0x00624;// SCALAR DOUBLE
// orbiter mass [slugs]
inline constexpr unsigned int SCP_WEIGHT = 0x00626;// SCALAR DOUBLE
// body roll rate [deg/s]
inline constexpr unsigned int SCP_P = 0x00628;// SCALAR DOUBLE
// body pitch rate [deg/s]
inline constexpr unsigned int SCP_Q = 0x0062a;// SCALAR DOUBLE
// body yaw rate [deg/s]
inline constexpr unsigned int SCP_R = 0x0062c;// SCALAR DOUBLE

// TAEM UPP
// mach number [1]
inline constexpr unsigned int SCP_MACH = 0x0062e;// SCALAR DOUBLE
// course with respect to centerline [deg]
inline constexpr unsigned int SCP_PSD = 0x00630;// SCALAR DOUBLE

// Entry UPP
// vehicle position in ECEF [ft]
inline constexpr unsigned int SCP_ECEF_POS = 0x00632;// VECTOR(3) DOUBLE
// vehicle velocity in ECEF [fps]
inline constexpr unsigned int SCP_ECEF_VEL = 0x00638;// VECTOR(3) DOUBLE
// current relative velocity [fps]
inline constexpr unsigned int SCP_VE = 0x0063e;// SCALAR DOUBLE
// current inertial velocity [fps]
inline constexpr unsigned int SCP_VI = 0x00640;// SCALAR DOUBLE
// current drag acceleration [fps^2]
inline constexpr unsigned int SCP_DRAG = 0x00642;// SCALAR DOUBLE
// current lift/drag ratio [1]
inline constexpr unsigned int SCP_LOD = 0x00644;// SCALAR DOUBLE
// current load factor [fps^2]
inline constexpr unsigned int SCP_XLFAC = 0x00646;// SCALAR DOUBLE

// EGRT output
// azimuth error [rad]
inline constexpr unsigned int SCP_DELAZ = 0x00648;// SCALAR DOUBLE
// range to target [NM]
inline constexpr unsigned int SCP_TRANG = 0x0064a;// SCALAR DOUBLE

// Autoland guidance output
// autoland phase counter
inline constexpr unsigned int SCP_PMODE = 0x0064c;// INTEGER SINGLE
// FSGS phase counter
inline constexpr unsigned int SCP_FMODE = 0x0064d;// INTEGER SINGLE
// autoland NZ command [g]
inline constexpr unsigned int SCP_NZ_CMD = 0x0064e;// SCALAR DOUBLE
// autoland roll angle command [deg]
inline constexpr unsigned int SCP_PHIC_AL = 0x00650;// SCALAR DOUBLE
// autoland yaw rate command post WOWLON
inline constexpr unsigned int SCP_RC = 0x00652;// SCALAR DOUBLE
// autoland speedbrake command [deg]
inline constexpr unsigned int SCP_DSBC_AL = 0x00654;// SCALAR DOUBLE
// body flap retract command
inline constexpr unsigned int SCP_RETRACT_BF = 0x00656;// INTEGER SINGLE
// altitude error [ft]
inline constexpr unsigned int SCP_HERR = 0x00657;// SCALAR DOUBLE

// TAEM guidance output
// heading error to HAC tangency [deg]
inline constexpr unsigned int SCP_DPSAC = 0x00659;// SCALAR DOUBLE
// predicted range to rw [ft]
inline constexpr unsigned int SCP_RPRED = 0x0065b;// SCALAR DOUBLE
// commanded body normal load factor increment from equilibrium [g]
inline constexpr unsigned int SCP_NZC = 0x0065d;// SCALAR DOUBLE
// speedbrake angle command (hinge line) [deg]
inline constexpr unsigned int SCP_DSBC_AT = 0x0065f;// SCALAR DOUBLE
// roll angle command
inline constexpr unsigned int SCP_PHIC_AT = 0x00661;// SCALAR DOUBLE
// minimum entry point flag
inline constexpr unsigned int SCP_MEP = 0x00663;// INTEGER SINGLE
// TAEM phase counter [1]
inline constexpr unsigned int SCP_IPHASE = 0x00664;// INTEGER SINGLE
// TAEM end flag
inline constexpr unsigned int SCP_TG_END = 0x00665;// INTEGER SINGLE
// current HAC final size [ft]
inline constexpr unsigned int SCP_RF = 0x00666;// SCALAR DOUBLE
// HAC X position [ft]
inline constexpr unsigned int SCP_XHAC = 0x00668;// SCALAR DOUBLE
// distance from OV to HAC center [ft]
inline constexpr unsigned int SCP_RCIR = 0x0066a;// SCALAR DOUBLE
// energy per unit weight [ft]
inline constexpr unsigned int SCP_EOW = 0x0066c;// SCALAR DOUBLE
// reference energy [ft]
inline constexpr unsigned int SCP_EN = 0x0066e;// SCALAR DOUBLE
// E/W to start S-turn [ft]
inline constexpr unsigned int SCP_ES = 0x00670;// SCALAR DOUBLE
// E/W to switch to MEP [ft]
inline constexpr unsigned int SCP_EMEP = 0x00672;// SCALAR DOUBLE
// E/W to downmode to STRN [ft]
inline constexpr unsigned int SCP_EMOH = 0x00674;// SCALAR DOUBLE
// altitude error from reference profile [ft]
inline constexpr unsigned int SCP_HERROR = 0x00676;// SCALAR DOUBLE
// heading to HAC center [deg]
inline constexpr unsigned int SCP_PSC = 0x00678;// SCALAR DOUBLE
// estimated time to HAC [sec]
inline constexpr unsigned int SCP_P2TRNT = 0x0067a;// SCALAR DOUBLE
// "OTT ST IN" indication
inline constexpr unsigned int SCP_OTT_ST_IN = 0x0067c;// INTEGER SINGLE
// "SW TO MEP" indication
inline constexpr unsigned int SCP_SW_TO_MEP = 0x0067d;// INTEGER SINGLE

// Entry guidance output
// angle-of-attack command [deg]
inline constexpr unsigned int SCP_ALPCMD = 0x0067e;// SCALAR DOUBLE
// drag reference [fps^2]
inline constexpr unsigned int SCP_DREFP = 0x00680;// SCALAR DOUBLE
// roll angle command about body axis [deg]
inline constexpr unsigned int SCP_ROLLCMD = 0x00682;// SCALAR DOUBLE
// roll ref [deg]
inline constexpr unsigned int SCP_ROLLREF = 0x00684;// SCALAR DOUBLE
// altitude rate reference [fps]
inline constexpr unsigned int SCP_RDTREF = 0x00686;// SCALAR DOUBLE
// derivative of range wrt drag [NM/fps^2]
inline constexpr unsigned int SCP_DRDD = 0x00688;// SCALAR DOUBLE
// Rdot feedback term [fps]
inline constexpr unsigned int SCP_DLRDOT = 0x0068a;// SCALAR DOUBLE
// maximum heading error absolute value [rad]
inline constexpr unsigned int SCP_YL = 0x0068c;// SCALAR DOUBLE
// scheduled angle of attack [deg]
inline constexpr unsigned int SCP_ACMD1 = 0x0068e;// SCALAR DOUBLE
// entry guidance subphase counter
inline constexpr unsigned int SCP_ISLECT = 0x00690;// INTEGER SINGLE
// Entry guidance end flag
inline constexpr unsigned int SCP_EG_END = 0x00691;// INTEGER SINGLE

// aerosurface position feedback
// left outboard elevon pos [deg]
inline constexpr unsigned int SCP_LOB_ELVN_POS_FDBK = 0x00692;// SCALAR DOUBLE
// left inboard elevon pos [deg]
inline constexpr unsigned int SCP_LIB_ELVN_POS_FDBK = 0x00694;// SCALAR DOUBLE
// right inboard elevon pos [deg]
inline constexpr unsigned int SCP_RIB_ELVN_POS_FDBK = 0x00696;// SCALAR DOUBLE
// right outboard elevon pos [deg]
inline constexpr unsigned int SCP_ROB_ELVN_POS_FDBK = 0x00698;// SCALAR DOUBLE
// elevator pos [deg]
inline constexpr unsigned int SCP_DEFB = 0x0069a;// SCALAR DOUBLE
// aileron pos [deg]
inline constexpr unsigned int SCP_DAFB = 0x0069c;// SCALAR DOUBLE
// body flap pos [deg]
inline constexpr unsigned int SCP_DBFOFB = 0x0069e;// SCALAR DOUBLE
// rudder pos [deg]
inline constexpr unsigned int SCP_DRFB = 0x006a0;// SCALAR DOUBLE
// Speedbrake pos [deg]
inline constexpr unsigned int SCP_DSBFB_DEG = 0x006a2;// SCALAR DOUBLE
// Speedbrake pos [%]
inline constexpr unsigned int SCP_DSBFB_PCT = 0x006a4;// SCALAR DOUBLE
// speedbrake increment [deg]
inline constexpr unsigned int SCP_DSBPC = 0x006a6;// SCALAR DOUBLE

// Aerosurface command
// left outboard elevon command [deg]
inline constexpr unsigned int SCP_ELOC = 0x006a8;// SCALAR DOUBLE
// left inboard elevon command [deg]
inline constexpr unsigned int SCP_ELIC = 0x006aa;// SCALAR DOUBLE
// right inboard elevon command [deg]
inline constexpr unsigned int SCP_ERIC = 0x006ac;// SCALAR DOUBLE
// right outboard elevon command [deg]
inline constexpr unsigned int SCP_EROC = 0x006ae;// SCALAR DOUBLE
// body flap command [deg]
inline constexpr unsigned int SCP_DBFRC = 0x006b0;// SCALAR DOUBLE
// rudder command [deg]
inline constexpr unsigned int SCP_RUDDER_CMD = 0x006b2;// SCALAR DOUBLE
// speedbrake command [deg]
inline constexpr unsigned int SCP_SPEED_BRAKE_CMD = 0x006b4;// SCALAR DOUBLE

// Speedbrake AUTO command [deg]
inline constexpr unsigned int SCP_SB_AUTO_CMD = 0x006b6;// SCALAR DOUBLE

// HUD
// runway to go [ft]
inline constexpr unsigned int SCP_RWTOGO = 0x006b8;// SCALAR DOUBLE
// max deceleration [fps^2]
inline constexpr unsigned int SCP_HUDMAXDECEL = 0x006ba;// SCALAR DOUBLE

// Trim Switch positions
inline constexpr unsigned int SCP_LH_RHC_TRIM_INHIBIT = 0x006bc;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_TRIM_INHIBIT = 0x006bd;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_PLUS_PITCH_TRIM = 0x006be;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_MINUS_PITCH_TRIM = 0x006bf;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_PLUS_ROLL_TRIM = 0x006c0;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_MINUS_ROLL_TRIM = 0x006c1;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_PLUS_PITCH_TRIM = 0x006c2;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_MINUS_PITCH_TRIM = 0x006c3;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_PLUS_ROLL_TRIM = 0x006c4;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_MINUS_ROLL_TRIM = 0x006c5;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_PLUS_PITCH_TRIM = 0x006c6;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_MINUS_PITCH_TRIM = 0x006c7;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_PLUS_ROLL_TRIM = 0x006c8;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_MINUS_ROLL_TRIM = 0x006c9;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_PLUS_YAW_TRIM = 0x006ca;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_MINUS_YAW_TRIM = 0x006cb;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_PLUS_PITCH_TRIM = 0x006cc;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_MINUS_PITCH_TRIM = 0x006cd;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_PLUS_ROLL_TRIM = 0x006ce;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_MINUS_ROLL_TRIM = 0x006cf;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_PLUS_YAW_TRIM = 0x006d0;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_MINUS_YAW_TRIM = 0x006d1;// INTEGER SINGLE
inline constexpr unsigned int SCP_DETM_RHC = 0x006d2;// INTEGER SINGLE
inline constexpr unsigned int SCP_DATM_RHC = 0x006d3;// INTEGER SINGLE
inline constexpr unsigned int SCP_DETM_PAN = 0x006d4;// INTEGER SINGLE
inline constexpr unsigned int SCP_DATM_PAN = 0x006d5;// INTEGER SINGLE
inline constexpr unsigned int SCP_DRT = 0x006d6;// INTEGER SINGLE

// Body Flap Switch positions
inline constexpr unsigned int SCP_LH_BODY_FLAP_UP = 0x006d7;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_BODY_FLAP_DOWN = 0x006d8;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_BODY_FLAP_UP = 0x006d9;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_BODY_FLAP_DOWN = 0x006da;// INTEGER SINGLE
inline constexpr unsigned int SCP_DBFMAN = 0x006db;// INTEGER SINGLE

// MPS switches
inline constexpr unsigned int SCP_MPS_BACKUP_LH2_PRPLT_DUMP_START = 0x006dc;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_BACKUP_LH2_PRPLT_DUMP_STOP = 0x006dd;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_PRPLT_DUMP_SEQUENCE_START = 0x006de;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_PRPLT_DUMP_SEQUENCE_STOP = 0x006df;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ENG_LIMIT_CONTROL_ENABLE = 0x006e0;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ENG_LIMIT_CONTROL_INHIBIT = 0x006e1;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ENG_LIMIT_CONTROL_AUTO = 0x006e2;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ME_1_SHUTDOWN_CMD = 0x006e3;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ME_2_SHUTDOWN_CMD = 0x006e4;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ME_3_SHUTDOWN_CMD = 0x006e5;// INTEGER SINGLE

// Separation switches
inline constexpr unsigned int SCP_SRB_SEPARATION_AUTO_CMD = 0x006e6;// INTEGER SINGLE
inline constexpr unsigned int SCP_SRB_SEPARATION_MANUAL_AUTO_ENABLE_CMD = 0x006e7;// INTEGER SINGLE
inline constexpr unsigned int SCP_SRB_SEPARATION_INITIATE_CMD = 0x006e8;// INTEGER SINGLE
inline constexpr unsigned int SCP_ET_SEPARATION_MANUAL_ENABLE_CMD = 0x006e9;// INTEGER SINGLE
inline constexpr unsigned int SCP_ET_SEPARATION_INITIATE_CMD = 0x006ea;// INTEGER SINGLE
inline constexpr unsigned int SCP_ET_SEPARATION_AUTO_CMD = 0x006eb;// INTEGER SINGLE

// (0-"-Z"; 1-"-X")
inline constexpr unsigned int SCP_SENSE_SWITCH = 0x006ec;// INTEGER SINGLE

// FCS PBIs
inline constexpr unsigned int SCP_FCS_LH_PITCH_AUTO_MODE = 0x006ed;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_LH_PITCH_CSS_MODE = 0x006ee;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_LH_RY_AUTO_MODE = 0x006ef;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_LH_RY_CSS_MODE = 0x006f0;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_BODY_FLAP_AUTO_MANUAL = 0x006f1;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_SPD_BK_THROT_AUTO_MAN = 0x006f2;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_PITCH_AUTO_MODE = 0x006f3;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_PITCH_CSS_MODE = 0x006f4;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_RY_AUTO_MODE = 0x006f5;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_RY_CSS_MODE = 0x006f6;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_BODY_FLAP_AUTO_MANUAL = 0x006f7;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_SPD_BK_THROT_AUTO_MAN = 0x006f8;// INTEGER SINGLE

// Orbit DAP PBIs
inline constexpr unsigned int SCP_FWD_DAP_SELECT_A = 0x006f9;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_SELECT_B = 0x006fa;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_AUTO = 0x006fb;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN = 0x006fc;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_OPTIONS_NORM = 0x006fd;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_OPTIONS_VERNIER = 0x006fe;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_ROLL_DISC_RATE = 0x006ff;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_ROLL_ACCEL = 0x00700;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_ROLL_PULSE = 0x00701;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_PITCH_DISC_RATE = 0x00702;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_PITCH_ACCEL = 0x00703;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_PITCH_PULSE = 0x00704;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_YAW_DISC_RATE = 0x00705;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_YAW_ACCEL = 0x00706;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_YAW_PULSE = 0x00707;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_X_NORM = 0x00708;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_X_PULSE = 0x00709;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_X_LVLH = 0x0070a;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Y_NORM = 0x0070b;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Y_PULSE = 0x0070c;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Y_LOW_Z = 0x0070d;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Z_NORM = 0x0070e;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Z_PULSE = 0x0070f;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Z_HIGH = 0x00710;// INTEGER SINGLE

inline constexpr unsigned int SCP_AFT_DAP_SELECT_A = 0x00711;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_SELECT_B = 0x00712;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_AUTO = 0x00713;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN = 0x00714;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_OPTIONS_NORM = 0x00715;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_OPTIONS_VERNIER = 0x00716;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_ROLL_DISC_RATE = 0x00717;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_ROLL_ACCEL = 0x00718;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_ROLL_PULSE = 0x00719;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_PITCH_DISC_RATE = 0x0071a;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_PITCH_ACCEL = 0x0071b;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_PITCH_PULSE = 0x0071c;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_YAW_DISC_RATE = 0x0071d;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_YAW_ACCEL = 0x0071e;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_YAW_PULSE = 0x0071f;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_X_NORM = 0x00720;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_X_PULSE = 0x00721;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_X_LVLH = 0x00722;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Y_NORM = 0x00723;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Y_PULSE = 0x00724;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Y_LOW_Z = 0x00725;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Z_NORM = 0x00726;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Z_PULSE = 0x00727;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Z_HIGH = 0x00728;// INTEGER SINGLE

// Ascent
inline constexpr unsigned int SCP_KMIN = 0x00729;// INTEGER SINGLE
inline constexpr unsigned int SCP_KMAX = 0x0072a;// INTEGER SINGLE
// (0-KMAX_NOM; 1-KMAX_SECONDARY; 2-KMAX_ABORT)
inline constexpr unsigned int SCP_KMAX_SEL = 0x0072b;// INTEGER SINGLE
// MPS dump complete flag
inline constexpr unsigned int SCP_MPS_LO2_DUMP_STOP = 0x0072c;// INTEGER SINGLE

// Vent Doors
// Config Vent Doors for Launch cmd
inline constexpr unsigned int SCP_CONF_VENT_DOORS = 0x0072d;// INTEGER SINGLE
// Orbiter Vent Doors status word
inline constexpr unsigned int SCP_ORBITER_VENT_DOORS_STATUS_WORD = 0x0072e;// INTEGER DOUBLE
// Manual Vent Door close/open command
inline constexpr unsigned int SCP_VENT_DOOR_SEQ_INIT = 0x00730;// INTEGER SINGLE
// Manual Vent Door close cmd
inline constexpr unsigned int SCP_ALL_VENT_CLOSE_CMD = 0x00731;// INTEGER SINGLE
// Vent Door position indication (0-no info, 1-open, 2-closed)
inline constexpr unsigned int SCP_VENT_DOOR_POS_IND = 0x00732;// INTEGER SINGLE

// SSME and MPS flags
// ME-x command path fail flag
inline constexpr unsigned int SCP_ME_CMD_PATH_FAIL = 0x00733;// ARRAY(3) INTEGER SINGLE
// ME-x electronic lockup mode flag
inline constexpr unsigned int SCP_ME_ELEC_LOCKUP = 0x00736;// ARRAY(3) INTEGER SINGLE
// ME-x flight data path fail flag
inline constexpr unsigned int SCP_ME_FLT_DATA_PATH_FAIL = 0x00739;// ARRAY(3) INTEGER SINGLE
// ME-x hydraulic lockup mode flag
inline constexpr unsigned int SCP_ME_HYD_LOCKUP = 0x0073c;// ARRAY(3) INTEGER SINGLE
// ME-x engine limit exceeded flag
inline constexpr unsigned int SCP_ME_LIM_EX = 0x0073f;// ARRAY(3) INTEGER SINGLE
// MPS E-x eng ready ind
inline constexpr unsigned int SCP_ME_READY = 0x00742;// ARRAY(3) INTEGER SINGLE
// MPS E-x post-shutdown phase
inline constexpr unsigned int SCP_MEPSTSHDN = 0x00745;// ARRAY(3) INTEGER SINGLE
// MPS E-x shutdown phase
inline constexpr unsigned int SCP_MESHDN = 0x00748;// ARRAY(3) INTEGER SINGLE
// MPS E1 fail flag
inline constexpr unsigned int SCP_ME1_FAIL_SHUTDOWN = 0x0074b;// INTEGER SINGLE
// MPS E2 fail flag
inline constexpr unsigned int SCP_ME2_FAIL_SHUTDOWN = 0x0074c;// INTEGER SINGLE
// MPS E3 fail flag
inline constexpr unsigned int SCP_ME3_FAIL_SHUTDOWN = 0x0074d;// INTEGER SINGLE
// MECO command flag
inline constexpr unsigned int SCP_MECO_CMD = 0x0074e;// INTEGER SINGLE
// MECO confirmed flag
inline constexpr unsigned int SCP_MECO_CONFIRMED = 0x0074f;// INTEGER SINGLE
// MPS E-1 percent ch press [pct]
inline constexpr unsigned int SCP_ME1_CH_PRESS_FDBK = 0x00750;// INTEGER SINGLE
// MPS E-2 percent ch press [pct]
inline constexpr unsigned int SCP_ME2_CH_PRESS_FDBK = 0x00751;// INTEGER SINGLE
// MPS E-3 percent ch press [pct]
inline constexpr unsigned int SCP_ME3_CH_PRESS_FDBK = 0x00752;// INTEGER SINGLE

// ET separation command flag
inline constexpr unsigned int SCP_ET_SEP_CMD = 0x00753;// INTEGER SINGLE

inline constexpr unsigned int SCP_ET_AUTO_SEP_INHIBIT_CREW_ALERT = 0x00754;// INTEGER SINGLE
inline constexpr unsigned int SCP_DAP_DNMODE_RHC_CREW_ALERT = 0x00755;// INTEGER SINGLE
inline constexpr unsigned int SCP_ROLL_REF_CREW_ALERT = 0x00756;// INTEGER SINGLE
inline constexpr unsigned int SCP_LOB_SAT_POS_CREW_ALERT = 0x00757;// INTEGER SINGLE
inline constexpr unsigned int SCP_LIB_SAT_POS_CREW_ALERT = 0x00758;// INTEGER SINGLE
inline constexpr unsigned int SCP_RIB_SAT_POS_CREW_ALERT = 0x00759;// INTEGER SINGLE
inline constexpr unsigned int SCP_ROB_SAT_POS_CREW_ALERT = 0x0075a;// INTEGER SINGLE
inline constexpr unsigned int SCP_SPEEDBRAKE_POS_CREW_ALERT = 0x0075b;// INTEGER SINGLE

inline constexpr unsigned int SIMPLECOMPOOL_SIZE = 1884;

#endif// _COMPOOL_H_
