#ifndef _COMPOOL_H_
#define _COMPOOL_H_

// ----------------------------------------------------------------
// SSV COMPOOL definition
// ----------------------------------------------------------------
// SINGLE => 16b
// DOUBLE => 32b

// INFO: SCALAR should always be DOUBLE, and implemented in C with a 32b float

// current major mode
inline constexpr unsigned int SCP_MM = 0x00000;// INTEGER SINGLE
// new major mode
inline constexpr unsigned int SCP_NEW_MM = 0x00001;// INTEGER SINGLE

// outputs to EIUs
inline constexpr unsigned int SCP_EIU_1_CMD = 0x00002;// INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_2_CMD = 0x00003;// INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_3_CMD = 0x00004;// INTEGER SINGLE

// inputs from EIUs
inline constexpr unsigned int SCP_EIU_1_PRIDATA = 0x00005;// ARRAY(32) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_2_PRIDATA = 0x00025;// ARRAY(32) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_3_PRIDATA = 0x00045;// ARRAY(32) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_1_SECDATA = 0x00065;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_2_SECDATA = 0x0006b;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_EIU_3_SECDATA = 0x00071;// ARRAY(6) INTEGER SINGLE

// output to DDU-1
inline constexpr unsigned int SCP_DDU1_ADI = 0x00077;// ARRAY(14) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU1_HSI = 0x00085;// ARRAY(10) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU1_AVVI = 0x0008f;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU1_AMI = 0x00095;// ARRAY(6) INTEGER SINGLE

// output to DDU-2
inline constexpr unsigned int SCP_DDU2_ADI = 0x0009b;// ARRAY(14) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU2_HSI = 0x000a9;// ARRAY(10) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU2_AVVI = 0x000b3;// ARRAY(6) INTEGER SINGLE
inline constexpr unsigned int SCP_DDU2_AMI = 0x000b9;// ARRAY(6) INTEGER SINGLE

// output to HUD-1
inline constexpr unsigned int SCP_HUD1_MSG1 = 0x000bf;// ARRAY(31) INTEGER SINGLE
inline constexpr unsigned int SCP_HUD1_MSG2 = 0x000de;// ARRAY(12) INTEGER SINGLE

// output to HUD-2
inline constexpr unsigned int SCP_HUD2_MSG1 = 0x000ea;// ARRAY(31) INTEGER SINGLE
inline constexpr unsigned int SCP_HUD2_MSG2 = 0x00109;// ARRAY(12) INTEGER SINGLE

// MDM FF1 input
// Radar Altimeter 1 data
inline constexpr unsigned int SCP_FF1_IOM0_CH4_DATA = 0x00115;// INTEGER SINGLE
// 3-LH_BODY_FLAP_UP_A
// 4-LH_BODY_FLAP_DOWN_A
// 5-MPS ME-1 SHUTDOWN CMD A
inline constexpr unsigned int SCP_FF1_IOM4_CH0_DATA = 0x00116;// INTEGER SINGLE
// 10-FCS LH PITCH AUTO MODE A
// 11-FCS LH PITCH CSS MODE A
// 13-FCS LH R-Y AUTO MODE A
// 14-FCS LH R-Y CSS MODE A
// 15-LH BODY FLAP AUTO/MANUAL A
inline constexpr unsigned int SCP_FF1_IOM4_CH1_DATA = 0x00117;// INTEGER SINGLE
// 0-LH SPD BK/THROT AUTO/MAN A
// 3-ENTRY ROLL MODE NO Y JET A
// 4-R PB/W VENTS 4 & 7 CLOSED 2
// 5-R PB/W VENTS 4 & 7 OPEN 2
// 6-R FWD VENTS 1 & 2 CLOSED 1
// 7-R FWD VENTS 1 & 2 OPEN 1
// 8-R FWD VENTS 1 & 2 PURGE IND 1
// 9-L PB VENT 6 CLOSED 1
// 10-L PB VENT 6 OPEN 1
// 11-L PB VENT 6 PURGE 1 IND 1
// 12-R PB VENT 3 CLOSED 1
// 13-R PB VENT 3 OPEN 1
// 14-R PB VENT 5 CLOSED 1
// 15-R PB VENT 5 OPEN 1
inline constexpr unsigned int SCP_FF1_IOM4_CH2_DATA = 0x00118;// INTEGER SINGLE
// 7-FWD THC POS X OUTPUT - A
// 8-FWD THC NEG X OUTPUT - A
// 9-FWD THC POS Y OUTPUT - A
// 10-FWD THC NEG Y OUTPUT - A
// 11-FWD THC POS Z OUTPUT - A
// 12-FWD THC NEG Z OUTPUT - A
// 13-LH SBTC TAKEOVER - A
inline constexpr unsigned int SCP_FF1_IOM6_CH0_DATA = 0x00119;// INTEGER SINGLE
// 1-LH_RHC_PLUS_PITCH_TRIM_A
// 2-LH_RHC_MINUS_PITCH_TRIM_A
// 3-LH_RHC_PLUS_ROLL_TRIM_A
// 4-LH_RHC_MINUS_ROLL_TRIM_A
// 5-SRB SEPARATION AUTO A CMD
// 6-SRB SEPN MANUAL/AUTO ENABLE A CMD
// 7-SRB SEPARATION INITIATE A CMD
inline constexpr unsigned int SCP_FF1_IOM6_CH1_DATA = 0x0011a;// INTEGER SINGLE
// 4-FWD DAP SELECT A - A
// 5-FWD DAP SELECT B - A
// 6-AFT DAP SELECT A - C
// 7-AFT DAP SELECT B - C
// 8-FWD DAP AUTO A
// 9-FWD DAP MAN A
// 10-AFT DAP AUTO C
// 11-AFT DAP MAN C
inline constexpr unsigned int SCP_FF1_IOM9_CH0_DATA = 0x0011b;// INTEGER SINGLE
// 1-SENSE SW -Z CON A
// 2-SENSE SW -X CON A
// 3-ENTRY ROLL MODE L GAIN - A
// 4-FWD ROTATION ROLL DISC RATE A
// 5-FWD ROTATION ROLL ACCEL A
// 6-FWD ROTATION ROLL PULSE A
// 7-FWD ROTATION PITCH DISC RATE A
// 8-FWD ROTATION PITCH ACCEL A
// 9-FWD ROTATION PITCH PULSE A
// 10-FWD ROTATION YAW DISC RATE A
// 11-FWD ROTATION YAW ACCEL A
// 12-FWD ROTATION YAW PULSE A
// 13-FWD RCS JETS NORM A
// 14-FWD RCS JETS VERNIER A
// 15-FWD TRANSLATION X NORM A
inline constexpr unsigned int SCP_FF1_IOM9_CH1_DATA = 0x0011c;// INTEGER SINGLE
// 0-FWD TRANSLATION X PULSE A
// 1-FWD TRANSLATION X LVLH A
// 2-FWD TRANSLATION Y NORM A
// 3-FWD TRANSLATION Y PULSE A
// 4-FWD TRANSLATION Y LOW Z A
// 5-FWD TRANSLATION Z NORM A
// 6-FWD TRANSLATION Z PULSE A
// 7-FWD TRANSLATION Z HIGH A
// 8-MPS PRPLT DUMP SEQUENCE START A
// 9-MPS PRPLT DUMP SEQUENCE STOP A
inline constexpr unsigned int SCP_FF1_IOM9_CH2_DATA = 0x0011d;// INTEGER SINGLE
// 1-LH_PLUS_PITCH_TRIM_A
// 2-LH_MINUS_PITCH_TRIM_A
// 3-LH_PLUS_ROLL_TRIM_A
// 4-LH_MINUS_ROLL_TRIM_A
// 5-LH_PLUS_YAW_TRIM_A
// 6-LH_MINUS_YAW_TRIM_A
// 13-CDR RDR ALTM SEL 1
inline constexpr unsigned int SCP_FF1_IOM12_CH0_DATA = 0x0011e;// INTEGER SINGLE
// 8-LH_RHC_TRIM_INHIBIT_A
inline constexpr unsigned int SCP_FF1_IOM12_CH1_DATA = 0x0011f;// INTEGER SINGLE
// 8-L PB VENT 6 PURGE 2 IND 1
// 14-AFT RCS OPTIONS NORM C
// 15-AFT RCS OPTIONS VERNIER C
inline constexpr unsigned int SCP_FF1_IOM12_CH2_DATA = 0x00120;// INTEGER SINGLE
// 7-AFT THC POS X OUTPUT - A
// 8-AFT THC NEG X OUTPUT - A
// 9-AFT THC POS Y OUTPUT - A
// 10-AFT THC NEG Y OUTPUT - A
// 11-AFT THC POS Z OUTPUT - A
// 12-AFT THC NEG Z OUTPUT - A
inline constexpr unsigned int SCP_FF1_IOM15_CH0_DATA = 0x00121;// INTEGER SINGLE
// 5-ET SEPARATION MANUAL ENABLE A CMD
// 6-ET SEPARATION INITIATE A CMD
// 7-ET SEPARATION AUTO A CMD
inline constexpr unsigned int SCP_FF1_IOM15_CH1_DATA = 0x00122;// INTEGER SINGLE

// MDM FF2 input
// Radar Altimeter 2 data
inline constexpr unsigned int SCP_FF2_IOM0_CH4_DATA = 0x00123;// INTEGER SINGLE
// 2-ENTRY ROLL MODE NO Y JET B
// 3-LH_BODY_FLAP_UP_B
// 4-LH_BODY_FLAP_DOWN_B
// 5-MPS ME-1 SHUTDOWN CMD B
inline constexpr unsigned int SCP_FF2_IOM4_CH0_DATA = 0x00124;// INTEGER SINGLE
// 10-FCS LH PITCH AUTO MODE B
// 11-FCS LH PITCH CSS MODE B
// 13-FCS LH R-Y AUTO MODE B
// 14-FCS LH R-Y CSS MODE B
// 15-LH BODY FLAP AUTO/MANUAL B
inline constexpr unsigned int SCP_FF2_IOM4_CH1_DATA = 0x00125;// INTEGER SINGLE
// 0-LH SPD BK/THROT AUTO/MAN B
// 1-MPS ENG LIMIT CONTROL NO. 1 ENABLE
// 2-MPS ENG LIMIT CONTROL NO. 1 INHIBIT
// 3-MPS ENG LIMIT CONTROL NO. 1 AUTO
// 4-L PB VENT 3 CLOSED 2
// 5-L PB VENT 3 OPEN 2
// 6-L FWD VENTS 1 & 2 CLOSED 2
// 7-L FWD VENTS 1 & 2 OPEN 2
// 8-L FWD VENTS 1 & 2 PURGE IND 2
// 9-R PB VENT 6 CLOSED 2
// 10-R PB VENT 6 OPEN 2
// 11-R PB VENT 6 PURGE 1 IND 2
// 12-L PB/W VENTS 4 & 7 CLOSED 2
// 13-L PB/W VENTS 4 & 7 OPEN 2
// 14-R PB VENT 5 CLOSED 2
// 15-R PB VENT 5 OPEN 2
inline constexpr unsigned int SCP_FF2_IOM4_CH2_DATA = 0x00126;// INTEGER SINGLE
// 7-FWD THC POS X OUTPUT - B
// 8-FWD THC NEG X OUTPUT - B
// 9-FWD THC POS Y OUTPUT - B
// 10-FWD THC NEG Y OUTPUT - B
// 11-FWD THC POS Z OUTPUT - B
// 12-FWD THC NEG Z OUTPUT - B
// 13-LH SBTC TAKEOVER - B
inline constexpr unsigned int SCP_FF2_IOM6_CH0_DATA = 0x00127;// INTEGER SINGLE
// 1-LH_RHC_PLUS_PITCH_TRIM_B
// 2-LH_RHC_MINUS_PITCH_TRIM_B
// 3-LH_RHC_PLUS_ROLL_TRIM_B
// 4-LH_RHC_MINUS_ROLL_TRIM_B
inline constexpr unsigned int SCP_FF2_IOM6_CH1_DATA = 0x00128;// INTEGER SINGLE
// 4-FWD DAP SELECT A - B
// 5-FWD DAP SELECT B - B
// 8-FWD DAP AUTO B
// 9-FWD DAP MAN B
inline constexpr unsigned int SCP_FF2_IOM9_CH0_DATA = 0x00129;// INTEGER SINGLE
// 0-MPS ME-2 SHUTDOWN CMD A
// 1-SENSE SW -Z CON B
// 2-SENSE SW -X CON B
// 3-ENTRY ROLL MODE L GAIN - B
// 4-FWD ROTATION ROLL DISC RATE B
// 5-FWD ROTATION ROLL ACCEL B
// 6-FWD ROTATION ROLL PULSE B
// 7-FWD ROTATION PITCH DISC RATE B
// 8-FWD ROTATION PITCH ACCEL B
// 9-FWD ROTATION PITCH PULSE B
// 10-FWD ROTATION YAW DISC RATE B
// 11-FWD ROTATION YAW ACCEL B
// 12-FWD ROTATION YAW PULSE B
// 13-FWD RCS JETS NORM B
// 14-FWD RCS JETS VERNIER B
// 15-FWD TRANSLATION X NORM B
inline constexpr unsigned int SCP_FF2_IOM9_CH1_DATA = 0x0012a;// INTEGER SINGLE
// 0-FWD TRANSLATION X PULSE B
// 1-FWD TRANSLATION X LVLH B
// 2-FWD TRANSLATION Y NORM B
// 3-FWD TRANSLATION Y PULSE B
// 4-FWD TRANSLATION Y LOW Z B
// 5-FWD TRANSLATION Z NORM B
// 6-FWD TRANSLATION Z PULSE B
// 7-FWD TRANSLATION Z HIGH B
// 8-MPS PRPLT DUMP SEQUENCE START B
// 9-MPS PRPLT DUMP SEQUENCE STOP B
inline constexpr unsigned int SCP_FF2_IOM9_CH2_DATA = 0x0012b;// INTEGER SINGLE
// 1-LH_PLUS_PITCH_TRIM_B
// 2-LH_MINUS_PITCH_TRIM_B
// 3-LH_PLUS_ROLL_TRIM_B
// 4-LH_MINUS_ROLL_TRIM_B
// 5-LH_PLUS_YAW_TRIM_B
// 6-LH_MINUS_YAW_TRIM_B
// 13-PLT RDR ALTM SEL 1
inline constexpr unsigned int SCP_FF2_IOM12_CH0_DATA = 0x0012c;// INTEGER SINGLE
// 8-LH_RHC_TRIM_INHIBIT_B
// 10-FCS RH PITCH AUTO MODE A
// 11-FCS RH PITCH CSS MODE A
// 13-FCS RH R-Y AUTO MODE A
// 14-FCS RH R-Y CSS MODE A
// 15-RH BODY FLAP AUTO/MANUAL A
inline constexpr unsigned int SCP_FF2_IOM12_CH1_DATA = 0x0012d;// INTEGER SINGLE
// 0-RH SPD BK/THROT AUTO/MAN A
// 8-R PB VENT 6 PURGE 2 IND 2
inline constexpr unsigned int SCP_FF2_IOM12_CH2_DATA = 0x0012e;// INTEGER SINGLE
// 7-AFT THC POS X OUTPUT - B
// 8-AFT THC NEG X OUTPUT - B
// 9-AFT THC POS Y OUTPUT - B
// 10-AFT THC NEG Y OUTPUT - B
// 11-AFT THC POS Z OUTPUT - B
// 12-AFT THC NEG Z OUTPUT - B
// 13-RH SBTC TAKEOVER - A
inline constexpr unsigned int SCP_FF2_IOM15_CH0_DATA = 0x0012f;// INTEGER SINGLE

// MDM FF3 input
// 3-RH_BODY_FLAP_UP_A
// 4-RH_BODY_FLAP_DOWN_A
// 5-MPS ME-3 SHUTDOWN CMD A
inline constexpr unsigned int SCP_FF3_IOM4_CH0_DATA = 0x00130;// INTEGER SINGLE
// 10-FCS LH PITCH AUTO MODE C
// 11-FCS LH PITCH CSS MODE C
// 13-FCS LH R-Y AUTO MODE C
// 14-FCS LH R-Y CSS MODE C
// 15-LH BODY FLAP AUTO/MANUAL C
inline constexpr unsigned int SCP_FF3_IOM4_CH1_DATA = 0x00131;// INTEGER SINGLE
// 0-LH SPD BK/THROT AUTO/MAN C
// 1-MPS ENG LIMIT CONTROL NO. 2 ENABLE
// 2-MPS ENG LIMIT CONTROL NO. 2 INHIBIT
// 3-MPS ENG LIMIT CONTROL NO. 2 AUTO
// 4-L PB VENT 3 CLOSED 1
// 5-L PB VENT 3 OPEN 1
// 6-L FWD VENTS 1 & 2 CLOSED 1
// 7-L FWD VENTS 1 & 2 OPEN 1
// 8-L FWD VENTS 1 & 2 PURGE IND 1
// 9-R PB VENT 6 CLOSED 1
// 10-R PB VENT 6 OPEN 1
// 11-R PB VENT 6 PURGE 1 IND 1
// 12-L PB/W VENTS 4 & 7 CLOSED 1
// 13-L PB/W VENTS 4 & 7 OPEN 1
// 14-L PB VENT 5 CLOSED 1
// 15-L PB VENT 5 OPEN 1
inline constexpr unsigned int SCP_FF3_IOM4_CH2_DATA = 0x00132;// INTEGER SINGLE
// 7-FWD THC POS X OUTPUT - C
// 8-FWD THC NEG X OUTPUT - C
// 9-FWD THC POS Y OUTPUT - C
// 10-FWD THC NEG Y OUTPUT - C
// 11-FWD THC POS Z OUTPUT - C
// 12-FWD THC NEG Z OUTPUT - C
// 13-LH SBTC TAKEOVER - C
inline constexpr unsigned int SCP_FF3_IOM6_CH0_DATA = 0x00133;// INTEGER SINGLE
// 5-SRB SEPARATION AUTO C CMD
// 6-SRB SEPN MANUAL/AUTO ENABLE C CMD
// 7-SRB SEPARATION INITIATE C CMD
inline constexpr unsigned int SCP_FF3_IOM6_CH1_DATA = 0x00134;// INTEGER SINGLE
// 4-AFT DAP SELECT A - A
// 5-AFT DAP SELECT B - A
// 6-FWD DAP SELECT A - C
// 7-FWD DAP SELECT B - C
// 8-AFT DAP AUTO A
// 9-AFT DAP MAN A
// 10-FWD DAP AUTO C
// 11-FWD DAP MAN C
inline constexpr unsigned int SCP_FF3_IOM9_CH0_DATA = 0x00135;// INTEGER SINGLE
// 0-MPS ME-2 SHUTDOWN CMD B
// 1-SENSE SW -Z CON C
// 2-SENSE SW -X CON C
// 3-ENTRY ROLL MODE L GAIN - C
// 4-AFT ROTATION ROLL DISC RATE A
// 5-AFT ROTATION ROLL ACCEL A
// 6-AFT ROTATION ROLL PULSE A
// 7-AFT ROTATION PITCH DISC RATE A
// 8-AFT ROTATION PITCH ACCEL A
// 9-AFT ROTATION PITCH PULSE A
// 10-AFT ROTATION YAW DISC RATE A
// 11-AFT ROTATION YAW ACCEL A
// 12-AFT ROTATION YAW PULSE A
// 13-AFT RCS JETS NORM A
// 14-AFT RCS JETS VERNIER A
// 15-AFT TRANSLATION X NORM A
inline constexpr unsigned int SCP_FF3_IOM9_CH1_DATA = 0x00136;// INTEGER SINGLE
// 0-AFT TRANSLATION X PULSE A
// 1-AFT TRANSLATION X LVLH A
// 2-AFT TRANSLATION Y NORM A
// 3-AFT TRANSLATION Y PULSE A
// 4-AFT TRANSLATION Y LOW Z A
// 5-AFT TRANSLATION Z NORM A
// 6-AFT TRANSLATION Z PULSE A
// 7-AFT TRANSLATION Z HIGH A
// 8-MPS BACKUP LH2 PRPLT DUMP START A
// 9-MPS BACKUP LH2 PRPLT DUMP STOP A
inline constexpr unsigned int SCP_FF3_IOM9_CH2_DATA = 0x00137;// INTEGER SINGLE
// 1-RH_PLUS_PITCH_TRIM_A
// 2-RH_MINUS_PITCH_TRIM_A
// 3-RH_PLUS_ROLL_TRIM_A
// 4-RH_MINUS_ROLL_TRIM_A
// 5-RH_PLUS_YAW_TRIM_A
// 6-RH_MINUS_YAW_TRIM_A
inline constexpr unsigned int SCP_FF3_IOM12_CH0_DATA = 0x00138;// INTEGER SINGLE
// 2-ENTRY ROLL MODE NO Y JET C
// 8-RH_RHC_TRIM_INHIBIT_A
// 10-FCS RH PITCH AUTO MODE B
// 11-FCS RH PITCH CSS MODE B
// 13-FCS RH R-Y AUTO MODE B
// 14-FCS RH R-Y CSS MODE B
// 15-RH BODY FLAP AUTO/MANUAL B
inline constexpr unsigned int SCP_FF3_IOM12_CH1_DATA = 0x00139;// INTEGER SINGLE
// 0-RH SPD BK/THROT AUTO/MAN B
// 8-R PB VENT 6 PURGE 2 IND 1
// 14-FWD RCS OPTIONS NORM C
// 15-FWD RCS OPTIONS VERNIER C
inline constexpr unsigned int SCP_FF3_IOM12_CH2_DATA = 0x0013a;// INTEGER SINGLE
// 7-AFT THC POS X OUTPUT - C
// 8-AFT THC NEG X OUTPUT - C
// 9-AFT THC POS Y OUTPUT - C
// 10-AFT THC NEG Y OUTPUT - C
// 11-AFT THC POS Z OUTPUT - C
// 12-AFT THC NEG Z OUTPUT - C
// 13-RH SBTC TAKEOVER - B
inline constexpr unsigned int SCP_FF3_IOM15_CH0_DATA = 0x0013b;// INTEGER SINGLE
// 1-RH_RHC_PLUS_PITCH_TRIM_A
// 2-RH_RHC_MINUS_PITCH_TRIM_A
// 3-RH_RHC_PLUS_ROLL_TRIM_A
// 4-RH_RHC_MINUS_ROLL_TRIM_A
// 5-ET SEPARATION MANUAL ENABLE C CMD
// 6-ET SEPARATION INITIATE C CMD
// 7-ET SEPARATION AUTO C CMD
inline constexpr unsigned int SCP_FF3_IOM15_CH1_DATA = 0x0013c;// INTEGER SINGLE

// MDM FF4 input
// 3-RH_BODY_FLAP_UP_B
// 4-RH_BODY_FLAP_DOWN_B
// 5-MPS ME-3 SHUTDOWN CMD B
inline constexpr unsigned int SCP_FF4_IOM4_CH0_DATA = 0x0013d;// INTEGER SINGLE
// 1-MPS ENG LIMIT CONTROL NO. 3 ENABLE
// 2-MPS ENG LIMIT CONTROL NO. 3 INHIBIT
// 3-MPS ENG LIMIT CONTROL NO. 3 AUTO
// 4-R PB VENT 3 CLOSED 2
// 5-R PB VENT 3 OPEN 2
// 6-R FWD VENTS 1 & 2 CLOSED 2
// 7-R FWD VENTS 1 & 2 OPEN 2
// 8-R FWD VENTS 1 & 2 PURGE IND 2
// 9-L PB VENT 6 CLOSED 2
// 10-L PB VENT 6 OPEN 2
// 11-L PB VENT 6 PURGE 1 IND 2
// 12-R PB/W VENTS 4 & 7 CLOSED 1
// 13-R PB/W VENTS 4 & 7 OPEN 1
// 14-L PB VENT 5 CLOSED 2
// 15-L PB VENT 5 OPEN 2
inline constexpr unsigned int SCP_FF4_IOM4_CH2_DATA = 0x0013e;// INTEGER SINGLE
// 5-SRB SEPARATION AUTO B CMD
// 6-SRB SEPN MANUAL/AUTO ENABLE B CMD
// 7-SRB SEPARATION INITIATE B CMD
inline constexpr unsigned int SCP_FF4_IOM6_CH1_DATA = 0x0013f;// INTEGER SINGLE
// 4-AFT DAP SELECT A - B
// 5-AFT DAP SELECT B - B
// 8-AFT DAP AUTO B
// 9-AFT DAP MAN B
inline constexpr unsigned int SCP_FF4_IOM9_CH0_DATA = 0x00140;// INTEGER SINGLE
// 3-ENTRY ROLL MODE L GAIN - D
// 4-AFT ROTATION ROLL DISC RATE B
// 5-AFT ROTATION ROLL ACCEL B
// 6-AFT ROTATION ROLL PULSE B
// 7-AFT ROTATION PITCH DISC RATE B
// 8-AFT ROTATION PITCH ACCEL B
// 9-AFT ROTATION PITCH PULSE B
// 10-AFT ROTATION YAW DISC RATE B
// 11-AFT ROTATION YAW ACCEL B
// 12-AFT ROTATION YAW PULSE B
// 13-AFT RCS JETS NORM B
// 14-AFT RCS JETS VERNIER B
// 15-AFT TRANSLATION X NORM B
inline constexpr unsigned int SCP_FF4_IOM9_CH1_DATA = 0x00141;// INTEGER SINGLE
// 0-AFT TRANSLATION X PULSE B
// 1-AFT TRANSLATION X LVLH B
// 2-AFT TRANSLATION Y NORM B
// 3-AFT TRANSLATION Y PULSE B
// 4-AFT TRANSLATION Y LOW Z B
// 5-AFT TRANSLATION Z NORM B
// 6-AFT TRANSLATION Z PULSE B
// 7-AFT TRANSLATION Z HIGH B
// 8-MPS BACKUP LH2 PRPLT DUMP START B
// 9-MPS BACKUP LH2 PRPLT DUMP STOP B
inline constexpr unsigned int SCP_FF4_IOM9_CH2_DATA = 0x00142;// INTEGER SINGLE
// 1-RH_PLUS_PITCH_TRIM_B
// 2-RH_MINUS_PITCH_TRIM_B
// 3-RH_PLUS_ROLL_TRIM_B
// 4-RH_MINUS_ROLL_TRIM_B
// 5-RH_PLUS_YAW_TRIM_B
// 6-RH_MINUS_YAW_TRIM_B
inline constexpr unsigned int SCP_FF4_IOM12_CH0_DATA = 0x00143;// INTEGER SINGLE
// 8-RH_RHC_TRIM_INHIBIT_B
// 10-FCS RH PITCH AUTO MODE C
// 11-FCS RH PITCH CSS MODE C
// 13-FCS RH R-Y AUTO MODE C
// 14-FCS RH R-Y CSS MODE C
// 15-RH BODY FLAP AUTO/MANUAL C
inline constexpr unsigned int SCP_FF4_IOM12_CH1_DATA = 0x00144;// INTEGER SINGLE
// 0-RH SPD BK/THROT AUTO/MAN C
// 8-L PB VENT 6 PURGE 2 IND 2
// 15-ENTRY ROLL MODE NO Y JET D
inline constexpr unsigned int SCP_FF4_IOM12_CH2_DATA = 0x00145;// INTEGER SINGLE
// 13-RH SBTC TAKEOVER - C
inline constexpr unsigned int SCP_FF4_IOM15_CH0_DATA = 0x00146;// INTEGER SINGLE
// 1-RH_RHC_PLUS_PITCH_TRIM_B
// 2-RH_RHC_MINUS_PITCH_TRIM_B
// 3-RH_RHC_PLUS_ROLL_TRIM_B
// 4-RH_RHC_MINUS_ROLL_TRIM_B
// 5-ET SEPARATION MANUAL ENABLE B CMD
// 6-ET SEPARATION INITIATE B CMD
// 7-ET SEPARATION AUTO B CMD
inline constexpr unsigned int SCP_FF4_IOM15_CH1_DATA = 0x00147;// INTEGER SINGLE

// MDM FA1 input
// 13-L AFT VENTS 8 & 9 CLOSED 1
// 14-L AFT VENTS 8 & 9 OPEN 1
// 15-L AFT VENTS 8 & 9 PURGE IND 1
inline constexpr unsigned int SCP_FA1_IOM11_CH0_DATA = 0x00148;// INTEGER SINGLE

// MDM FA2 input
// 13-R AFT VENTS 8 & 9 CLOSED 2
// 14-R AFT VENTS 8 & 9 OPEN 2
// 15-R AFT VENTS 8 & 9 PURGE IND 2
inline constexpr unsigned int SCP_FA2_IOM11_CH0_DATA = 0x00149;// INTEGER SINGLE

// MDM FA3 input
// 13-R AFT VENTS 8 & 9 CLOSED 1
// 14-R AFT VENTS 8 & 9 OPEN 1
// 15-R AFT VENTS 8 & 9 PURGE IND 1
inline constexpr unsigned int SCP_FA3_IOM11_CH0_DATA = 0x0014a;// INTEGER SINGLE

// MDM FA4 input
// 13-L AFT VENTS 8 & 9 CLOSED 2
// 14-L AFT VENTS 8 & 9 OPEN 2
// 15-L AFT VENTS 8 & 9 PURGE IND 2
inline constexpr unsigned int SCP_FA4_IOM11_CH0_DATA = 0x0014b;// INTEGER SINGLE

// MDM FF1 output
// 0-RH VENTS 1/2 MOTOR 1/CLOSE B (CL/1B)
// 1-RH VENTS 1/2 MOTOR 1/OPEN B (OP/1B)
// 2-RH VENTS 1/2 MOTOR 1/PURGE B (PG/1B)
// 11-RH VENTS 4/7 MOTOR 2/CLOSE B (CL/2B)
inline constexpr unsigned int SCP_FF1_IOM2_CH0_DATA = 0x0014c;// INTEGER SINGLE
// 0-F7 LIGHT: C MPS AMBER STATUS
// 7-F6 LIGHT A: RCS CMD "ROLL LEFT"
// 8-F6 LIGHT A: RCS CMD "ROLL RIGHT"
// 9-F6 LIGHT A: RCS CMD "YAW LEFT"
// 10-F6 LIGHT A: RCS CMD "YAW RIGHT"
// 11-F6 LIGHT A: RCS CMD "PITCH UP"
// 12-F6 LIGHT A: RCS CMD "PITCH DOWN"
// 13-C3 LIGHT: FWD DAP CONTROL "AUTO"
// 14-C3 LIGHT: FWD DAP SELECT "A"
// 15-C3 LIGHT: FWD DAP RCS JETS "NORM"
inline constexpr unsigned int SCP_FF1_IOM2_CH1_DATA = 0x0014d;// INTEGER SINGLE
// 3-C3 LIGHT: FWD DAP CONTROL "MAN"
// 4-C3 LIGHT: FWD DAP SELECT "B"
// 5-C3 LIGHT: FWD DAP RCS JETS "VERN"
// 7-RH VENTS 4/7 MOTOR 2/OPEN B (OP/2B)
// 8-RH VENT 3 MOTOR 1/CLOSE B (CL/1B)
// 9-RH VENT 3 MOTOR 1/OPEN B (OP/1B)
// 10-LH VENT 6 MOTOR 1/CLOSE B (CL/1B)
// 11-LH VENT 6 MOTOR 1/OPEN B (OP/1B)
// 12-LH VENT 6 MOTOR 1/PRG-1 B (P1/1B)
// 13-LH VENT 6 MOTOR 1/PRG-2 B (P2/1B)
// 14-RH VENT 5 MOTOR 1/CLOSE B (CL/1B)
// 15-RH VENT 5 MOTOR 1/OPEN B (OP/1B)
inline constexpr unsigned int SCP_FF1_IOM2_CH2_DATA = 0x0014e;// INTEGER SINGLE
// 0-FWD EVENT TIMER: ABORT TIMER_RESET
inline constexpr unsigned int SCP_FF1_IOM5_CH1_DATA = 0x0014f;// INTEGER SINGLE
// 0-RH VENTS 1/2 MOTOR 1/CLOSE A (CL/1A)
// 1-RH VENTS 1/2 MOTOR 1/OPEN A (OP/1A)
// 2-RH VENTS 1/2 MOTOR 1/PURGE A (PG/1A)
// 4-F2 LIGHT: LH FCS BODY FLAP "AUTO"
// 5-F2 LIGHT: LH FCS SPEED BK "AUTO"
// 6-F2 LIGHT: LH FCS PITCH "AUTO"
// 7-F2 LIGHT: LH FCS ROLL/YAW "AUTO"
inline constexpr unsigned int SCP_FF1_IOM10_CH0_DATA = 0x00150;// INTEGER SINGLE
// 0-F7 LIGHT: C MPS RED STATUS
// 1-C3 LIGHT: FWD MAN ROT ROLL "DISC RT"
// 2-C3 LIGHT: FWD MAN ROT ROLL "ACCEL"
// 3-C3 LIGHT: FWD MAN ROT ROLL "PULSE"
// 4-C3 LIGHT: FWD MAN ROT PITCH "DISC RT"
// 5-C3 LIGHT: FWD MAN ROT PITCH "ACCEL"
// 6-C3 LIGHT: FWD MAN ROT PITCH "PULSE"
// 7-C3 LIGHT: FWD MAN ROT YAW "DISC RT"
// 8-C3 LIGHT: FWD MAN ROT YAW "ACCEL"
// 9-C3 LIGHT: FWD MAN ROT YAW "PULSE"
// 10-C3 LIGHT: FWD MAN TRANS X "NORM"
// 11-C3 LIGHT: FWD MAN TRANS X "PULSE"
// 12-C3 LIGHT: FWD MAN TRANS X "LVLH"
// 13-C3 LIGHT: FWD MAN TRANS Y "NORM"
// 14-C3 LIGHT: FWD MAN TRANS Y "PULSE"
// 15-C3 LIGHT: FWD MAN TRANS Y "LOW Z"
inline constexpr unsigned int SCP_FF1_IOM10_CH1_DATA = 0x00151;// INTEGER SINGLE
// 0-C3 LIGHT: FWD MAN TRANS Z "NORM"
// 1-C3 LIGHT: FWD MAN TRANS Z "PULSE"
// 2-C3 LIGHT: FWD MAN TRANS Z "HIGH"
// 6-RH VENTS 4/7 MOTOR 2/CLOSE A (CL/2A)
// 7-RH VENTS 4/7 MOTOR 2/OPEN A (OP/2A)
// 8-RH VENT 3 MOTOR 1/CLOSE A (CL/1A)
// 9-RH VENT 3 MOTOR 1/OPEN A (OP/1A)
// 10-LH VENT 6 MOTOR 1/CLOSE A (CL/1A)
// 11-LH VENT 6 MOTOR 1/OPEN A (OP/1A)
// 12-LH VENT 6 MOTOR 1/PRG-1 A (P1/1A)
// 13-LH VENT 6 MOTOR 1/PRG-2 A (P2/1A)
// 14-RH VENT 5 MOTOR 1/CLOSE A (CL/1A)
// 15-RH VENT 5 MOTOR 1/OPEN A (OP/1A)
inline constexpr unsigned int SCP_FF1_IOM10_CH2_DATA = 0x00152;// INTEGER SINGLE

// MDM FF2 output
// 0-LH VENTS 1/2 MOTOR 2/CLOSE B (CL/2B)
// 1-LH VENTS 1/2 MOTOR 2/OPEN B (OP/2B)
// 2-LH VENTS 1/2 MOTOR 2/PURGE B (PG/2B)
inline constexpr unsigned int SCP_FF2_IOM2_CH0_DATA = 0x00153;// INTEGER SINGLE
// 0-F7 LIGHT: L MPS AMBER STATUS
// 6-RH VENT 5 MOTOR 2/CLOSE B (CL/2B)
inline constexpr unsigned int SCP_FF2_IOM2_CH1_DATA = 0x00154;// INTEGER SINGLE
// 6-LH VENT 3 MOTOR 2/CLOSE B (CL/2B)
// 7-LH VENT 3 MOTOR 2/OPEN B (OP/2B)
// 8-LH VENTS 4/7 MOTOR 2/CLOSE B (CL/2B)
// 9-LH VENTS 4/7 MOTOR 2/OPEN B (OP/2B)
// 10-RH VENT 6 MOTOR 2/CLOSE B (CL/2B)
// 11-RH VENT 6 MOTOR 2/OPEN B (OP/2B)
// 12-RH VENT 6 MOTOR 2/PRG-1 B (P1/2B)
// 13-RH VENT 6 MOTOR 2/PRG-2 B (P2/2B)
// 15-RH VENT 5 MOTOR 2/OPEN B (OP/2B)
inline constexpr unsigned int SCP_FF2_IOM2_CH2_DATA = 0x00155;// INTEGER SINGLE
// 0-LH VENTS 1/2 MOTOR 2/CLOSE A (CL/2A)
// 1-LH VENTS 1/2 MOTOR 2/OPEN A (OP/2A)
// 2-LH VENTS 1/2 MOTOR 2/PURGE A (PG/2A)
// 4-F2 LIGHT: LH FCS BODY FLAP "MAN"
// 5-F2 LIGHT: LH FCS SPEED BK "MAN"
// 6-F2 LIGHT: LH FCS PITCH "CSS"
// 7-F2 LIGHT: LH FCS ROLL/YAW "CSS"
inline constexpr unsigned int SCP_FF2_IOM10_CH0_DATA = 0x00156;// INTEGER SINGLE
// 0-F7 LIGHT: L MPS RED STATUS
inline constexpr unsigned int SCP_FF2_IOM10_CH1_DATA = 0x00157;// INTEGER SINGLE
// 6-LH VENT 3 MOTOR 2/CLOSE A (CL/2A)
// 7-LH VENT 3 MOTOR 2/OPEN A (OP/2A)
// 8-LH VENTS 4/7 MOTOR 2/CLOSE A (CL/2A)
// 9-LH VENTS 4/7 MOTOR 2/OPEN A (OP/2A)
// 10-RH VENT 6 MOTOR 2/CLOSE A (CL/2A)
// 11-RH VENT 6 MOTOR 2/OPEN A (OP/2A)
// 12-RH VENT 6 MOTOR 2/PRG-1 A (P1/2A)
// 13-RH VENT 6 MOTOR 2/PRG-2 A (P2/2A)
// 14-RH VENT 5 MOTOR 2/CLOSE A (CL/2A)
// 15-RH VENT 5 MOTOR 2/OPEN A (OP/2A)
inline constexpr unsigned int SCP_FF2_IOM10_CH2_DATA = 0x00158;// INTEGER SINGLE

// MDM FF3 output
// 0-LH VENT 3 MOTOR 1/OPEN B (OP/1B)
// 1-LH VENTS 1/2 MOTOR 1/OPEN B (OP/1B)
// 2-LH VENTS 1/2 MOTOR 1/PURGE B (PG/1B)
inline constexpr unsigned int SCP_FF3_IOM2_CH0_DATA = 0x00159;// INTEGER SINGLE
// 0-F7 LIGHT: R MPS AMBER STATUS
// 6-LH VENTS 4/7 MOTOR 1/CLOSE B (CL/1B)
// 7-F6 LIGHT B: RCS CMD "ROLL LEFT"
// 8-F6 LIGHT B: RCS CMD "ROLL RIGHT"
// 9-F6 LIGHT B: RCS CMD "YAW LEFT"
// 10-F6 LIGHT B: RCS CMD "YAW RIGHT"
// 11-F6 LIGHT B: RCS CMD "PITCH UP"
// 12-F6 LIGHT B: RCS CMD "PITCH DOWN"
// 13-A6 LIGHT: AFT DAP CONTROL "AUTO"
// 14-A6 LIGHT: AFT DAP SELECT "A"
// 15-A6 LIGHT: AFT DAP RCS JETS "NORM"
inline constexpr unsigned int SCP_FF3_IOM2_CH1_DATA = 0x0015a;// INTEGER SINGLE
// 3-A6 LIGHT: AFT DAP CONTROL "MAN"
// 4-A6 LIGHT: AFT DAP SELECT "B"
// 5-A6 LIGHT: AFT DAP RCS JETS "VERN"
// 6-LH VENT 3 MOTOR 1/CLOSE B (CL/1B)
// 7-LH VENTS 1/2 MOTOR 1/CLOSE B (CL/1B)
// 9-LH VENTS 4/7 MOTOR 1/OPEN B (OP/1B)
// 10-RH VENT 6 MOTOR 1/CLOSE B (CL/1B)
// 11-RH VENT 6 MOTOR 1/OPEN B (OP/1B)
// 12-RH VENT 6 MOTOR 1/PRG-1 B (P1/1B)
// 13-RH VENT 6 MOTOR 1/PRG-2 B (P2/1B)
// 14-LH VENT 5 MOTOR 1/CLOSE B (CL/1B)
// 15-LH VENT 5 MOTOR 1/OPEN B (OP/1B)
inline constexpr unsigned int SCP_FF3_IOM2_CH2_DATA = 0x0015b;// INTEGER SINGLE
// 0-LH VENTS 1/2 MOTOR 1/CLOSE A (CL/1A)
// 1-LH VENTS 1/2 MOTOR 1/OPEN A (OP/1A)
// 2-LH VENT 3 MOTOR 1/OPEN A (OP/1A)
// 4-F4 LIGHT: RH FCS BODY FLAP "AUTO"
// 5-F4 LIGHT: RH FCS SPEED BK "AUTO"
// 6-F4 LIGHT: RH FCS PITCH "AUTO"
// 7-F4 LIGHT: RH FCS ROLL/YAW "AUTO"
inline constexpr unsigned int SCP_FF3_IOM10_CH0_DATA = 0x0015c;// INTEGER SINGLE
// 0-F7 LIGHT: R MPS RED STATUS
// 1-A6 LIGHT: AFT MAN ROT ROLL "DISC RT"
// 2-A6 LIGHT: AFT MAN ROT ROLL "ACCEL"
// 3-A6 LIGHT: AFT MAN ROT ROLL "PULSE"
// 4-A6 LIGHT: AFT MAN ROT PITCH "DISC RT"
// 5-A6 LIGHT: AFT MAN ROT PITCH "ACCEL"
// 6-A6 LIGHT: AFT MAN ROT PITCH "PULSE"
// 7-A6 LIGHT: AFT MAN ROT YAW "DISC RT"
// 8-A6 LIGHT: AFT MAN ROT YAW "ACCEL"
// 9-A6 LIGHT: AFT MAN ROT YAW "PULSE"
// 10-A6 LIGHT: AFT MAN TRANS X "NORM"
// 11-A6 LIGHT: AFT MAN TRANS X "PULSE"
// 12-A6 LIGHT: AFT MAN TRANS X "LVLH"
// 13-A6 LIGHT: AFT MAN TRANS Y "NORM"
// 14-A6 LIGHT: AFT MAN TRANS Y "PULSE"
// 15-A6 LIGHT: AFT MAN TRANS Y "LOW Z"
inline constexpr unsigned int SCP_FF3_IOM10_CH1_DATA = 0x0015d;// INTEGER SINGLE
// 0-A6 LIGHT: AFT MAN TRANS Z "NORM"
// 1-A6 LIGHT: AFT MAN TRANS Z "PULSE"
// 2-A6 LIGHT: AFT MAN TRANS Z "HIGH"
// 6-LH VENT 3 MOTOR 1/CLOSE A (CL/1A)
// 7-LH VENTS 1/2 MOTOR 1/PURGE A (PG/1A)
// 8-LH VENTS 4/7 MOTOR 1/CLOSE A (CL/1A)
// 9-LH VENTS 4/7 MOTOR 1/OPEN A (OP/1A)
// 10-RH VENT 6 MOTOR 1/CLOSE A (CL/1A)
// 11-RH VENT 6 MOTOR 1/OPEN A (OP/1A)
// 12-RH VENT 6 MOTOR 1/PRG-1 A (P1/1A)
// 13-RH VENT 6 MOTOR 1/PRG-2 A (P2/1A)
// 14-LH VENT 5 MOTOR 1/CLOSE A (CL/1A)
// 15-LH VENT 5 MOTOR 1/OPEN A (OP/1A)
inline constexpr unsigned int SCP_FF3_IOM10_CH2_DATA = 0x0015e;// INTEGER SINGLE

// MDM FF4 output
// 0-RH VENT 3 MOTOR 2/OPEN B (OP/2B)
// 1-RH VENTS 1/2 MOTOR 2/OPEN B (OP/2B)
// 2-RH VENTS 1/2 MOTOR 2/PURGE B (PG/2B)
inline constexpr unsigned int SCP_FF4_IOM2_CH0_DATA = 0x0015f;// INTEGER SINGLE
// 6-LH VENT 5 MOTOR 2/CLOSE B (CL/2B)
inline constexpr unsigned int SCP_FF4_IOM2_CH1_DATA = 0x00160;// INTEGER SINGLE
// 6-RH VENT 3 MOTOR 2/CLOSE B (CL/2B)
// 7-RH VENTS 1/2 MOTOR 2/CLOSE B (CL/2B)
// 8-RH VENTS 4/7 MOTOR 1/CLOSE B (CL/1B)
// 9-RH VENTS 4/7 MOTOR 1/OPEN B (OP/1B)
// 10-LH VENT 6 MOTOR 2/CLOSE B (CL/2B)
// 11-LH VENT 6 MOTOR 2/OPEN B (OP/2B)
// 12-LH VENT 6 MOTOR 2/PRG-1 B (P1/2B)
// 13-LH VENT 6 MOTOR 2/PRG-2 B (P2/2B)
// 15-LH VENT 5 MOTOR 2/OPEN B (OP/2B)
inline constexpr unsigned int SCP_FF4_IOM2_CH2_DATA = 0x00161;// INTEGER SINGLE
// 0-FWD EVENT TIMER: LIFT OFF TIMER_RESET
inline constexpr unsigned int SCP_FF4_IOM5_CH1_DATA = 0x00162;// INTEGER SINGLE
// 0-RH VENTS 1/2 MOTOR 2/CLOSE A (CL/2A)
// 1-RH VENTS 1/2 MOTOR 2/OPEN A (OP/2A)
// 2-RH VENT 3 MOTOR 2/OPEN A (OP/2A)
// 4-F4 LIGHT: RH FCS BODY FLAP "MAN"
// 5-F4 LIGHT: RH FCS SPEED BK "MAN"
// 6-F4 LIGHT: RH FCS PITCH "CSS"
// 7-F4 LIGHT: RH FCS ROLL/YAW "CSS"
inline constexpr unsigned int SCP_FF4_IOM10_CH0_DATA = 0x00163;// INTEGER SINGLE
// 6-RH VENT 3 MOTOR 2/CLOSE A (CL/2A)
// 7-RH VENTS 1/2 MOTOR 2/PURGE A (PG/2A)
// 8-RH VENTS 4/7 MOTOR 1/CLOSE A (CL/1A)
// 9-RH VENTS 4/7 MOTOR 1/OPEN A (OP/1A)
// 10-LH VENT 6 MOTOR 2/CLOSE A (CL/2A)
// 11-LH VENT 6 MOTOR 2/OPEN A (OP/2A)
// 12-LH VENT 6 MOTOR 2/PRG-1 A (P1/2A)
// 13-LH VENT 6 MOTOR 2/PRG-2 A (P2/2A)
// 14-LH VENT 5 MOTOR 2/CLOSE A (CL/2A)
// 15-LH VENT 5 MOTOR 2/OPEN A (OP/2A)
inline constexpr unsigned int SCP_FF4_IOM10_CH2_DATA = 0x00164;// INTEGER SINGLE

// MDM FA1 output
// 4-LH VENTS 8/9 MOTOR 1/CLOSE A (CL/1A)
// 5-LH VENTS 8/9 MOTOR 1/OPEN A (OP/1A)
// 6-LH VENTS 8/9 MOTOR 1/PURGE A (PG/1A)
inline constexpr unsigned int SCP_FA1_IOM7_CH0_DATA = 0x00165;// INTEGER SINGLE
// 3-LH VENTS 8/9 MOTOR 1/CLOSE B (CL/1B)
// 4-LH VENTS 8/9 MOTOR 1/OPEN B (OP/1B)
// 5-LH VENTS 8/9 MOTOR 1/PURGE B (PG/1B)
inline constexpr unsigned int SCP_FA1_IOM15_CH0_DATA = 0x00166;// INTEGER SINGLE

// MDM FA2 output
// 4-RH VENTS 8/9 MOTOR 2/CLOSE A (CL/2A)
// 5-RH VENTS 8/9 MOTOR 2/OPEN A (OP/2A)
// 6-RH VENTS 8/9 MOTOR 2/PURGE A (PG/2A)
inline constexpr unsigned int SCP_FA2_IOM7_CH0_DATA = 0x00167;// INTEGER SINGLE
// 3-RH VENTS 8/9 MOTOR 2/CLOSE B (CL/2B)
// 4-RH VENTS 8/9 MOTOR 2/OPEN B (OP/2B)
// 5-RH VENTS 8/9 MOTOR 2/PURGE B (PG/2B)
inline constexpr unsigned int SCP_FA2_IOM15_CH0_DATA = 0x00168;// INTEGER SINGLE

// MDM FA3 output
// 4-RH VENTS 8/9 MOTOR 1/CLOSE A (CL/1A)
// 5-RH VENTS 8/9 MOTOR 1/OPEN A (OP/1A)
// 6-RH VENTS 8/9 MOTOR 1/PURGE A (PG/1A)
inline constexpr unsigned int SCP_FA3_IOM7_CH0_DATA = 0x00169;// INTEGER SINGLE
// 3-RH VENTS 8/9 MOTOR 1/CLOSE B (CL/1B)
// 4-RH VENTS 8/9 MOTOR 1/OPEN B (OP/1B)
// 5-RH VENTS 8/9 MOTOR 1/PURGE B (PG/1B)
inline constexpr unsigned int SCP_FA3_IOM15_CH0_DATA = 0x0016a;// INTEGER SINGLE

// MDM FA4 output
// 4-LH VENTS 8/9 MOTOR 2/CLOSE A (CL/2A)
// 5-LH VENTS 8/9 MOTOR 2/OPEN A (OP/2A)
// 6-LH VENTS 8/9 MOTOR 2/PURGE A (PG/2A)
inline constexpr unsigned int SCP_FA4_IOM7_CH0_DATA = 0x0016b;// INTEGER SINGLE
// 3-LH VENTS 8/9 MOTOR 2/CLOSE B (CL/2B)
// 4-LH VENTS 8/9 MOTOR 2/OPEN B (OP/2B)
// 5-LH VENTS 8/9 MOTOR 2/PURGE B (PG/2B)
inline constexpr unsigned int SCP_FA4_IOM15_CH0_DATA = 0x0016c;// INTEGER SINGLE

// Radar Altimeter
inline constexpr unsigned int SCP_RA_DATA_CDR_SEL = 0x0016d;// INTEGER SINGLE
inline constexpr unsigned int SCP_RA_VALIDITY_CDR_SEL = 0x0016e;// INTEGER SINGLE
inline constexpr unsigned int SCP_RA_DATA_PLT_SEL = 0x0016f;// INTEGER SINGLE
inline constexpr unsigned int SCP_RA_VALIDITY_PLT_SEL = 0x00170;// INTEGER SINGLE

// DAP PBIs light command
// forward
inline constexpr unsigned int SCP_FWD_DAP_SELECT_A_LT = 0x00171;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_SELECT_B_LT = 0x00172;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_AUTO_LT = 0x00173;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN_INRTL_LT = 0x00174;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN_LVLH_LT = 0x00175;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN_FREE_DFT_LT = 0x00176;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_BLANK_LT = 0x00177;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_X_NORM_LT = 0x00178;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_X_PULSE_LT = 0x00179;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_LOW_Z_LT = 0x0017a;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Y_NORM_LT = 0x0017b;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Y_PULSE_LT = 0x0017c;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Z_HIGH_LT = 0x0017d;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Z_NORM_LT = 0x0017e;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSL_Z_PULSE_LT = 0x0017f;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_JETS_NORM_LT = 0x00180;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_ROLL_DISC_LT = 0x00181;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_ROLL_PULSE_LT = 0x00182;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ALT_PRCS_MODE_LT = 0x00183;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_PITCH_DISC_LT = 0x00184;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_PITCH_PULSE_LT = 0x00185;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_JETS_VERN_LT = 0x00186;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_YAW_DISC_LT = 0x00187;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROT_YAW_PULSE_LT = 0x00188;// INTEGER SINGLE
// aft
inline constexpr unsigned int SCP_AFT_DAP_SELECT_A_LT = 0x00189;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_SELECT_B_LT = 0x0018a;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_AUTO_LT = 0x0018b;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN_INRTL_LT = 0x0018c;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN_LVLH_LT = 0x0018d;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN_FREE_DFT_LT = 0x0018e;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_BLANK_LT = 0x0018f;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_X_NORM_LT = 0x00190;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_X_PULSE_LT = 0x00191;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_LOW_Z_LT = 0x00192;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Y_NORM_LT = 0x00193;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Y_PULSE_LT = 0x00194;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Z_HIGH_LT = 0x00195;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Z_NORM_LT = 0x00196;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSL_Z_PULSE_LT = 0x00197;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_JETS_NORM_LT = 0x00198;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_ROLL_DISC_LT = 0x00199;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_ROLL_PULSE_LT = 0x0019a;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ALT_PRCS_MODE_LT = 0x0019b;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_PITCH_DISC_LT = 0x0019c;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_PITCH_PULSE_LT = 0x0019d;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_JETS_VERN_LT = 0x0019e;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_YAW_DISC_LT = 0x0019f;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROT_YAW_PULSE_LT = 0x001a0;// INTEGER SINGLE

// TAEM parameters
// maximum shuttle orbiter weight [slugs]
inline constexpr unsigned int SCP_WT_GS1 = 0x001a1;// SCALAR DOUBLE
// minimum RPRED to issue OHALRT [ft]
inline constexpr unsigned int SCP_RMOH = 0x001a3;// SCALAR DOUBLE
// HAC turn angle [deg]
inline constexpr unsigned int SCP_PSHA = 0x001a5;// SCALAR DOUBLE
// HAC radius [ft]
inline constexpr unsigned int SCP_RTURN = 0x001a7;// SCALAR DOUBLE
// R/L cone indicator [1]
inline constexpr unsigned int SCP_YSGN = 0x001a9;// SCALAR DOUBLE
// PSHA reset value [deg]
inline constexpr unsigned int SCP_PSHARS = 0x001ab;// SCALAR DOUBLE
// initial HAC spiral turn radius on final [ft]
inline constexpr unsigned int SCP_RF0 = 0x001ad;// SCALAR DOUBLE
// linear term in spiral radius eqn. [ft/deg]
inline constexpr unsigned int SCP_R1 = 0x001af;// SCALAR DOUBLE
// quadratic term in spiral radius eqn. [ft/deg]
inline constexpr unsigned int SCP_R2 = 0x001b1;// SCALAR DOUBLE

// Autoland parameters
// pullup circle radius (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_AL_R = 0x001b3;// MATRIX(2,2) DOUBLE
// pullup circle center (x) (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_X_K = 0x001bb;// MATRIX(2,2) DOUBLE
// pullup circle center (h) (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_H_K = 0x001c3;// MATRIX(2,2) DOUBLE
// exponential/circle tangency range (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_X_EXP = 0x001cb;// MATRIX(2,2) DOUBLE
// exponential decay (indexed by IGI,IGS) [ft]
inline constexpr unsigned int SCP_H_DECAY = 0x001d3;// MATRIX(2,2) DOUBLE
// exponential decay factor [1]
inline constexpr unsigned int SCP_SIGMA = 0x001db;// SCALAR DOUBLE
// steep glideslop angle (indexed by IGS) [deg]
inline constexpr unsigned int SCP_GAMMA_REF_1 = 0x001dd;// VECTOR(2) DOUBLE
// shallow glideslop angle [deg]
inline constexpr unsigned int SCP_GAMMA_REF_2 = 0x001e1;// SCALAR DOUBLE
// steep glide slope aim point (indexed by IGI) [ft]
inline constexpr unsigned int SCP_X_ZERO = 0x001e3;// VECTOR(2) DOUBLE
// shallow glide slope aim point [ft]
inline constexpr unsigned int SCP_X_AIM = 0x001e7;// SCALAR DOUBLE
// open-loop pull-up altitude [ft]
inline constexpr unsigned int SCP_H_FLARE = 0x001e9;// SCALAR DOUBLE
// closed-loop pull-up altitude [ft]
inline constexpr unsigned int SCP_H_CLOOP = 0x001eb;// SCALAR DOUBLE

// runway approach mode (1-overhead; 2-strait-in)
inline constexpr unsigned int SCP_OVHD = 0x001ed;// INTEGER SINGLE
// glide slope (1-light; 2-heavy)
inline constexpr unsigned int SCP_IGS = 0x001ee;// INTEGER SINGLE
// aimpoint (1-nom; 2-close-in)
inline constexpr unsigned int SCP_IGI = 0x001ef;// INTEGER SINGLE
// runway ID (1-pri; 2-sec)
inline constexpr unsigned int SCP_RWID = 0x001f0;// INTEGER SINGLE
// previous runway ID (1-pri; 2-sec)
inline constexpr unsigned int SCP_RWID0 = 0x001f1;// INTEGER SINGLE
// landing site ID [1,45]
inline constexpr unsigned int SCP_LSID = 0x001f2;// INTEGER SINGLE

// speedbrake logic select (1-nom; 2-short; 3-ELS)
inline constexpr unsigned int SCP_SB_SEL = 0x001f3;// INTEGER SINGLE

// pri runway name
inline constexpr unsigned int SCP_PRI_ID = 0x001f4;// CHARACTER(5)
// pri runway heading [deg]
inline constexpr unsigned int SCP_PRI_HDG = 0x001f9;// SCALAR DOUBLE
// pri runway pos (greenwich=ECEF) [ft]
inline constexpr unsigned int SCP_PRI_POS = 0x001fb;// VECTOR(3) DOUBLE
// pri greenwich(=ECEF)-to-runway matrix [ft]
inline constexpr unsigned int SCP_PRI_G2R = 0x00201;// MATRIX(3,3) DOUBLE
// pri runway length [ft]
inline constexpr unsigned int SCP_PRI_LEN = 0x00213;// INTEGER SINGLE
// sec runway name
inline constexpr unsigned int SCP_SEC_ID = 0x00214;// CHARACTER(5)
// sec runway heading [deg]
inline constexpr unsigned int SCP_SEC_HDG = 0x00219;// SCALAR DOUBLE
// sec runway pos (greenwich=ECEF) [ft]
inline constexpr unsigned int SCP_SEC_POS = 0x0021b;// VECTOR(3) DOUBLE
// sec greenwich(=ECEF)-to-runway matrix [ft]
inline constexpr unsigned int SCP_SEC_G2R = 0x00221;// MATRIX(3,3) DOUBLE
// sec runway length [ft]
inline constexpr unsigned int SCP_SEC_LEN = 0x00233;// INTEGER SINGLE

// Landing SOP
inline constexpr unsigned int SCP_WOWLON = 0x00234;// INTEGER SINGLE
inline constexpr unsigned int SCP_FLATTURN = 0x00235;// INTEGER SINGLE
inline constexpr unsigned int SCP_ROLLOUT = 0x00236;// INTEGER SINGLE
inline constexpr unsigned int SCP_GSENBL = 0x00237;// INTEGER SINGLE
inline constexpr unsigned int SCP_HUD_WOWLON = 0x00238;// INTEGER SINGLE
inline constexpr unsigned int SCP_HUD_ROLLOUT = 0x00239;// INTEGER SINGLE

// Aerojet DAP FCS
// AerojetDAP FCS pitch control (1-AUTO; 2-CSS)
inline constexpr unsigned int SCP_AEROJET_FCS_PITCH = 0x0023a;// INTEGER SINGLE
// AerojetDAP FCS roll control (1-AUTO; 2-CSS)
inline constexpr unsigned int SCP_AEROJET_FCS_ROLL = 0x0023b;// INTEGER SINGLE
// AerojetDAP FCS speedbrake control (1-AUTO; 2-CDR; 3-PLT)
inline constexpr unsigned int SCP_AEROJET_FCS_SB = 0x0023c;// INTEGER SINGLE
// AerojetDAP body flap control (1-AUTO; 2-CSS)
inline constexpr unsigned int SCP_AEROJET_FCS_BF = 0x0023d;// INTEGER SINGLE
// number of RCS roll jets to fire (+right, -left) [1]
inline constexpr unsigned int SCP_UXCMD = 0x0023e;// INTEGER SINGLE
// number of RCS pitch jets to fire (+up, -down) [1]
inline constexpr unsigned int SCP_UYCMD = 0x0023f;// INTEGER SINGLE
// number of RCS yaw jets to fire (+right, -left) [1]
inline constexpr unsigned int SCP_UZCMD = 0x00240;// INTEGER SINGLE
// aileron trim [deg]
inline constexpr unsigned int SCP_DATRIM = 0x00241;// SCALAR DOUBLE
// rudder trim [deg]
inline constexpr unsigned int SCP_DRTRIM = 0x00243;// SCALAR DOUBLE
// NY trim [g]
inline constexpr unsigned int SCP_DRTI = 0x00245;// SCALAR DOUBLE
// NZ error [g]
inline constexpr unsigned int SCP_NZERR = 0x00247;// SCALAR DOUBLE
// bank error [deg]
inline constexpr unsigned int SCP_BANKERR = 0x00249;// SCALAR DOUBLE
// wraparound DAP mode (0=INH, 1=ENA, 2=ACT)
inline constexpr unsigned int SCP_WRAP = 0x0024b;// INTEGER SINGLE
// elevator command [deg]
inline constexpr unsigned int SCP_DECC = 0x0024c;// SCALAR DOUBLE
// aileron command [deg]
inline constexpr unsigned int SCP_DAC = 0x0024e;// SCALAR DOUBLE
// rudder command [deg]
inline constexpr unsigned int SCP_DRC = 0x00250;// SCALAR DOUBLE
// speedbrake command [deg]
inline constexpr unsigned int SCP_DSBC = 0x00252;// SCALAR DOUBLE
// NWS command [deg]
inline constexpr unsigned int SCP_DNWC = 0x00254;// SCALAR DOUBLE
// Entry Mode switch "Low Gain" selected
inline constexpr unsigned int SCP_SEL_L_GAIN = 0x00256;// INTEGER SINGLE
// Entry Mode switch "No Yaw Jet" selected
inline constexpr unsigned int SCP_SEL_NO_Y_JET = 0x00257;// INTEGER SINGLE
// Entry Mode switch override
inline constexpr unsigned int SCP_ENTRY_SW_OVERRIDE = 0x00258;// INTEGER SINGLE

// A/L UPP
// geodetic altitude of vehicle center of mass above rw [ft]
inline constexpr unsigned int SCP_H = 0x00259;// SCALAR DOUBLE
// negative z component of velocity in topodetic coordinates [fps]
inline constexpr unsigned int SCP_HDOT = 0x0025b;// SCALAR DOUBLE
// true airspeed [fps]
inline constexpr unsigned int SCP_V_T = 0x0025d;// SCALAR DOUBLE
// equivalent? airspeed [fps]
inline constexpr unsigned int SCP_V_I = 0x0025f;// SCALAR DOUBLE
// equivalent airspeed [knots]
inline constexpr unsigned int SCP_KEAS = 0x00261;// SCALAR DOUBLE
// topodetic horizontal component of earth relative velocity [fps]
inline constexpr unsigned int SCP_VG = 0x00263;// SCALAR DOUBLE
// vehicle position in runway coordinates [ft]
inline constexpr unsigned int SCP_X = 0x00265;// SCALAR DOUBLE
inline constexpr unsigned int SCP_Y = 0x00267;// SCALAR DOUBLE
inline constexpr unsigned int SCP_Z = 0x00269;// SCALAR DOUBLE
// vehicle velocity in runway coordinates [fps]
inline constexpr unsigned int SCP_XDOT = 0x0026b;// SCALAR DOUBLE
inline constexpr unsigned int SCP_YDOT = 0x0026d;// SCALAR DOUBLE
// heading [deg]
inline constexpr unsigned int SCP_HDG = 0x0026f;// SCALAR DOUBLE
// topodetic earth relative flight-path angle [deg]
inline constexpr unsigned int SCP_GAMMA = 0x00271;// SCALAR DOUBLE
// roll [deg]
inline constexpr unsigned int SCP_PHI = 0x00273;// SCALAR DOUBLE
// cosine of body roll euler angle [1]
inline constexpr unsigned int SCP_COSPHI = 0x00275;// SCALAR DOUBLE
// sine of body roll euler angle [1]
inline constexpr unsigned int SCP_SINPHI = 0x00277;// SCALAR DOUBLE
// tangent of body roll euler angle [1]
inline constexpr unsigned int SCP_TANPHI = 0x00279;// SCALAR DOUBLE
// cosine of angle of attack [1]
inline constexpr unsigned int SCP_COSALF = 0x0027b;// SCALAR DOUBLE
// sine of angle of attack [1]
inline constexpr unsigned int SCP_SINALF = 0x0027d;// SCALAR DOUBLE
// pitch [deg]
inline constexpr unsigned int SCP_THETA = 0x0027f;// SCALAR DOUBLE
// cosine of theta [1]
inline constexpr unsigned int SCP_COSTH = 0x00281;// SCALAR DOUBLE
// sine of theta [1]
inline constexpr unsigned int SCP_SINTH = 0x00283;// SCALAR DOUBLE
// angle-of-attack [deg]
inline constexpr unsigned int SCP_ALPHA = 0x00285;// SCALAR DOUBLE
// sideslip [deg]
inline constexpr unsigned int SCP_BETA = 0x00287;// SCALAR DOUBLE
// dynamic pressure [psf]
inline constexpr unsigned int SCP_QBAR = 0x00289;// SCALAR DOUBLE
// lateral acceleration [g]
inline constexpr unsigned int SCP_NY = 0x0028b;// SCALAR DOUBLE
// normal acceleration [g]
inline constexpr unsigned int SCP_NZ = 0x0028d;// SCALAR DOUBLE
// orbiter mass [slugs]
inline constexpr unsigned int SCP_WEIGHT = 0x0028f;// SCALAR DOUBLE
// body roll rate [deg/s]
inline constexpr unsigned int SCP_P = 0x00291;// SCALAR DOUBLE
// body pitch rate [deg/s]
inline constexpr unsigned int SCP_Q = 0x00293;// SCALAR DOUBLE
// body yaw rate [deg/s]
inline constexpr unsigned int SCP_R = 0x00295;// SCALAR DOUBLE

// TAEM UPP
// mach number [1]
inline constexpr unsigned int SCP_MACH = 0x00297;// SCALAR DOUBLE
// course with respect to centerline [deg]
inline constexpr unsigned int SCP_PSD = 0x00299;// SCALAR DOUBLE

// Entry UPP
// vehicle position in ECEF [ft]
inline constexpr unsigned int SCP_ECEF_POS = 0x0029b;// VECTOR(3) DOUBLE
// vehicle velocity in ECEF [fps]
inline constexpr unsigned int SCP_ECEF_VEL = 0x002a1;// VECTOR(3) DOUBLE
// current relative velocity [fps]
inline constexpr unsigned int SCP_VE = 0x002a7;// SCALAR DOUBLE
// current inertial velocity [fps]
inline constexpr unsigned int SCP_VI = 0x002a9;// SCALAR DOUBLE
// current drag acceleration [fps^2]
inline constexpr unsigned int SCP_DRAG = 0x002ab;// SCALAR DOUBLE
// current lift/drag ratio [1]
inline constexpr unsigned int SCP_LOD = 0x002ad;// SCALAR DOUBLE
// current load factor [fps^2]
inline constexpr unsigned int SCP_XLFAC = 0x002af;// SCALAR DOUBLE

// EGRT output
// azimuth error [rad]
inline constexpr unsigned int SCP_DELAZ = 0x002b1;// SCALAR DOUBLE
// range to target [NM]
inline constexpr unsigned int SCP_TRANG = 0x002b3;// SCALAR DOUBLE

// Autoland guidance output
// autoland phase counter
inline constexpr unsigned int SCP_PMODE = 0x002b5;// INTEGER SINGLE
// FSGS phase counter
inline constexpr unsigned int SCP_FMODE = 0x002b6;// INTEGER SINGLE
// autoland NZ command [g]
inline constexpr unsigned int SCP_NZ_CMD = 0x002b7;// SCALAR DOUBLE
// autoland roll angle command [deg]
inline constexpr unsigned int SCP_PHIC_AL = 0x002b9;// SCALAR DOUBLE
// autoland yaw rate command post WOWLON
inline constexpr unsigned int SCP_RC = 0x002bb;// SCALAR DOUBLE
// autoland speedbrake command [deg]
inline constexpr unsigned int SCP_DSBC_AL = 0x002bd;// SCALAR DOUBLE
// body flap retract command
inline constexpr unsigned int SCP_RETRACT_BF = 0x002bf;// INTEGER SINGLE
// altitude error [ft]
inline constexpr unsigned int SCP_HERR = 0x002c0;// SCALAR DOUBLE

// TAEM guidance output
// heading error to HAC tangency [deg]
inline constexpr unsigned int SCP_DPSAC = 0x002c2;// SCALAR DOUBLE
// predicted range to rw [ft]
inline constexpr unsigned int SCP_RPRED = 0x002c4;// SCALAR DOUBLE
// commanded body normal load factor increment from equilibrium [g]
inline constexpr unsigned int SCP_NZC = 0x002c6;// SCALAR DOUBLE
// speedbrake angle command (hinge line) [deg]
inline constexpr unsigned int SCP_DSBC_AT = 0x002c8;// SCALAR DOUBLE
// roll angle command
inline constexpr unsigned int SCP_PHIC_AT = 0x002ca;// SCALAR DOUBLE
// minimum entry point flag
inline constexpr unsigned int SCP_MEP = 0x002cc;// INTEGER SINGLE
// TAEM phase counter [1]
inline constexpr unsigned int SCP_IPHASE = 0x002cd;// INTEGER SINGLE
// TAEM end flag
inline constexpr unsigned int SCP_TG_END = 0x002ce;// INTEGER SINGLE
// current HAC final size [ft]
inline constexpr unsigned int SCP_RF = 0x002cf;// SCALAR DOUBLE
// HAC X position [ft]
inline constexpr unsigned int SCP_XHAC = 0x002d1;// SCALAR DOUBLE
// distance from OV to HAC center [ft]
inline constexpr unsigned int SCP_RCIR = 0x002d3;// SCALAR DOUBLE
// energy per unit weight [ft]
inline constexpr unsigned int SCP_EOW = 0x002d5;// SCALAR DOUBLE
// reference energy [ft]
inline constexpr unsigned int SCP_EN = 0x002d7;// SCALAR DOUBLE
// E/W to start S-turn [ft]
inline constexpr unsigned int SCP_ES = 0x002d9;// SCALAR DOUBLE
// E/W to switch to MEP [ft]
inline constexpr unsigned int SCP_EMEP = 0x002db;// SCALAR DOUBLE
// E/W to downmode to STRN [ft]
inline constexpr unsigned int SCP_EMOH = 0x002dd;// SCALAR DOUBLE
// altitude error from reference profile [ft]
inline constexpr unsigned int SCP_HERROR = 0x002df;// SCALAR DOUBLE
// heading to HAC center [deg]
inline constexpr unsigned int SCP_PSC = 0x002e1;// SCALAR DOUBLE
// estimated time to HAC [sec]
inline constexpr unsigned int SCP_P2TRNT = 0x002e3;// SCALAR DOUBLE

// Entry guidance output
// angle-of-attack command [deg]
inline constexpr unsigned int SCP_ALPCMD = 0x002e5;// SCALAR DOUBLE
// drag reference [fps^2]
inline constexpr unsigned int SCP_DREFP = 0x002e7;// SCALAR DOUBLE
// roll angle command about body axis [deg]
inline constexpr unsigned int SCP_ROLLCMD = 0x002e9;// SCALAR DOUBLE
// roll ref [deg]
inline constexpr unsigned int SCP_ROLLREF = 0x002eb;// SCALAR DOUBLE
// altitude rate reference [fps]
inline constexpr unsigned int SCP_RDTREF = 0x002ed;// SCALAR DOUBLE
// derivative of range wrt drag [NM/fps^2]
inline constexpr unsigned int SCP_DRDD = 0x002ef;// SCALAR DOUBLE
// Rdot feedback term [fps]
inline constexpr unsigned int SCP_DLRDOT = 0x002f1;// SCALAR DOUBLE
// maximum heading error absolute value [rad]
inline constexpr unsigned int SCP_YL = 0x002f3;// SCALAR DOUBLE
// scheduled angle of attack [deg]
inline constexpr unsigned int SCP_ACMD1 = 0x002f5;// SCALAR DOUBLE
// entry guidance subphase counter
inline constexpr unsigned int SCP_ISLECT = 0x002f7;// INTEGER SINGLE
// Entry guidance end flag
inline constexpr unsigned int SCP_EG_END = 0x002f8;// INTEGER SINGLE

// aerosurface position feedback
// left outboard elevon pos [deg]
inline constexpr unsigned int SCP_LOB_ELVN_POS_FDBK = 0x002f9;// SCALAR DOUBLE
// left inboard elevon pos [deg]
inline constexpr unsigned int SCP_LIB_ELVN_POS_FDBK = 0x002fb;// SCALAR DOUBLE
// right inboard elevon pos [deg]
inline constexpr unsigned int SCP_RIB_ELVN_POS_FDBK = 0x002fd;// SCALAR DOUBLE
// right outboard elevon pos [deg]
inline constexpr unsigned int SCP_ROB_ELVN_POS_FDBK = 0x002ff;// SCALAR DOUBLE
// elevator pos [deg]
inline constexpr unsigned int SCP_DEFB = 0x00301;// SCALAR DOUBLE
// aileron pos [deg]
inline constexpr unsigned int SCP_DAFB = 0x00303;// SCALAR DOUBLE
// body flap pos [deg]
inline constexpr unsigned int SCP_DBFOFB = 0x00305;// SCALAR DOUBLE
// rudder pos [deg]
inline constexpr unsigned int SCP_DRFB = 0x00307;// SCALAR DOUBLE
// Speedbrake pos [deg]
inline constexpr unsigned int SCP_DSBFB_DEG = 0x00309;// SCALAR DOUBLE
// Speedbrake pos [%]
inline constexpr unsigned int SCP_DSBFB_PCT = 0x0030b;// SCALAR DOUBLE
// speedbrake increment [deg]
inline constexpr unsigned int SCP_DSBPC = 0x0030d;// SCALAR DOUBLE

// Aerosurface command
// left outboard elevon command [deg]
inline constexpr unsigned int SCP_ELOC = 0x0030f;// SCALAR DOUBLE
// left inboard elevon command [deg]
inline constexpr unsigned int SCP_ELIC = 0x00311;// SCALAR DOUBLE
// right inboard elevon command [deg]
inline constexpr unsigned int SCP_ERIC = 0x00313;// SCALAR DOUBLE
// right outboard elevon command [deg]
inline constexpr unsigned int SCP_EROC = 0x00315;// SCALAR DOUBLE
// body flap command [deg]
inline constexpr unsigned int SCP_DBFRC = 0x00317;// SCALAR DOUBLE
// rudder command [deg]
inline constexpr unsigned int SCP_RUDDER_CMD = 0x00319;// SCALAR DOUBLE
// speedbrake command [deg]
inline constexpr unsigned int SCP_SPEED_BRAKE_CMD = 0x0031b;// SCALAR DOUBLE

// Speedbrake AUTO command [deg]
inline constexpr unsigned int SCP_SB_AUTO_CMD = 0x0031d;// SCALAR DOUBLE

// HUD
// runway to go [ft]
inline constexpr unsigned int SCP_RWTOGO = 0x0031f;// SCALAR DOUBLE
// max deceleration [fps^2]
inline constexpr unsigned int SCP_HUDMAXDECEL = 0x00321;// SCALAR DOUBLE
// speedbrake delta minimum velocity [fps]
inline constexpr unsigned int SCP_SBDMN = 0x00323;// SCALAR DOUBLE
// speedbrake delta maximum velocity [fps]
inline constexpr unsigned int SCP_SBDMX = 0x00325;// SCALAR DOUBLE
// speedbrake delta limit [deg]
inline constexpr unsigned int SCP_SBDLIM = 0x00327;// SCALAR DOUBLE

// Trim Switch positions
inline constexpr unsigned int SCP_LH_RHC_TRIM_INHIBIT = 0x00329;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_TRIM_INHIBIT = 0x0032a;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_PLUS_PITCH_TRIM = 0x0032b;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_MINUS_PITCH_TRIM = 0x0032c;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_PLUS_ROLL_TRIM = 0x0032d;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_RHC_MINUS_ROLL_TRIM = 0x0032e;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_PLUS_PITCH_TRIM = 0x0032f;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_MINUS_PITCH_TRIM = 0x00330;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_PLUS_ROLL_TRIM = 0x00331;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_RHC_MINUS_ROLL_TRIM = 0x00332;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_PLUS_PITCH_TRIM = 0x00333;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_MINUS_PITCH_TRIM = 0x00334;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_PLUS_ROLL_TRIM = 0x00335;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_MINUS_ROLL_TRIM = 0x00336;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_PLUS_YAW_TRIM = 0x00337;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_MINUS_YAW_TRIM = 0x00338;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_PLUS_PITCH_TRIM = 0x00339;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_MINUS_PITCH_TRIM = 0x0033a;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_PLUS_ROLL_TRIM = 0x0033b;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_MINUS_ROLL_TRIM = 0x0033c;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_PLUS_YAW_TRIM = 0x0033d;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_MINUS_YAW_TRIM = 0x0033e;// INTEGER SINGLE
inline constexpr unsigned int SCP_DETM_RHC = 0x0033f;// INTEGER SINGLE
inline constexpr unsigned int SCP_DATM_RHC = 0x00340;// INTEGER SINGLE
inline constexpr unsigned int SCP_DETM_PAN = 0x00341;// INTEGER SINGLE
inline constexpr unsigned int SCP_DATM_PAN = 0x00342;// INTEGER SINGLE
inline constexpr unsigned int SCP_DRT = 0x00343;// INTEGER SINGLE

// Body Flap Switch positions
inline constexpr unsigned int SCP_LH_BODY_FLAP_UP = 0x00344;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_BODY_FLAP_DOWN = 0x00345;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_BODY_FLAP_UP = 0x00346;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_BODY_FLAP_DOWN = 0x00347;// INTEGER SINGLE
inline constexpr unsigned int SCP_DBFMAN = 0x00348;// INTEGER SINGLE

// MPS switches
inline constexpr unsigned int SCP_MPS_BACKUP_LH2_PRPLT_DUMP_START = 0x00349;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_BACKUP_LH2_PRPLT_DUMP_STOP = 0x0034a;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_PRPLT_DUMP_SEQUENCE_START = 0x0034b;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_PRPLT_DUMP_SEQUENCE_STOP = 0x0034c;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ENG_LIMIT_CONTROL_ENABLE = 0x0034d;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ENG_LIMIT_CONTROL_INHIBIT = 0x0034e;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ENG_LIMIT_CONTROL_AUTO = 0x0034f;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ME_1_SHUTDOWN_CMD = 0x00350;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ME_2_SHUTDOWN_CMD = 0x00351;// INTEGER SINGLE
inline constexpr unsigned int SCP_MPS_ME_3_SHUTDOWN_CMD = 0x00352;// INTEGER SINGLE

// Separation switches
inline constexpr unsigned int SCP_SRB_SEPARATION_AUTO_CMD = 0x00353;// INTEGER SINGLE
inline constexpr unsigned int SCP_SRB_SEPARATION_MANUAL_AUTO_ENABLE_CMD = 0x00354;// INTEGER SINGLE
inline constexpr unsigned int SCP_SRB_SEPARATION_INITIATE_CMD = 0x00355;// INTEGER SINGLE
inline constexpr unsigned int SCP_ET_SEPARATION_MANUAL_ENABLE_CMD = 0x00356;// INTEGER SINGLE
inline constexpr unsigned int SCP_ET_SEPARATION_INITIATE_CMD = 0x00357;// INTEGER SINGLE
inline constexpr unsigned int SCP_ET_SEPARATION_AUTO_CMD = 0x00358;// INTEGER SINGLE

// (0-"-Z"; 1-"-X")
inline constexpr unsigned int SCP_SENSE_SWITCH = 0x00359;// INTEGER SINGLE

// FCS PBIs
inline constexpr unsigned int SCP_FCS_LH_PITCH_AUTO_MODE = 0x0035a;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_LH_PITCH_CSS_MODE = 0x0035b;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_LH_RY_AUTO_MODE = 0x0035c;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_LH_RY_CSS_MODE = 0x0035d;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_BODY_FLAP_AUTO_MANUAL = 0x0035e;// INTEGER SINGLE
inline constexpr unsigned int SCP_LH_SPD_BK_THROT_AUTO_MAN = 0x0035f;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_PITCH_AUTO_MODE = 0x00360;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_PITCH_CSS_MODE = 0x00361;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_RY_AUTO_MODE = 0x00362;// INTEGER SINGLE
inline constexpr unsigned int SCP_FCS_RH_RY_CSS_MODE = 0x00363;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_BODY_FLAP_AUTO_MANUAL = 0x00364;// INTEGER SINGLE
inline constexpr unsigned int SCP_RH_SPD_BK_THROT_AUTO_MAN = 0x00365;// INTEGER SINGLE

// Orbit DAP PBIs
inline constexpr unsigned int SCP_FWD_DAP_SELECT_A = 0x00366;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_SELECT_B = 0x00367;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_AUTO = 0x00368;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_DAP_MAN = 0x00369;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_OPTIONS_NORM = 0x0036a;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_RCS_OPTIONS_VERNIER = 0x0036b;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_ROLL_DISC_RATE = 0x0036c;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_ROLL_ACCEL = 0x0036d;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_ROLL_PULSE = 0x0036e;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_PITCH_DISC_RATE = 0x0036f;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_PITCH_ACCEL = 0x00370;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_PITCH_PULSE = 0x00371;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_YAW_DISC_RATE = 0x00372;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_YAW_ACCEL = 0x00373;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_ROTATION_YAW_PULSE = 0x00374;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_X_NORM = 0x00375;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_X_PULSE = 0x00376;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_X_LVLH = 0x00377;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Y_NORM = 0x00378;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Y_PULSE = 0x00379;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Y_LOW_Z = 0x0037a;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Z_NORM = 0x0037b;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Z_PULSE = 0x0037c;// INTEGER SINGLE
inline constexpr unsigned int SCP_FWD_TRANSLATION_Z_HIGH = 0x0037d;// INTEGER SINGLE

inline constexpr unsigned int SCP_AFT_DAP_SELECT_A = 0x0037e;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_SELECT_B = 0x0037f;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_AUTO = 0x00380;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_DAP_MAN = 0x00381;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_OPTIONS_NORM = 0x00382;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_RCS_OPTIONS_VERNIER = 0x00383;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_ROLL_DISC_RATE = 0x00384;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_ROLL_ACCEL = 0x00385;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_ROLL_PULSE = 0x00386;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_PITCH_DISC_RATE = 0x00387;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_PITCH_ACCEL = 0x00388;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_PITCH_PULSE = 0x00389;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_YAW_DISC_RATE = 0x0038a;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_YAW_ACCEL = 0x0038b;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_ROTATION_YAW_PULSE = 0x0038c;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_X_NORM = 0x0038d;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_X_PULSE = 0x0038e;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_X_LVLH = 0x0038f;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Y_NORM = 0x00390;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Y_PULSE = 0x00391;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Y_LOW_Z = 0x00392;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Z_NORM = 0x00393;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Z_PULSE = 0x00394;// INTEGER SINGLE
inline constexpr unsigned int SCP_AFT_TRANSLATION_Z_HIGH = 0x00395;// INTEGER SINGLE

// Ascent
inline constexpr unsigned int SCP_KMIN = 0x00396;// INTEGER SINGLE
inline constexpr unsigned int SCP_KMAX = 0x00397;// INTEGER SINGLE
// (0-KMAX_NOM; 1-KMAX_SECONDARY; 2-KMAX_ABORT)
inline constexpr unsigned int SCP_KMAX_SEL = 0x00398;// INTEGER SINGLE
// MPS dump complete flag
inline constexpr unsigned int SCP_MPS_LO2_DUMP_STOP = 0x00399;// INTEGER SINGLE

// Vent Doors
// Config Vent Doors for Launch cmd
inline constexpr unsigned int SCP_CONF_VENT_DOORS = 0x0039a;// INTEGER SINGLE
// Orbiter Vent Doors status word
inline constexpr unsigned int SCP_ORBITER_VENT_DOORS_STATUS_WORD = 0x0039b;// INTEGER DOUBLE
// Manual Vent Door close/open command
inline constexpr unsigned int SCP_VENT_DOOR_SEQ_INIT = 0x0039d;// INTEGER SINGLE
// Manual Vent Door close cmd
inline constexpr unsigned int SCP_ALL_VENT_CLOSE_CMD = 0x0039e;// INTEGER SINGLE
// Vent Door position indication (0-no info, 1-open, 2-closed)
inline constexpr unsigned int SCP_VENT_DOOR_POS_IND = 0x0039f;// INTEGER SINGLE

inline constexpr unsigned int SIMPLECOMPOOL_SIZE = 928;

#endif// _COMPOOL_H_
